### ISSUE TITLE
Make more `wsdl2java` options configurable via `application.properties`

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#1007]
Additional options can currently be passed to `wsdl2java` via `additional-params`, e.g.

```
quarkus.cxf.codegen.wsdl2java.bar-params.additional-params = -wsdlLocation,wsdl/bar.wsdl,-xjc-Xts
```

It would be nice to have a few more, definitely not all. 
https://cxf.apache.org/docs/wsdl-to-java.html

The above example would become something like

```
quarkus.cxf.codegen.wsdl2java.bar-params.wsdl-location = wsdl/bar.wsdl
quarkus.cxf.codegen.wsdl2java.bar-params.xjc = ts
```

**Comment by manubell** [comment]
Would love if it were possible to reference/use wsdl by URL as well. However from a quick glance at the code I feel like that would require a lot more changes. Probably worth a separate ticket if it were to be considered.

In my projects I only use quarkus-cxf for soap clients, and for all of them I still use the cxf-codegen-plugin where I generate clients like
```
<wsdlOption>
     <wsdl>http://something.com/service?WSDL</wsdl>
</wsdlOption>
```

Also thanks for the work you do on quarkus-cxf. It is all much appreciated. 😉

**Comment by ppalaga** [comment]
> Would love if it were possible to reference/use wsdl by URL as well. However from a quick glance at the code I feel like that would require a lot more changes. Probably worth a separate ticket if it were to be considered.
> 
> In my projects I only use quarkus-cxf for soap clients, and for all of them I still use the cxf-codegen-plugin where I generate clients like
> 
> ```
> <wsdlOption>
>      <wsdl>http://something.com/service?WSDL</wsdl>
> </wsdlOption>
> ```
> 
> Also thanks for the work you do on quarkus-cxf. It is all much appreciated. 😉

Could you please file a separate issue?
