### ISSUE TITLE
Remove usage of DevConsoleRuntimeTemplateInfoBuildItem

### ISSUE THREAD

**Issue by jamesnetherton** [quarkiverse/quarkus-cxf#1014]
`DevConsoleRuntimeTemplateInfoBuildItem` is deprecated and is planned for removal in Quarkus 3.5.x:

https://groups.google.com/g/quarkus-platform-coordination/c/WNnE9lGxESc/m/K-WxR1z4AwAJ

**Comment by jamesnetherton** [comment]
Looks like it got addressed in https://github.com/quarkiverse/quarkus-cxf/commit/977f98c704b00a0e19c3fba4af7aeca015b9c266.

**Comment by ppalaga** [comment]
Thanks for reporting anyway, @jamesnetherton!
