### ISSUE TITLE
soap-binding property ignored in version 2.4.0

### ISSUE THREAD

**Issue by ramiayoub-priv** [quarkiverse/quarkus-cxf#1031]
Quarkus version 3.3.3
Using CXF 2.4.0 no longer respects the soap-binding property when set to http://www.w3.org/2003/05/soap/bindings/HTTP/

in 2.4.0:

**Actual**: Content-Type: text/xml;
**Expected**: Content-Type: application/soap+xml; action="http://yoursouapactionhere"
Additionally in the payload: 

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"> appears instead of <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">

This causes a http 400 bad request with some servers that expect soap1.2 and the content-type this way.

In the previous version 2.3.1 this works as expected. Exactly the same code with 
quarkus.cxf.client."your-soap-client".soap-binding=http://www.w3.org/2003/05/soap/bindings/HTTP/
in application.properties

**Comment by ppalaga** [comment]
Thanks for the report @ramiayoub-priv!
