### ISSUE TITLE
Make the destination folder of `wsdl2java` configurable

### ISSUE THREAD

**Issue by Owlz** [quarkiverse/quarkus-cxf#1045]
Hello Everyone,
By default the wsdl2java tool generates the classes into the `/target/generated-sources/wsdl2java/` folder. 
If you try to change the destination by adding the additional params -d ([as explained here](https://cxf.apache.org/docs/wsdl-to-java.html)) like so:

`quarkus.cxf.codegen.wsdl2java.serviceName.includes = wsdl/serviceName.wsdl
quarkus.cxf.codegen.wsdl2java.serviceName.additional-params = -d, src/main/java/testpackage`

you get the following error message:

`[INFO] [io.quarkiverse.cxf.deployment.codegen.Wsdl2JavaCodeGen] Running wsdl2java -d target/generated-sources/wsdl2java -d  src/main/java/testpackage src/main/resources/wsdl/ServiceName.wsdl
Duplicated option: outputdir
Usage : wsdl2java -fe|-frontend <front-end-name> -db|-databinding <data-binding-name> -wv <wsdl-version> -p <[wsdl-namespace =]package-name>* -sn <service-name> -b <binding-file-name>* -reserveClass <class-name>* -catalog <catalog-file-name> -d <output-directory> -compile -classdir <compile-classes-directory> -impl -server -client -clientjar <jar-file-name> -all -autoNameResolution -allowElementReferences|-aer<=true> -defaultValues<=class-name-for-DefaultValueProvider> -ant -nexclude <schema-namespace [= java-package-name]>* -exsh <(true, false)> -noTypes -dns <Default value is true> -dex <(true, false)> -validate<[=all|basic|none]> -keep -wsdlLocation <wsdlLocation> -xjc<xjc-arguments>* -asyncMethods<[=method1,method2,...]>* -bareMethods<[=method1,method2,...]>* -mimeMethods<[=method1,method2,...]>* -noAddressBinding -faultSerialVersionUID <fault-serialVersionUID> -encoding <encoding> -exceptionSuper <exceptionSuper> -seiSuper <seiSuper>* -mark-generated -suppress-generated-date -maxExtensionStackDepth <maxExtensionStackDepth> -h|-?|-help -version|-v -verbose|-V -quiet|-q|-Q -wsdlList <wsdlurl> `

Is there a way to disable the default -d params so that we can provide our own? We couldn't find anything in the documentation.

**Comment by ppalaga** [comment]
> Is there a way to disable the default -d params so that we can provide our own?

No it is currently not possible. I did it like that because I though no single person in the universe would want the opposite. I wonder what is your motivation to have a custom output directory?

**Comment by Owlz** [comment]
> No it is currently not possible. I did it like that because I though no single person in the universe would want the opposite. I wonder what is your motivation to have a custom output directory?

I mean, it is a feature of the very tool you are wrapping. I don't get why removing choice should be considered a good idea.

Our motivation is that the code generated should be treated as normal code and should be put in our src folder so that we can use version control without meddling with the .gitignore

Is there any reason why changing the directory is something that "no single person in the universe would want"?

**Comment by ppalaga** [comment]
> Is there any reason why changing the directory is something that "no single person in the universe would want"?

Your use case sounds legit. There was a great part of irony in what I said (sorry for not marking it as such).

**Comment by ppalaga** [comment]
Would you like to send a PR (including a test)?

**Comment by Owlz** [comment]
> Would you like to send a PR (including a test)?

I have zero knowledge of how to write the test suite, but i'll look around and check what I can do.

**Comment by ppalaga** [comment]
> I have zero knowledge of how to write the test suite, but i'll look around and check what I can do.

It would be enough to modify application.properties in this test module: https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/wsdl2java and then adjust the assertions in https://github.com/quarkiverse/quarkus-cxf/blob/main/integration-tests/wsdl2java/src/test/java/io/quarkiverse/cxf/wsdl2java/it/Wsdl2JavaTest.java

**Comment by ppalaga** [comment]
The feature is underway https://github.com/quarkiverse/quarkus-cxf/pull/1089
There are some gotchas related to setting a custom value. I tried to document them around [here](https://github.com/quarkiverse/quarkus-cxf/pull/1089/files#diff-8b6fa87b3236a95dbc4aef116294cbdca5b1fbf2130a5979b18b17bd15d3eef3R169-R185) 
@Owlz, I hope the feature has some value for you anyway?
