### ISSUE TITLE
Global http-conduit-factory config setting doesn't take effect

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#1047]
I tried setting `quarkus.cxf.http-conduit-factory` to CXFDefault or HttpClientHTTPConduitFactory but I always end up with URLConnectionHTTPConduit, _unless_ I'm seeting `quarkus.cxf.client.myclient.http-conduit-factory` instead.

Looking at the code, it seems like https://github.com/quarkiverse/quarkus-cxf/blob/2.4.1/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/CXFClientInfo.java#L216-L217 is always setting one of the factory impls and the producer will then _always_ set the respective factory property: https://github.com/quarkiverse/quarkus-cxf/blob/2.4.1/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/CxfClientProducer.java#L141-L161
So to me it seems that the global bus setting will never take effect.

PS: All this is without hc5.

**Comment by ppalaga** [comment]
Thanks @famod, this is a good catch. I thought I have covered this situation by a test, but in reality, I haven't. 

https://github.com/quarkiverse/quarkus-cxf/pull/1088 should fix it.
