### ISSUE TITLE
@RequestScoped WebService throws ContextNotActiveException at runtime

### ISSUE THREAD

**Issue by wh81752** [quarkiverse/quarkus-cxf#106]
http://cxf.apache.org/docs/jaxrs-services-configuration.html states:

> When service classes and providers are registered this way, the default life-cycle is 'singleton'. You can override it by setting a "jaxrs.scope" parameter with the value of 'prototype' (equivalent to per-request).

Trying 

```
@RequestScoped
@WebService(endpointInterface = "org.acme.cxf.FruitWebService")
public class FruitWebServiceImpl implements FruitWebService {

  @Override
   List<Fruit> list() { .. }
}
```

does not work. I'm getting 

```
Caused by: javax.enterprise.context.ContextNotActiveException
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:40)
        at FruitWebService_ClientProxy.arc$delegate(FruitWebService_ClientProxy.zig:xx)
        at FruitWebService_ClientProxy.list(FruitWebService_ClientProxy.zig:xx)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
```

Background: The need for a request scoped webservice is that I want to inject a request scoped dependency, especially a a request scoped entity manager.

**Comment by coelho-extremosistemas** [comment]
I am trying to Inject others @RequestScoped instances, into a @Webservice class, return null values.

ps: Change to release 0.4.0-SNAPSHOT
ps2: I need to inject datasource instance

**Comment by wh81752** [comment]
> I am trying to Inject others @RequestScoped instances, into a @webservice class, return null values.

Are you trying to do something like this?
```
/* @ApplicationScoped or just absent */
@WebService(endpointInterface = "org.acme.cxf.FruitWebService")
public class FruitWebServiceImpl implements FruitWebService {

   @Inject
   MyRequestScopedClass  mrsc;
   ..
}
```

Technically this cannot work. Well, you need to have a super-smart proxied instance of MyRequestScopedClass able to delegate to the real instance on a request base, perhaps with ThreadLocal. Don't think this works well with Vert.x.

Returning a "null" instance for "mrsc" above is also not an option. In that case an exception must be thrown while wireing things up. 

If this describes what you are trying to do then I suggest to create a new issue. This issue is about having a RequestScoped (http) webservice which -- if available -- would allow you to naturally inject other RequestScoped instances.

**Comment by shumonsharif** [comment]
@wh81752 @coelho-extremosistemas I believe I addressed both your scenarios via the PR above, would you be able to help test?  Changes are in the securityidentity branch.  cc: @dufoli

**Comment by dufoli** [comment]
I close the ticket because it must be ok now. Reopen, if you have issue ;-)

**Comment by wh81752** [comment]
No need to "re-open" this ticket, works perfectly. Thx for implementing.
