### ISSUE TITLE
quarkus-cxf:jar:2.4.1: Dependency convergence error for org.eclipse.angus:angus-activation:jar:2.0.1

### ISSUE THREAD

**Issue by c-schmitz-tsystems** [quarkiverse/quarkus-cxf#1071]
With would like to introduce version 2.4.1 of quarkus cxf into our project. Our maven enforcer plugin detects the following convergence error:

Dependency convergence error for org.eclipse.angus:angus-activation:jar:2.0.1 paths to dependency are:
+-com.telekom.net4f:inhouse-mapper:jar:1.0-SNAPSHOT
  +-io.quarkiverse.cxf:quarkus-cxf:jar:2.4.1:compile
    +-org.apache.cxf:cxf-rt-frontend-jaxws:jar:4.0.3:compile
      +-org.apache.cxf:cxf-core:jar:4.0.3:compile
        +-org.eclipse.angus:angus-activation:jar:2.0.1:compile
and
+-com.telekom.net4f:inhouse-mapper:jar:1.0-SNAPSHOT
  +-io.quarkiverse.cxf:quarkus-cxf:jar:2.4.1:compile
    +-org.apache.cxf:cxf-rt-frontend-jaxws:jar:4.0.3:compile
      +-org.apache.cxf:cxf-rt-bindings-soap:jar:4.0.3:compile
        +-org.eclipse.angus:angus-activation:jar:2.0.1:compile
and
+-com.telekom.net4f:inhouse-mapper:jar:1.0-SNAPSHOT
  +-io.quarkiverse.cxf:quarkus-cxf:jar:2.4.1:compile
    +-org.apache.cxf:cxf-rt-frontend-jaxws:jar:4.0.3:compile
      +-org.apache.cxf:cxf-rt-frontend-simple:jar:4.0.3:compile
        +-org.eclipse.angus:angus-mail:jar:1.0.0:compile
          +-org.eclipse.angus:angus-activation:jar:1.0.0:runtime
and
+-com.telekom.net4f:inhouse-mapper:jar:1.0-SNAPSHOT
  +-io.quarkiverse.cxf:quarkus-cxf:jar:2.4.1:compile
    +-org.apache.cxf:cxf-rt-frontend-jaxws:jar:4.0.3:compile
      +-org.eclipse.angus:angus-activation:jar:2.0.1:compile

**Comment by ppalaga** [comment]
Sounds like you are not importing our BOM as documented [around here](https://docs.quarkiverse.io/quarkus-cxf/dev/user-guide/create-project.html#dependency-management)?

**Comment by c-schmitz-tsystems** [comment]
Thanks for the reply. We use the quarkus version 2.16.12.Final. The quarkus cxf version 2.4.1 is suitable to this version. The problem relies in the dependency tree of the cxf component itself. I think it is not allowed to include 2 versions of the same component into a parent component project. Maybe this could made problems in the native compilation process too.

**Comment by ppalaga** [comment]
> We use the quarkus version 2.16.12.Final. The quarkus cxf version 2.4.1 is suitable to this version.

Nope. quarkus cxf 2.4.1 is compatible with Quarkus 3.4.x

If you prefer staying on Quarkus 2.x, then I recommend combining the latest Quarkus 2.13.x and Quarkus CXF 1.5.x (which are LTS streams).
Anyway, take care to import the appropriate BOMs. Feel free to paste your pom.xml/Gradle file here if you have any doubts.

**Comment by ppalaga** [comment]
@c-schmitz-tsystems feel free to reopen if needed
