### ISSUE TITLE
Disable CN-Check no more working after upgrade to quarkus-cxf 2.4 (from 1.7)

### ISSUE THREAD

**Issue by sburkard** [quarkiverse/quarkus-cxf#1072]
Hi 

I am currently working on a major dependency update of my project. So I moved **from quarkus-cxf 1.7.3 to quarkus-cxf 2.4.1**. 

To avoid TLS problems due to differences between endpoint URLs and certificate CNames, I **disabled CN-Check in my project** as follows

```
    void onStart(@Observes StartupEvent ev) {
        log.info("Enter Startup Observer to configure CXF CnCheck");
        HTTPConduitConfigurer httpConduitConfigurer = (name, address, httpConduit) -> {
            TLSClientParameters tlsParameters = new TLSClientParameters();
            // Disable strict Hostname check on Certificate
            tlsParameters.setDisableCNCheck(true);
            httpConduit.setTlsClientParameters(tlsParameters);
        };
        final Bus bus = BusFactory.getThreadDefaultBus();
        bus.setExtension(httpConduitConfigurer, HTTPConduitConfigurer.class);
    }
```

**Since my dependency update, this does not work anymore.** 

The onStart method is called and is processed, but when I send SOAP requests to the server, I get a CertificateException as if the CNCheck would not be disabled.

```
java.security.cert.CertificateException: No subject alternative DNS name matching uzkp-ase-v-ap-n01.visana.ch found.
	at java.base/sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:212)
	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:103)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:458)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:418)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:292)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
```

Is this an obvious problem due to the dependency major upgrades? 

I suppose that the httpConduit configuration is done, but the configured conduit is (due to new versions of CXF etc) not used. Do I need to do this configuration different in the current versions? 

Thanks for your help

**Comment by sburkard** [comment]
Surprisingly, I was able to solve the problem by removing the dependency `io.quarkiverse.cxf:quarkus-cxf-rt-transports-http-hc5`. Notice that this dependency was already present before the upgrade and the SOAP communication then worked with it.

The removal leads to these dependencies removed from the project. 
```
+- io.quarkiverse.cxf:quarkus-cxf-rt-transports-http-hc5:jar:2.4.1:compile
  \- org.apache.cxf:cxf-rt-transports-http-hc5:jar:4.0.3:compile
     \- org.apache.httpcomponents.client5:httpclient5:jar:5.2.1:compile
        +- org.apache.httpcomponents.core5:httpcore5:jar:5.2:compile
        \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2:compile
```

Possible causes (just guesses)

- Perhaps quarkus-cxf 1.7.3 did not use httpclient 5 (although the explicitly added dependency), while quarkus-cxf 2.4.1 now really uses it, but my http-conduit configuration is ignored by httpclient 5. 
- quarkus-cxf 2.4.1 or httpclient 5.2 has changed stuff so that my http-conduit configuration is no more used.

**Comment by manubell** [comment]
Your guesses aren't too far off I think.
Upstream in CXF 4.0.2they defaulted to HTTP/2 and I think with that came some changed to the httpclient. In the Jira issue they have some docs linked around async client.
https://issues.apache.org/jira/browse/CXF-8606

In quarkus-cxf that was a change somewhere between versions 2.0.0 and 2.0.4.

**Comment by sburkard** [comment]
Thanks for the hint. I think that explains it. 

Since in older versions http/2 was disabled by default, my client did not use http-client 5 at all, but classic HttpURLConnection (as described on [this wiki-page](https://cwiki.apache.org/confluence/display/CXF20DOC/Asynchronous+Client+HTTP+Transport))

Now that http/2 defaults to true, http-client 5 was picked up and used. But my http-configuration in the question above has no effect in this setup. 

The removal of http-client 5 dependency probably forces CXF back to http 1.x since no http/2 capable lib is available. Therefore, my http-configuration works again. 

The explanation leaves the question how to configure TLSClientParameters for quarkus-cxf when http/2 is enabled.

**Comment by ppalaga** [comment]
Thanks for the report and investigation @sburkard!

hc5 client had no tests in Quarkus CXF 1.x and so it is hard to tell whether it worked at all.
Basic use cases are [covered by tests](https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/hc5) since 2.2.1 but there is no test coverage for SSL. 
Setting the TLSClientParameters on the conduit should IMO work also for HC5 and we should investigate whether it really works.
Since Quarkus CXF 2.5.0 (released yesterday), there is a set of new SSL config options. One of them is [quarkus.cxf.client."clients".hostname-verifier](https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf.html#quarkus-cxf_quarkus.cxf.client.-clients-.hostname-verifier). Value `AllowAllHostnameVerifier` effectivelly calls `setDisableCNCheck(true)`. 

Note that this new built-in config functionality may conflict with the way how you implemented your `HTTPConduitConfigurer`. Unless you want to override everything TLSClientParameters-related from application.properties, you should better re-use the `TLSClientParameters` instance already set on the conduit.

**Comment by ppalaga** [comment]
About HTTP/2: In Quarkus 2.3.1, we have introduced our own default for HTTPConduitFactory: https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf.html#quarkus-cxf_quarkus.cxf.client.-clients-.http-conduit-factory 
Where CXF uses a `java.net.http.HttpClient` based clients by default (which support HTTP/2), Quarkus CXF is still using `java.net.HttpURLConnection` (HTTP 1.1 only). This was motivated mainly by https://github.com/quarkiverse/quarkus-cxf/issues/992

**Comment by ppalaga** [comment]
Please feel free to reopen if needed.
