### ISSUE TITLE
Wrong service file loaded in native mode after upgrading Mandrel from 23.0.1.2 JDK 17.8 to 23.1.0.0 JDK 21.0

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#1078]
Before the upgrade the service loader has loaded the resource `META-INF/services/org.apache.cxf.bus.factory` from the application runner `quarkus-cxf-integration-test-mtom-awt-2.5.0-SNAPSHOT-runner.jar` but now after the Mandrel upgrade, the resource is loaded from a dependency `org.apache.cxf:cxf-core`.

**Comment by ppalaga** [comment]
@zakkak @galderz is there any way to get back to the old behavior (which is BTW consistent with the JVM mode)?

**Comment by zakkak** [comment]
@ppalaga can you please provide a reproducer? It sounds like a GraalVM bug to me, but would need to have a look at it first.

**Comment by ppalaga** [comment]
Here is how to reproduce:

```
git clone git@github.com:quarkiverse/quarkus-cxf.git
cd quarkus-cxf
# the commit that upgrades to Quarkus 3.5.0
# there is a workaround in the main branch right after it, 
# so being at this particular commit is important
git reset --hard fea5378251d6aa98f6dad12dbbf4dc796d303e74
# build the whole source tree
mvn clean install -DskipTests -Dquarkus.build.skip -Denforcer.skip
# run some native test
mvn clean verify -Pnative -Dquarkus.native.container-build
...
[ERROR]   MtomAwtIT>MtomAwtTest.uploadDownloadMtom
```

The root cause is that `org.apache.cxf.BusFactory.getBusFactoryClass(ClassLoader)` sees the default `META-INF/services/org.apache.cxf.bus.factory` from cxf-core rather than the one that we write into the application at build time (implemented [around here](https://github.com/quarkiverse/quarkus-cxf/blob/fea5378251d6aa98f6dad12dbbf4dc796d303e74/extensions/core/deployment/src/main/java/io/quarkiverse/cxf/deployment/QuarkusCxfProcessor.java#L184-L196) )
And so the BusFactory loads the default implementation instead of our custom `io.quarkiverse.cxf.QuarkusBusFactory`

**Comment by zakkak** [comment]
The issue is introduced by https://github.com/oracle/graal/commit/d5000f4146e66faaa4d79cd80c5b3274fcf12e14 I will have a better look probably next week.

@olpaw FYI

**Comment by maxandersen** [comment]
This feels like a native image bug if not possible to have similar semantics as jvm?

**Comment by zakkak** [comment]
Correct

**Comment by zakkak** [comment]
> The issue is introduced by [oracle/graal@d5000f4](https://github.com/oracle/graal/commit/d5000f4146e66faaa4d79cd80c5b3274fcf12e14) I will have a better look probably next week.
> 
> @olpaw FYI

Wrong mention... Sorry Paul. cc @chumer

**Comment by zakkak** [comment]
Upstream Graal fix: https://github.com/oracle/graal/issues/7678

**Comment by zakkak** [comment]
The upstream fix has been merged and should land in GraalVM for JDK 22 and Mandrel 24.0. A backport request is pending to get the fix in GraalVM for JDK 17 and Mandrel 23.1 as well.

**Comment by ppalaga** [comment]
Thanks a lot, @zakkak!

**Comment by ppalaga** [comment]
I am closing this leaving the [workaround](https://github.com/quarkiverse/quarkus-cxf/commit/3156682521b25cb462b5cb0fba6be72e0d20a41a) in place.

**Comment by zakkak** [comment]
> The upstream fix has been merged and should land in GraalVM for JDK 22 and Mandrel 24.0. A backport request is pending to get the fix https://github.com/oracle/graal/pull/7957#issuecomment-1841664895 and https://github.com/graalvm/mandrel/issues/629.

FTR the upstream fix will land in land in GraalVM for JDK 21 and Mandrel 23.1 in the upcoming January CPU releases.
