### ISSUE TITLE
@RolesAllowed() not working

### ISSUE THREAD

**Issue by wh81752** [quarkiverse/quarkus-cxf#109]
I have a HTTP webservice providing REST and SOAP endpoints:

Here's the REST service:
```
@RequestScoped
public class FruitResource {

    @GET
    @Path("/list")
    @RolesAllowed("USER")
    public List<String> list() {
         final SecurityIdentity securityIdentity =CDI.current()
                 .select(SecurityIdentity.class)
                 .get();
        System.out.println(securityIdentity.hasRole("USER"));
        return Arrays.asList( .. );
    }
}
```

Here's the "same" service as SOAP:

```
@WebService(endpointInterface = "org.acme.cxf.FruitWebService")
public class FruitWebServiceImpl implements FruitWebService {

    @Override
    @RolesAllowed("USER")
    public List<String> list() {
        final SecurityIdentity securityIdentity =CDI.current()
                 .select(SecurityIdentity.class)
                 .get();
        System.out.println(securityIdentity.hasRole("USER"));
        return Arrays.asList( .. );
    }
```

This does not work at all.  I'm getting a `javax.enterprise.context.ContextNotActiveException: null` in `io.quarkus.arc.impl.ClientProxies#getDelegate` while all works fine using the REST EP.

My configuration is rather simple:
```
quarkus.http.auth.basic=true
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.x=x
quarkus.security.users.embedded.roles.x=USER     
quarkus.resteasy.path=/rest
quarkus.cxf.path=/soap
quarkus.cxf.endpoint."/fruit".implementor=org.acme.cxf.FruitWebServiceImpl
```

Not sure whether this is a bug. However, I somehow expect that configured (http) security works regardless of the service implementation.

**Comment by dufoli** [comment]
have you added quarkus security to pom ?

**Comment by wh81752** [comment]
Let me compile an example to support my claim...

**Comment by wh81752** [comment]
Compiled a sample project, available here:

https://github.com/wh81752/cxfdemo-quarkus 

Contains a simple helloworld/greeter service provides as CXF Soap and REST. I've added simple security based on basic auth and user-properties for demonstration purposes.

The methods in question is 
```
    // HelloWorld.java
    @WebMethod()
    @XmlElement(required = true)
    @RolesAllowed({ "APPUSER" })
    String securedHiToUser(@XmlElement(required = true) @WebParam(name = "user") User user);
```
 and

```
    // HelloWorldResource.java
    @POST
    @Path("/sechello/{user}")
    @RolesAllowed({ "APPUSER" })
    public String sayHiToUserSecured(@PathParam("user") UserImpl user) { // TODO: use interface User instead
        return String.format("***%s***", hwService.sayHiToUser(user));
    }
```

When you trying those methods (for example via curl), then you will notice that the `HelloWorldResource.sayHiToUserSecured` is properly secured while `HelloWorld.securedHiToUser` isn't.  The latter will allow you to perform the application without authentication.

**Comment by wh81752** [comment]
In addition I created a variation of this issue (--> branch: https://github.com/wh81752/cxfdemo-quarkus/tree/service-rbac). 

Again a HelloWorld REST Resource and SOAP Endpoint. Security / RBAC (Role Based Access) is applied to a shared service implementation --> https://github.com/wh81752/cxfdemo-quarkus/blob/service-rbac/src/main/java/io/app/rest/HelloWorldResource.java

Accessing the service via REST works as expected:
```
curl -u u:p -v http://localhost:8080/rest/hw/hello         ;;; 200
curl            -v http://localhost:8080/rest/hw/hello         ;;; 401
```

Accessing `hello()` via SOAP/CXF produces:
```
Caused by: javax.enterprise.context.ContextNotActiveException
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:40)
        at io.quarkus.security.runtime.SecurityIdentityProxy_ClientProxy.arc$delegate(SecurityIdentityProxy_ClientProxy.zig:42)
        at io.quarkus.security.runtime.SecurityIdentityProxy_ClientProxy.hasRole(SecurityIdentityProxy_ClientProxy.zig:398)
        at io.quarkus.security.runtime.interceptor.check.RolesAllowedCheck.apply(RolesAllowedCheck.java:54)
        at io.quarkus.security.runtime.interceptor.SecurityConstrainer.check(SecurityConstrainer.java:27)
        at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:23)
        at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
        at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(RolesAllowedInterceptor_Bean.zig:386)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.app.service.HelloWorldService_Subclass.hello(HelloWorldService_Subclass.zig:568)
        at io.app.soap.HelloWorldImpl.hello(HelloWorldImpl.java:26)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.jaxws.JAXWSMethodInvoker.performInvocation(JAXWSMethodInvoker.java:66)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
```

**Comment by dufoli** [comment]
hmm. Quarkus team point me to interceptors.
I found that there is a RolesAllowedInterceptor.
which seems to be used in SecurityProcessor
https://github.com/quarkusio/quarkus/blob/452c4af59ff98264798c81b943a1ef4c63e1b51c/extensions/security/deployment/src/main/java/io/quarkus/security/deployment/SecurityProcessor.java

it seems to be started with 
AdditionalSecuredClassesBuildIem (resteasy used that)
AdditionalSecurityCheckBuildItem (spring use that)

So I guess we have to do the same process than :
https://github.com/quarkusio/quarkus/blob/d535e41adbe9a50b9c6473524cc53c5327e07ffb/extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyBuiltinsProcessor.java

**Comment by dufoli** [comment]
other lead to analyse:
https://github.com/quarkusio/quarkus/blob/ef55a323d52af0969c7507289c37ddcf2259da7b/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/SecurityContextFilter.java
https://github.com/quarkusio/quarkus/blob/ef55a323d52af0969c7507289c37ddcf2259da7b/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/QuarkusResteasySecurityContext.java
https://github.com/quarkusio/quarkus/blob/d8967543610fb751a6b0fda68bb45e59456db9d2/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/VertxRequestHandler.java

https://github.com/quarkusio/quarkus/blob/d535e41adbe9a50b9c6473524cc53c5327e07ffb/extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyBuiltinsProcessor.java
https://github.com/quarkusio/quarkus/blob/ef55a323d52af0969c7507289c37ddcf2259da7b/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/AuthenticationRedirectExceptionMapper.java
https://github.com/quarkusio/quarkus/blob/ef55a323d52af0969c7507289c37ddcf2259da7b/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/AuthenticationFailedExceptionMapper.java
https://github.com/quarkusio/quarkus/blob/ef55a323d52af0969c7507289c37ddcf2259da7b/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/UnauthorizedExceptionMapper.java
https://github.com/quarkusio/quarkus/blob/ef55a323d52af0969c7507289c37ddcf2259da7b/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/QuarkusResteasySecurityContext.java

**Comment by wh81752** [comment]
Hmm, feels like the wheel is re-implemented again supporting WS (CXF). I'm not at all into writing Quarkus extensions - nonetheless, is there no way to "re-use"  build steps already present in support RS (Resteasy)? That said, I think you guys to a fantastic job in moving this (long awaited) extension forward,

**Comment by dufoli** [comment]
Hello, I note here the lead to support it. I will copy some part into cxf. But it seems not a simple bug to fix. Hope I will do it when I found time. Else help is welcome ;-)

**Comment by dufoli** [comment]
@shumonsharif  has fixed with this PR. I close the issue. Re open if you have issue.

**Comment by dufoli** [comment]
For this one, we have to test first... I think isUserInRole and getUserPrincipal must been implemented in https://github.com/quarkiverse/quarkus-cxf/blob/master/runtime/src/main/java/io/quarkiverse/cxf/transport/VertxHttpServletRequest.java#L466.

thanks to access to security layer, it can be doable now.

**Comment by wh81752** [comment]
Hi guys, I've tested intensively this morning - works perfect. From a security point of view: works regardless whether my service is implemented as RS or WS. Exactly how I believe things shall behave.
Congrats for fixing this.
