### ISSUE TITLE
Consider changing the default `HTTPConduitFactory` to `HttpClientHTTPConduitFactory`

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#1091]
We can do this in the next major or minor release, once https://github.com/quarkiverse/quarkus-cxf/pull/1090 is merged.

It would be nice to run some perf benchmarks using `URLConnectionHTTPConduitFactory` and `HttpClientHTTPConduitFactory`.

Possible topics to cover:

* Small/large payloads
* http vs. https

**Comment by ppalaga** [comment]
I need to figure out whether https://issues.apache.org/jira/projects/CXF/issues/CXF-8951 has any relevance to us. Although it is about JAX-RS clients, the way how the HTTP clients are managed by the two conduit implementations might be the same for JAX-WS clients.

**Comment by famod** [comment]
Just FWIW, for each QCXF update in my app I'm re-checking https://github.com/quarkiverse/quarkus-cxf/discussions/971#discussioncomment-6794535 and so far nothing has changed.
That's also why we pinned `URLConnectionHTTPConduitFactory` via config to avoid nasty surprises on a QCXF update.
Sadly, I haven't had time to take a stab at a reproducer (with and without Quarkus in the mix).

**Comment by ppalaga** [comment]
> Just FWIW, for each QCXF update in my app I'm re-checking [#971 (reply in thread)](https://github.com/quarkiverse/quarkus-cxf/discussions/971#discussioncomment-6794535) and so far nothing has changed. That's also why we pinned `URLConnectionHTTPConduitFactory` via config to avoid nasty surprises on a QCXF update. Sadly, I haven't had time to take a stab at a reproducer (with and without Quarkus in the mix).

I think it would be worth to track this as a separate issue. At least there is a clear and easy way to reproduce. Would you mind filing a new issue?

**Comment by ppalaga** [comment]
I'd be in favor of setting the new `VertxHttpClientHTTPConduit` as a default once it is mature enough. It supports HTTP/2, will support the async mode and generally the Vert.x behavior is well understood on Quarkus.
