### ISSUE TITLE
XML Schema validation runtime configuration property

### ISSUE THREAD

**Issue by cj19** [quarkiverse/quarkus-cxf#1099]
I am using schema validation in my Quarkus application by marking the web services with relevant annotation (SchemaValidation). There are cases when it needed to be turned off, but it is not possible to turn it off dynamically using application properties config. It would be ideal if it was necessary to turn it off/on, also if it could be done using runtime arguments.

Edit by @ppalaga:

The requested configuration property would have the same behavior like `@org.apache.cxf.annotations.SchemaValidation` annotation or `org.apache.cxf.annotations.EndpointProperty.EndpointProperty(key = "schema-validation-enabled", value = "true")` on a SEI implementation class.

We already have a test for `@org.apache.cxf.annotations.SchemaValidation`: https://github.com/quarkiverse/quarkus-cxf/commit/dd4f3115cbb672960a6730c3e0973664e5d62c71 For testing the new property, it would be enough to add an endpoint configured by that new property and parametrize the tests in https://github.com/quarkiverse/quarkus-cxf/commit/dd4f3115cbb672960a6730c3e0973664e5d62c71#diff-ec4c15055dd2c706bfdfc931429c6e03b5dc4ff8cd3f2a7997b214ce373eac97R11 so that they call both the existing and the new eindpoint expecting the exact same behavior.

Implementation: the new option would go to [CxfEndpointConfig](https://github.com/quarkiverse/quarkus-cxf/blob/d5a48426e2c0764bfed3d7062fe3b72ef839db7b/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/CxfEndpointConfig.java#L10) from where it has to be passed to `jaxWsServerFactoryBean.properties` in  [CxfHandler](https://github.com/quarkiverse/quarkus-cxf/blob/d5a48426e2c0764bfed3d7062fe3b72ef839db7b/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/transport/CxfHandler.java#L132) via `CXFServletInfo` much like it is done with other options defined in `CxfEndpointConfig`. 

This is a good first issue, contributions are welcome!

**Comment by ppalaga** [comment]
I hope you mean this to be only a boot time switch? "Dynamically" might imply that on/off would work also later during the life time of the application. That would be hard to implement and I hope you do not mean that :)

**Comment by cj19** [comment]
> I hope you mean this to be only a boot time switch?
Yes, I do mean that. :)

**Comment by cj19** [comment]
Could you give me a time frame when this feature can be realized? @ppalaga

**Comment by ppalaga** [comment]
I'd say it is up to you as long as you are the only person who made this wish :)
If you would like to get it delivered in the next release, then I plan to release 2.6.0 around Nov. 15th right after [Quarkus 2.6.0 Core](https://github.com/quarkusio/quarkus/wiki/Release-Planning).
