### ISSUE TITLE
How to inject Interceptors programmatically

### ISSUE THREAD

**Issue by mcanzerini** [quarkiverse/quarkus-cxf#1146]
Hi,

I want to add Out Interceptors programmatically by class name. Is there a way to do so? I did not find any clue is the documentation.

Thanks

**Comment by ppalaga** [comment]
Is this not helpful? https://docs.quarkiverse.io/quarkus-cxf/dev/user-guide/cxf-interceptors-and-features.html

**Comment by ppalaga** [comment]
@mcanzerini please feel free to reopen when the above resource does not help.
