### ISSUE TITLE
io/quarkiverse/cxf/CxfConfig throws error when using with Java 8

### ISSUE THREAD

**Issue by Kropik123** [quarkiverse/quarkus-cxf#115]
I am currently not able to use the "quarkus-cxf" extension as parts of it seem to be compiled with a Java-version > 8.
![image](https://user-images.githubusercontent.com/52424464/106112382-79df8580-614d-11eb-9f50-05c8835ca76e.png)

If this extension is known to not support Java 8 anymore then please let me know.

**Comment by dufoli** [comment]
hmm strange...

**Comment by dufoli** [comment]
have you try with mvn clean install ?

**Comment by derari** [comment]
In [this commit](https://github.com/quarkiverse/quarkus-cxf/commit/eb2ffba2889a545ba33ae96259f6c9b9ec43cb38) the target version was bumped to 11. I suspect that causes this issue

**Comment by dufoli** [comment]
Have you try to build with master and change version to 8?
