### ISSUE TITLE
Make algorithm suites configurable through application.properties thus allowing FIPS compliant suites

### ISSUE THREAD

**Issue by JiriOndrusek** [quarkiverse/quarkus-cxf#1173]
To make quarkus-cxf works correctly o FIPS, custom algorithm suite has to be configured.

It would be nice to have an option to configure such suite via properties, where default values are working on FIPS.

Modules integration-tests/ws-trust and integration-tests/ws-security-policy should work on FIPS with this change.

**Comment by ppalaga** [comment]
For the record, we agreed to try to propose the algorithm configuration on CXF level https://issues.apache.org/jira/browse/CXF-8971

**Comment by ppalaga** [comment]
Fixed by 96405020012ec2c95e537dd7392df4e067e1ca95
