### ISSUE TITLE
create merge request to quarkus to move jaxb and jaxp related stuff directly in jaxp jaxb extension

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkus-cxf#12]

**Comment by dufoli** [comment]
a big part was added with https://github.com/quarkusio/quarkus/pull/13408 but it remain what point ppalaga.

**Comment by dufoli** [comment]
another stuff for jaxb here : https://github.com/quarkiverse/quarkus-cxf/blob/main/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/graal/CXFSubstitutions.java#L71-L147

**Comment by ppalaga** [comment]
I think we are fine, thus closing.
