### ISSUE TITLE
cxf interceptors are not being initialized/called in dev mode

### ISSUE THREAD

**Issue by chet20r** [quarkiverse/quarkus-cxf#121]
Hi all, This is more of a question than a bug. I have an issue where the cxf interceptors are not being called/initialised.

I've got a multi module maven project with module A having soap client artifacts generated by cxf maven plugin. And module B is a quarkus app that has module A as dependency and calling a remote soap service.

I've got an interceptor defined in module B and registered in `application.properties` of module B.  However, the interceptor is not being initialised/called during a soap call. I need to be able to add basic auth to the soap request.

Any pointers as to what I could be missing?

**Comment by shumonsharif** [comment]
Does it work fine when both the soap client artifacts and the Quarkus app are in the same module?

**Comment by chet20r** [comment]
I haven't really tried putting both in the same module. But with the maven multi module, the soap call itself works .. its just that I am unable to add basic auth via interceptors as the interceptor is not being initialized/called

**Comment by shumonsharif** [comment]
It would be good to verify that the issue is indeed tied to the packaging and module structure.  Happy to try dig in more if you are able to provide a reproducer, or if you're able to test with a single module.

**Comment by chet20r** [comment]
Hi @shumonsharif,
 I have created a sample repo with the issue replication. There is one interceptor defined `BasicAuthInterceptor.java` that is supposed to be called when soap service is invoked. I've added instructions in the README. Let me know if you need any more info.

https://github.com/chet20r/quarkus-cxf-interceptor-issue

thanks,
chetan

**Comment by chet20r** [comment]
I just figured out there is a way to add a basic auth user and password via the `application.properties` 

```
quarkus.cxf.endpoint."/".username=user
quarkus.cxf.endpoint."/".password=pwd
```
However, I also need to add additional headers like a `User-Agent` into the header where the use of interceptors would make sense?

**Comment by chet20r** [comment]
I think I am pretty close to finding why interceptors are not being invoked. In the `CXFRecorder.java` there is a conditional registration of interceptors like so

```java
if (cxfEndPointConfig.implementor.isPresent()) {
                String implementor = cxfEndPointConfig.implementor.get();
   ----> this one here --->             if (implementor != null && implementor.equals(wsImplementor)) {
                    CXFServletInfo cfg = new CXFServletInfo(path,
                            relativePath,
                            implementor,
                            sei,
                            cxfEndPointConfig.wsdlPath.orElse(null),
                            soapBinding,
                            wrapperClassNames,
                            cxfEndPointConfig.publishedEndpointUrl.orElse(null));
                    if (cxfEndPointConfig.inInterceptors.isPresent()) {
                        cfg.getInInterceptors().addAll(cxfEndPointConfig.inInterceptors.get());
                    }
                 
```
I understand the code is checking for an `implementor` to be defined in the config and it should equal `wsImplementor`.

I only have an client interface generated by cxf and no `wsImplementor` as I just need to call a remote SOAP endpoint. 
Need your help in understanding what goes in `implementor` config property that would get the interceptors registered?

**Comment by dufoli** [comment]
hmmm. I think I ave add interceptor only for server part. I was not aware that client part need it too ...

**Comment by chet20r** [comment]
May be I am doing something wrong. i am not sure... When I define a cxf feature in `application.properties` as `#quarkus.cxf.endpoint."/".features=org.apache.cxf.feature.LoggingFeature 👍🏽` then it seems to be invoking that feature and I can see the soap request and responses logged.

However when I create my own feature by extending the `LoggingFeature` it doesn't seem to work?
`quarkus.cxf.endpoint."/".features=io.github.chet20r.cxf.feature.CustomLoggingFeature // extends LoggingFeature but does not work`

I've created a repo with reproduction (has an interceptor instead). Would you be able to have a look please when you get a chance? 
https://github.com/chet20r/quarkus-cxf-interceptor-issue
thanks,

**Comment by shumonsharif** [comment]
I spent a little bit of time on this, but nothing unusual stood out at me.  Just a note, the patch below works fine, you can see the interceptor getting initialized?  So I'm not yet convinced there is an issue with the extension ...

```patch
Index: integration-tests/pom.xml
<+>UTF-8
===================================================================
diff --git a/integration-tests/pom.xml b/integration-tests/pom.xml
--- a/integration-tests/pom.xml	(revision 8b73bffd740cdd6595140454a2cc7f7b8b5cdb48)
+++ b/integration-tests/pom.xml	(date 1613049988000)
@@ -27,6 +27,11 @@
             <artifactId>quarkus-resteasy</artifactId>
         </dependency>
         <dependency>
+            <groupId>io.github.chet20r</groupId>
+            <artifactId>quarkus-service</artifactId>
+            <version>1.0.0-SNAPSHOT</version>
+        </dependency>
+        <dependency>
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-undertow</artifactId>
         </dependency>
Index: integration-tests/src/main/resources/application.properties
<+>UTF-8
===================================================================
diff --git a/integration-tests/src/main/resources/application.properties b/integration-tests/src/main/resources/application.properties
--- a/integration-tests/src/main/resources/application.properties	(revision 8b73bffd740cdd6595140454a2cc7f7b8b5cdb48)
+++ b/integration-tests/src/main/resources/application.properties	(date 1613050283000)
@@ -2,6 +2,7 @@
 quarkus.cxf.endpoint."/greeting".implementor=io.quarkiverse.it.cxf.GreetingWebServiceImpl
 quarkus.cxf.endpoint."/foo".client-endpoint-url=http://localhost:8081/soap/greeting
 quarkus.cxf.endpoint."/foo".service-interface=io.quarkiverse.it.cxf.GreetingClientWebService
+quarkus.cxf.endpoint."/foo".in-interceptors=io.github.chet20r.cxf.interceptor.BasicAuthInterceptor
 quarkus.cxf.endpoint."/greeting".published-endpoint-url=https://io.quarkus-cxf.com/test
 
 quarkus.cxf.endpoint."mockCalculator".wsdl=http://localhost:9000/mockCalculator?wsdl
```

**Comment by shumonsharif** [comment]
@chet20r Please take a look at the attached, it contains a patch file to your repo, containing a unit test, and the log output for `./mvnw -pl quarkus-service -am test`.  The interceptor loads fine for the unit test.  

I am suspecting there is an issue with your maven project setup in terms of logging in BasicAuthInterceptor.

[junit-interceptor-works.zip](https://github.com/quarkiverse/quarkus-cxf/files/5966674/junit-interceptor-works.zip)

May still be good to get @dufoli 's thoughts on this in case I'm missing anything.

**Comment by chet20r** [comment]
Thanks @shumonsharif for supplying the patch. And surprisingly it does work when I run the test 🤯 ..  However, not when running the application itself. I enabled some debug logs while running the app and the tests and found different behaviour

When running integration test I can see the `BasicAuthInterceptor` being added to the interceptor chain -- see below

```
2021-02-12 09:59:16,320 DEBUG [org.apa.cxf.pha.PhaseInterceptorChain] (main) Chain org.apache.cxf.phase.PhaseInterceptorChain@1ebe756f was created. Current flow:
  receive [PolicyInInterceptor, AttachmentInInterceptor]
  post-stream [StaxInInterceptor]
  read [WSDLGetInterceptor, ReadHeadersInterceptor, SoapActionInInterceptor, StartBodyInterceptor]
  pre-protocol [BasicAuthInterceptor, MustUnderstandInterceptor]
  post-protocol [CheckFaultInterceptor, JAXBAttachmentSchemaValidationHack]
  unmarshal [DocLiteralInInterceptor, SoapHeaderInterceptor]
  post-logical [WrapperClassInInterceptor]
  pre-invoke [SwAInInterceptor, HolderInInterceptor]
```

But when running the app, the BasicAuthInterceptor is not in the chain at all

```
2021-02-12 09:54:53,772 DEBUG [org.apa.cxf.pha.PhaseInterceptorChain] (executor-thread-1) Chain org.apache.cxf.phase.PhaseInterceptorChain@772bb89f was created. Current flow:
  receive [PolicyInInterceptor, AttachmentInInterceptor]
  post-stream [StaxInInterceptor]
  read [WSDLGetInterceptor, ReadHeadersInterceptor, SoapActionInInterceptor, StartBodyInterceptor]
  pre-protocol [MustUnderstandInterceptor]
  post-protocol [CheckFaultInterceptor, JAXBAttachmentSchemaValidationHack]
  unmarshal [DocLiteralInInterceptor, SoapHeaderInterceptor]
  post-logical [WrapperClassInInterceptor]
  pre-invoke [SwAInInterceptor, HolderInInterceptor]
```

I am attaching the logs for both the test run and the application run below

[cxf.log](https://github.com/quarkiverse/quarkus-cxf/files/5968938/cxf.log)

[cxf_test.log](https://github.com/quarkiverse/quarkus-cxf/files/5968937/cxf_test.log)

I am completely stumped about what is happening when the actual application runs 🤷🏽

**Comment by chet20r** [comment]
Hey @shumonsharif and @dufoli , Just a quick update for you. When I run the application in dev mode (`quarkus:dev`) then the interceptors don't seem to get executed. However, when I package the application and run the jar in production mode then I can see the Interceptor being registered and called during soap invocation 😺 .

**Comment by dufoli** [comment]
2 potential causes: 
cls = Class.forName(className).asSubclass(clazz);
failed because class is not in classLoader...
Else
item = CDI.current().select(cls).get();
failed to load bean.

I have checked code and I have to lead to fix that:
1) all feature, interceptor and databinding class must be convert to bean with singleton:  (with AdditionalBeanBuildItem)
2) work to add class to classLoader or change ClassLoader used.

@chet20r  can you add annotation ApplicationScoped to your custom interceptor to check if it come from interceptor is not a bean ?

**Comment by dufoli** [comment]
good catch @shumonsharif I arrive to pretty same conclusion. 
Do you think we have to add interceptors, features as beans ?

**Comment by dufoli** [comment]
@chet20r can you check if fix of shumon fix the issue ?

**Comment by shumonsharif** [comment]
Thanks @dufoli - I agree with you, we should probably add interceptors and features as singleton beans.  Having said that, here are the results I had for the CDI lookup and the custom interceptor annotations:

- No annotations: No bean found for CDI lookup (interceptor initialized via empty constructor)
- `@ApplicationScoped`: No bean found for CDI lookup (interceptor initialized via empty constructor)
- `@ApplicationScoped` and `@Unremovable`:  CDI lookup fails with `java.lang.VerifyError: class io.github.chet20r.cxf.interceptor.BasicAuthInterceptor_ClientProxy overrides final method org.apache.cxf.phase.AbstractPhaseInterceptor.getId()Ljava/lang/String;`
- `@Singleton` and `@Unremovable`: CDI lookup is happy, no need for constructor initialization

I think we can create a new issue to address singleton beans, and close this one, once @chet20r can confirm the fix!

**Comment by shumonsharif** [comment]
BTW @dufoli , been thinking about it a little deeper for the past 15 mins, and I'm now not sure I see any major benefit to using singleton beans for the interceptors and features.  The empty constructor initialization seems just as good.  Am I missing something obvious?

**Comment by dufoli** [comment]
1) beans not used is clean by quarkus. => reduce memory but we will keep them configured at runtime so it will not been removed... => no memory gain.
2) so only remaining advantage of beans is that I can defined producer if interceptor need parameters. Most of interceptor do not need params but for security interceptor we can add a producer which initialize interceptor if config is fullfilled and add new config element for this config. wdyt? let s continue on other tickets.

**Comment by chet20r** [comment]
Heya, I can confirm @shumonsharif fix is working 🎉 👏🏽.  Thanks to both. Amazing collaboration and a quick fix 👍🏽 . Will be good to know when this is planned to be released to mvn repo.
