### ISSUE TITLE
officially quarkus version supported by redhat

### ISSUE THREAD

**Issue by vnicoletti** [quarkiverse/quarkus-cxf#122]
you could make quarkus-cxf compatible with quarkus version 1.7.6, as reported here https://access.redhat.com/articles/4966181#RHBQ_1_7_x is the version officially supported by redhat, thank you.

**Comment by dufoli** [comment]
hmm, 1.7 is dated of august 2020.
So I know that I can try to switch back to this version but graalvm 21 have fix a bugs that make cxf not worked to rollback to old version is difficult. => not planned currently.
