### ISSUE TITLE
Remove the doc link from the logging extension metadata

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-cxf#1241]
The io.quarkiverse.cxf:quarkus-cxf-rt-features-logging extension references https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf-rt-features-logging.html in its extension metadata. That docs page doesn't seem to exist anymore.

**Comment by holly-cummins** [comment]
> Is there anything else I can do?

The dummy `io.quarkiverse.cxf:quarkus-cxf-rt-features-logging` extension should either be marked deprecated, or have the link to the documentation removed in its extension metadata. We're less strict for deprecated extensions, and don't expect the links on those pages to be valid. 

https://github.com/quarkiverse/quarkus-cxf/blob/ec77f4cec29dddf76bff615bc53b37a7f30cd042/extensions/features-logging/runtime/src/main/resources/META-INF/quarkus-extension.yaml shows the status as 'stable'. (Camel pioneered adding 'deprecated' to the actual status, so I've updated things to use it.)

It also looks like even if the extension metadata had a deprecated status, it wouldn't have made it into a release yet. As well as the changes above, ideally we wouldn't remove docs pages until the latest release no longer refers to them, but I know keeping docs and code in sync is tricky when there's two distinct release cycles involved.

**Comment by ppalaga** [comment]
> Camel pioneered adding 'deprecated' 
Would it be separated by space from the actual status, like `status: stable deprecated` ?

**Comment by holly-cummins** [comment]
It's usually done as an array, for example (taken from https://github.com/apache/camel-quarkus/blob/main/extensions/joor/runtime/src/main/resources/META-INF/quarkus-extension.yaml)

```
  status:
  - "stable"
  - "deprecated"
  ```
  
  The Camel extensions may also do something extra with the deprecated status, because I can see it gets carried across into a [generated metadata file](https://github.com/apache/camel-quarkus/blob/55759dbcd7bc4cc907d8fa4894b296a95530cd5f/docs/modules/ROOT/examples/languages/joor.yml#L7], but I don't know what it gets used for after that!

**Comment by ppalaga** [comment]
`docs/modules/ROOT/examples/languages/joor.yml` is IIRC a data file for generating some antora pages.

OK, let me set the deprecated status and remove the guide link.

**Comment by ppalaga** [comment]
I plan to release 3.8.1 within a couple of days, once CXF 4.0.4 is out.
