### ISSUE TITLE
Dynamic Schema-Validation breaks kafka error strategy / retry mechanism

### ISSUE THREAD

**Issue by cj19** [quarkiverse/quarkus-cxf#1250]
I am using quarkus framework and I have the schema validation turned on with the following setting:

``quarkus.cxf.client."client".schema-validation.enabled-for=out``

The kafka setting looks like this:

``mp.messaging.incoming.channel.failure-strategy=ignore``

I am trying to break the consuming retry mechanism with the following annotation setting:
``@Retry(delay = 200, maxRetries = -1, maxDuration = 0, abortOn = { AbortRetryException.class, MarshalException.class })``

If the schema validation fails then AbortRetryException being thrown, but after I turned on the schema validation this does not work anymore. Is there any special configuration that I need to use to make this work?

**Comment by ppalaga** [comment]
> If the schema validation fails then AbortRetryException being thrown, but after I turned on the schema validation this does not work anymore.

Sorry, I am not sure I follow what you do and what happens. A reproducer would explain everything in the most effective way.
