### ISSUE TITLE
Is there a way to configure the locale language of the SOAPFaults?

### ISSUE THREAD

**Issue by cj19** [quarkiverse/quarkus-cxf#1263]
It seems that the language setting of the messages depends on the settings of the OS. I already configured the : 
``quarkus.default-locale=en_US``
but that does not change the language of the soap fault messages. Is there any way to change this to be not dependent on the locale settings of the OS?

**Comment by ppalaga** [comment]
Interesting question. Where would the alt-locale messages come from? CXF delivers only messages in English. Does perhaps your service have bundles for other locales? 

For the mechanism to pick some non-default locale, CXF seems to always take `Locale.getDefault()`, so you would have to pass `-Duser.language=hu` when starting your app in JVM mode and set `quarkus.default-locale=hu` at build time for native mode. That would only hold for CXF's own messages and you would have to provide the bundles for your locale yourself.

If you ask about the language of the messages thrown by your own service, then I think you are on your own. Neither JAX-WS nor CXF prescribe you anything. You can pick whatever message loading mechanism you want and you can make it sensitive to whatever system property or SOAP/HTTP message header you like.

Disclaimer: I never solved this in practice, so I can be wrong.

**Comment by cj19** [comment]
Thank you @ppalaga for the quick answer, I will look into this, then I get back to you when I have new updates. :)

**Comment by cj19** [comment]
@ppalaga This problem popped up when my coworker ran the test on his computer and the assertion of the error messages appeared in different language, because his OS configured with different languages. Sidenote: We have already configured the quarkus locale settings, tried with jvm arguments etc. 

I am not sure what else we can be done to change the locale for the CXF. :)

**Comment by ppalaga** [comment]
I could perhaps help more if I knew which messages you speak about. Could you cite one? Which jar or Java class produces it?

**Comment by cj19** [comment]
```
Caused by: jakarta.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-complex-type.2.4.a: Invalid content was found starting with element 'invalidElement'. One of '{expectedElement}' is expected.]
```

**Comment by ppalaga** [comment]
That's one half of the requested info. The other half would be where that exception gets instantiated. It can be seen from the stack trace.

**Comment by ppalaga** [comment]
Closing because of missing information. Please feel free to reopen providing it.
