### ISSUE TITLE
Allow to dynamically specify whole client url

### ISSUE THREAD

**Issue by jakubpietrzak96** [quarkiverse/quarkus-cxf#131]
This is an issue to discuss potential improvement for client url handling (I have created earlier PR for that #128).

Service described with the following configuration:
```
quarkus.cxf.endpoint."/foo".client-endpoint-url=http://localhost:8081/soap/greeting
quarkus.cxf.endpoint."/foo".service-interface=io.quarkiverse.it.cxf.GreetingClientWebService
```

is exposed under
```
http://localhost:8081/soap/greeting/foo
```

Let's say that for different environments we are not able to ensure or predict that the client url ends with `/foo`.
Currently I see no way to override `/foo` part at all with some simple property or environment variable.

Preferably it would be an ability to specify the whole url as a parameter.

We can of course have a workaround where the client service calls go through some kind of proxy that allows us for the url to stay consistent.

Since my proposal with additional boolean property seems not to be an ideal solution, let's discuss if this can be implemented differently.

Suggestion from the PR was to try to achieve this with https://smallrye.io/docs/smallrye-config/interceptors/interceptors.html#relocate-interceptor - I can try to play with this interceptor if we do not see any other way.

**Comment by shumonsharif** [comment]
I looked into this briefly today.  Integrating the SmallRye RelocateInterceptor was fairly trivial, but I was unable to get the extension to actually use the newly mapped properties.  

Having said that, I wanted to propose a slightly different approach to address this issue.  We can allow for property expansion for the relativePath in CXFRecorder.  So having a method such as:

```java
    private String expandPlaceholders(String value) {
        Expression expression = Expression.compile(value, LENIENT_SYNTAX, NO_TRIM);
        return expression.evaluateWithPropertiesAndEnvironment(false);
    }
```

and wrap our call for relativePath:

```java
    String relativePath = expandPlaceholders(webServicesByPath.getKey());
```

This will basically allow us to, if needed, define properties such as:

```properties
quarkus.cxf.endpoint."${web-service-path}".client-endpoint-url=http://localhost:8081/soap/greeting
quarkus.cxf.endpoint."${web-service-path}".service-interface=io.quarkiverse.it.cxf.GreetingClientWebService
```

As long as a corresponding environment variable or system property named `web-service-path` is available, it'll get swapped out.  @dufoli @bnazare @jakubpietrzak96 What do you think of this approach, please share you thoughts!

**Comment by shumonsharif** [comment]
I don't think the solution proposed above is optimal, because we'd be introducing a dependency on SmallRye.  I guess writing our own expandPlaceholders method (something like [this](https://stackoverflow.com/a/9725352)?) may possibly be a viable option - however, I am still left wondering whether this is a common enough use case for us to have to address as part of the extension?

@jakubpietrzak96 Along the lines of environment variable and property placeholder expansions, have you already considered something like the maven-resources-plugin?  

https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html

The difference is that you would be handling the substitution as part of the build process rather than dynamically at runtime.  I think that may be your best bet for now, while we wait for some community feedback.

**Comment by jakubpietrzak96** [comment]
@shumonsharif Some kind of trick with the placeholders would already be sufficient for me. It would then require to adjust two properties / environment variables each time something changes. It's not as good as 1 property, but I think that would work.

Filtering during build does not really help as this parameter needs to be provided in runtime (helm values in this case).

Now that I think of it, most likely the only trouble that I see with the current approach is that we do not know the path suffix in advance (during implementation). However we can adjust that once we have the necessary information and the path suffix will be the same across environments (we use a kind of forward proxy to communicate).

So all in all, I would say that not having such feature is an inconvenience, but we can live with that. We are only integrating with one legacy system talking soap, so just 1 use case if probably not sufficient to call it common.

If we could get some feedback to find a solution either with this extension or by using some kind of workaround (in runtime, not build time) that would be great, but if you guys say it's not possible then it's not the end of the world.

**Comment by shumonsharif** [comment]
@jakubpietrzak96 To clarify - with the proposed solution, the only thing that'll need updating will be the environment variable you pass in.  You will not be updating the property file, that will remain static as it'll contain the substitution placeholders.

**Comment by dufoli** [comment]
btw you can override configuration with env var or env file...
cf https://quarkus.io/guides/config

**Comment by jakubpietrzak96** [comment]
Thanks, I'm aware of that (and how microprofile config works). That doesn't help currently, though - only for the base path to the client service.

**Comment by shumonsharif** [comment]
@jakubpietrzak96 Given the unique circumstance you are in, I believe we can skip having to address this issue as part of the extension.  However, I do have yet another suggestion for you, that may address your needs quite directly and give you plenty of flexibility with implementation.  You can introduce a class such as the below, it's pretty self explanatory, but let us know if you have any questions!

```java
import io.quarkus.arc.Unremovable;
import io.quarkus.vertx.web.RouteFilter;
import io.vertx.ext.web.RoutingContext;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
@Unremovable
public class RouteRedirector {

    // Which path to reroute, can be env property
    @ConfigProperty(name = "redirector.dynamic.path")
    String dynamicPath;

    // Where to route the request to, eg: /soap/foo
    @ConfigProperty(name = "redirector.static.path")
    String staticPath;

    @RouteFilter(400)
    void pathBasedRerouter(RoutingContext rc) {
        String uri = rc.request().uri();
        if (uri.endsWith(dynamicPath)) {
            rc.reroute(staticPath);
            return;
        }
        rc.next();
    }

}
```

@dufoli I think we can close this request as well as the corresponding PR, if you're ok with that.

**Comment by jakubpietrzak96** [comment]
Hi @shumonsharif thanks for the reply.
I still can't understand how I'm the only one with this problem, I think not having ability to specify this without rebuilding seems inconvenient or even a showstopper for supporting multiple environments/configurations. But well, I think the route filter will be good enough for my use case.

**Comment by shumonsharif** [comment]
Thanks @jakubpietrzak96 Ultimately I think it boils down to "/foo" below being unpredictable across environments, which is likely a valid use case, especially if you're promoting tagged container images across environments.  However, what we're not sure on is the community demand/need for the same service being consumed being hosted at different paths across different environments - ideally that should not be the case to begin with.

```properties
quarkus.cxf.endpoint."/foo".client-endpoint-url=http://localhost:8081/soap/greeting
quarkus.cxf.endpoint."/foo".service-interface=io.quarkiverse.it.cxf.GreetingClientWebService
```

We will absolutely reopen this issue (and hopefully come up with a better solution) if there is some demand for this ... and we'll definitely keep your note in mind if the issue comes up again.  Thank you.
