### ISSUE TITLE
Unnecessary logger warnings

### ISSUE THREAD

**Issue by jakubpietrzak96** [quarkiverse/quarkus-cxf#133]
Hi,

there are few places in current code that have `WARN` level logs which in fact are not really warnings.
I would treat them more as one of `INFO`, `DEBUG` or `TRACE` depending on context.

Example:
https://github.com/quarkiverse/quarkus-cxf/blob/master/runtime/src/main/java/io/quarkiverse/cxf/CXFRecorder.java#L21
```
LOGGER.warn("recorder CXFClientInfoSupplier");
```

I can send a PR for that if you'd like.

**Comment by shumonsharif** [comment]
Please feel free to submit a PR.

**Comment by dufoli** [comment]
yeah I do so when I start the project and forget to clean it ...
