### ISSUE TITLE
wsdl2Java code generation fails due to a missing SPI implementation

### ISSUE THREAD

**Issue by camproto** [quarkiverse/quarkus-cxf#1332]
I opened a quarkus issue https://github.com/quarkusio/quarkus/issues/39689 that in v3.6.9 my SecretsKeyHandler ist did not compile after an upgrade from 3.2.4. 

[radcortez](https://github.com/radcortez) mentioned your fix in #1007 may cause the problem with my custom SecretsKeyhandler in compile phase in v3.6.9. 

Would appreciate a confirmation on that. 

I expect a possible fix of it (if at all) in the latest Java 17 version. In my project I'm still on Java 11, and therefore need to migrate to Java 17 before. Or do you still maintain a fix on a Java 11 version?

**Comment by ppalaga** [comment]
Thanks for the report and the [reproducer](https://github.com/quarkusio/quarkus/files/14755578/getting-started.zip) @camproto. I commented on the original issue: https://github.com/quarkusio/quarkus/issues/39689#issuecomment-2040187324

**Comment by ppalaga** [comment]
Would a backport to Quarkus CXF 2.2 (Quarkus Platform 3.2) be of any value for you? That's the last java 11 compatible LTS stream.
