### ISSUE TITLE
Could not load keystore in @QuarkusTest

### ISSUE THREAD

**Issue by argenstijn** [quarkiverse/quarkus-cxf#1345]
Quarkus : 3.9.3
Quarkus-CXF: latest
Java 21
Windows 10
Maven 3.9.6

I have a simple test where i want to invoke a SOAP service (which is a wiremock server). I need a client which can perform MTLS. But when i add this configuration:

       quarkus.cxf.client.solera.key-store=cert/client/keystore.p12
    
But i get the following error:

Could not load cert/client/keystore.p12 from class path or filesystem

I tried absolute file path etc. But no matter, i constantly get the same error.

**Comment by argenstijn** [comment]
Seems to work in version 3.8.2. In version 3.8.3 it breaks!

**Comment by ppalaga** [comment]
Thanks for the report @argenstijn. Hard to say without a reproducer. You may want to have a look at our [mTLS test](https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/mtls) and gradually change it to your use case. That may reveal what is the problem. Otherwise a small reproducer project would be nice

**Comment by argenstijn** [comment]
Why is this needed in your test? 

 private void extract(final Path keystorePath) throws IOException {
        Assertions.assertThat(keystorePath.getName(0).toString()).isEqualTo("target");
        if (!Files.isRegularFile(keystorePath)) {
            /*
             * This test can be run from the test jar on Quarkus Platform
             * In that case target/classes does not exist an we have to copy
             * what's needed manually
             */
            Files.createDirectories(keystorePath.getParent());
            try (InputStream in = MutualTlsTest.class.getClassLoader()
                    .getResourceAsStream(keystorePath.getFileName().toString())) {
                Files.copy(in, keystorePath, StandardCopyOption.REPLACE_EXISTING);
            }
        }
    }

**Comment by ppalaga** [comment]
Nice to hear that & thanks reporting back @argenstijn
