### ISSUE TITLE
HTTP 302 redirects when `quarkus.http.root-path` is set

### ISSUE THREAD

**Issue by chet20r** [quarkiverse/quarkus-cxf#135]
### Background
I have a Quarkus project setup that uses this dependency to call a SOAP service. 

### Problem Description
When hitting an endpoint in production mode, I observed that there is a HTTP 302 redirect that is happening before the endpoint is executed. This happens when the `quarkus.http.root-path` is set to a value in `application.properties`.

After a lot of testing, I have narrowed down the issue to this dependency and hence opening an issue here.  When I remove the `quarkus-cxf` dependency from the project, then I don't observe that behaviour.

### Steps to replicate

I have a repo to replicate this issue.

1. Clone https://github.com/chet20r/quarkus-cxf-interceptor-issue
2. from the parent maven project, run `mvn clean package -pl sample-rest -am`
3. `cd sample-rest`
4. run `java -jar target/sample-rest-1.0.0-SNAPSHOT-runner.jar`
5. from postman hit the endpoint `http://localhost:8080/hello`
6. In the postman HTTP logs, you can see that there is a HTTP 302 redirect

<img width="456" alt="Screen Shot 2021-02-17 at 4 10 45 pm" src="https://user-images.githubusercontent.com/7542319/108159237-b3972100-713a-11eb-9f28-2b50387fffbf.png">

Also to point out that this behaviour is not replicable in `quarkus:dev` but only when running as production JAR mode 

This could possibly be linked to #124 but not sure

**Comment by dufoli** [comment]
have you test the workaround
```
quarkus.resteasy.path=/rest         # REST via /rest/**
quarkus.cxf.path=/soap                # CXF    via /soap/**
```

**Comment by chet20r** [comment]
Yes.. I can confirm the workaround ☝🏽 works fine. I will close this as it looks to be the same as #124
