### ISSUE TITLE
Schema validation is not working properly

### ISSUE THREAD

**Issue by Inithron** [quarkiverse/quarkus-cxf#1368]
I am using Quarkus CXF 3.10.0

1. The schema validation is only working, if it is enabled AND the WSDL location is set in the application.properties file: `quarkus.cxf.endpoint."/endpoint-path".wsdl=my.wsdl` Which is not mentioned in the specification.
2. The schema validation is only working, if the WSDL location is set in the application.properties file. If the WSDL location is set via annotation `@WebService(wsdlLocation = "my.wsdl")` the schema validation is not working.

**Comment by ppalaga** [comment]
Thanks for the report, @Inithron, this sounds similar to https://github.com/quarkiverse/quarkus-cxf/issues/557 

> Which is not mentioned in the specification.

You mean the JAX-WS spec? Do you happen to have the relevant reference at hand?

**Comment by Inithron** [comment]
Yes, it sounds similar, but #557 has the focus not on the schema validation. But if it also solved the problem with the schema validation, you can close this issue.

With the specification I mean the following two configuration properties:

1. [quarkus.cxf.endpoint."/endpoint-path".schema-validation.enabled-for](https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf.html#quarkus-cxf_quarkus-cxf-endpoint-endpoint-path-schema-validation-enabled-for)
2. [quarkus.cxf.client."client-name".schema-validation.enabled-for](https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf.html#quarkus-cxf_quarkus-cxf-client-client-name-schema-validation-enabled-for)

They mention only how to enable the schema validation, but if the WSDL location is not set, it will not work. And this is from my point of view missing in the specification.

**Comment by Inithron** [comment]
To be more precise I have only testest the schema validation on the endpoint and I am only assuming it will be the same behavior for the client.

**Comment by ppalaga** [comment]
Thanks for the clarification.
