### ISSUE TITLE
Questions: Multiple Clients with same interface but different endpoints?

### ISSUE THREAD

**Issue by antonwiens** [quarkiverse/quarkus-cxf#137]
Is it possible to create multiple clients of the same interface with different endpoint urls and maybe different interceptors?

If yes, how do i inject the different clients?

Thanks a lot!

**Comment by dufoli** [comment]
just use different sei
```
quarkus.cxf.endpoint."/foo".client-endpoint-url=http://localhost:8081/soap/greeting
quarkus.cxf.endpoint."/foo".service-interface=io.quarkiverse.it.cxf.GreetingClientWebService

quarkus.cxf.endpoint."/bar".client-endpoint-url=http://localhost:8081/soap/greeting2
quarkus.cxf.endpoint."/bar".service-interface=io.quarkiverse.it.cxf.GreetingClientWebService2
```

then use named annotation to identify it

```
@Inject
@Named("/foo")
    GreetingClientWebService clientService;

@Inject
@Named("/bar")
    GreetingClientWebService2 clientService2;
```

**Comment by antonwiens** [comment]
Thanks for your information that helps me a lot. 

A question related to our diskussion in 
https://github.com/quarkiverse/quarkus-cxf/issues/113#issuecomment-780595005

Can i configure the same interceptor class with different settings for different clients with the producer?

**Comment by dufoli** [comment]
You can use a singleton bean interceptor.

**Comment by antonwiens** [comment]
I dont see how this removes the need to create a new SEI for each endpoint i want to add an client for.

For me it seems more like it is not supported to create multiple clients for the same SEI and also it is not supported to create different configurations for the same interceptors for different clients.

**Comment by dufoli** [comment]
multiple client for same sei just inject in each bean the client so you will have one for each bean...
I do not understand your goal and issue.
And yes different config of interceptor for each client it is not possible currently.
proposed solution:
use named annotation on interceptor producer and check CDI with named before default.

**Comment by antonwiens** [comment]
I didn't see anything in the documentation related to that, thats why i am asking.
Thanks for your time and explanation.
