### ISSUE TITLE
Native build fails with exception 

### ISSUE THREAD

**Issue by chet20r** [quarkiverse/quarkus-cxf#139]
Hi,

I am trying to do a native build of a quarkus project using `quarkus-cxf` to call a remote soap client. When I execute the below,

`./mvnw clean package -Pnative -Dquarkus.native.container-build=true -pl sample-rest -am -Dquarkus.native.native-image-xmx=10g -X`

then the following exception is thrown.

Anything I could be missing here? This is the repo I'm trying to build the native image for  https://github.com/chet20r/quarkus-cxf-interceptor-issue

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
Call path from entry point to org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader$TypeHelperClassLoader, String, byte[], int, int): 
```

I am using Java 11

**Comment by dufoli** [comment]
can you try with 
mvn clean package -Dnative  -pl sample-rest  -Dquarkus.native.container-build=true

I know that I use -Dnative instead of -Pnative, I never take the time to create profile and so on...

**Comment by chet20r** [comment]
Thanks @dufoli . I tried with `-Dnative` but still the same

```
[sample-rest-1.0.0-SNAPSHOT-runner:26]        setup:   3,170.17 ms,  0.94 GB
21:44:30,286 INFO  [org.hib.val.int.uti.Version] HV000001: Hibernate Validator 6.2.0.Final
21:45:05,866 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
[sample-rest-1.0.0-SNAPSHOT-runner:26]     (clinit):   1,550.06 ms,  2.88 GB
[sample-rest-1.0.0-SNAPSHOT-runner:26]   (typeflow):  38,217.21 ms,  2.88 GB
[sample-rest-1.0.0-SNAPSHOT-runner:26]    (objects):  55,587.84 ms,  2.88 GB
[sample-rest-1.0.0-SNAPSHOT-runner:26]   (features):   2,513.40 ms,  2.88 GB
[sample-rest-1.0.0-SNAPSHOT-runner:26]     analysis: 101,979.56 ms,  2.88 GB
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
Call path from entry point to org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader$TypeHelperClassLoader, String, byte[], int, int):
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.lambda$defineClass$0(ClassGeneratorClassLoader.java:148)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader$$Lambda$915/0x00000007c1dc1440.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:338)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
Call path from entry point to org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader$TypeHelperClassLoader, String, byte[], int, int):
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.lambda$defineClass$0(ClassGeneratorClassLoader.java:148)
	at org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader$$Lambda$915/0x00000007c1dc1440.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:338)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
```

**Comment by chet20r** [comment]
I don't necessarily need to create a native image. The problem I am facing is that I have a simple quarkus service that calls a remote SOAP web service. This service is deployed as an AWS lambda function. The problem is the time it takes to initialise the SOAP service on first request. 

What I am seeing is that to initialise the soap client service, it is taking about 4 seconds which is really slow considering the end user is waiting for a response. This happens only on the first request and the subsequent requests are in millisecond response

<img width="1297" alt="Screen Shot 2021-02-19 at 10 44 06 am" src="https://user-images.githubusercontent.com/7542319/108436523-ac3d5800-729f-11eb-9991-d01d90d73e28.png">

If I can somehow improve the service initialisation time for first request, then I'll be happy with just running in JVM mode. I am not too sure how much of a benefit I would get building a native executable.

**Comment by dufoli** [comment]
Hmm I need cxf version and quarkus-cxf version. Because it seems to be not compatible version...

**Comment by chet20r** [comment]
Here are the versions..
```
CXF - 3.4.2
quarkus-cxf 0.4
```

**Comment by dufoli** [comment]
To monitor time https://quarkus.io/guides/writing-extensions#printing-step-execution-time
Just add -Dquarkus.debug.print-startup-times=true

**Comment by dufoli** [comment]
I know that cxf done a lot of things at first call
... As generated class. On our side it must be done during build time. Anyways, I need to investigate deeper and no time for that.

**Comment by shumonsharif** [comment]
@chet20r I just took a quick look at your project, try adding the following to the native profile in `sample-rest/pom.xml`.  The native image that got built for me works without issue, but let us know how it goes for you.

```xml
        <plugin>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
            <executions>
                <execution>
                    <goals>
                        <goal>native-image</goal>
                    </goals>
                    <configuration>
                        <enableHttpUrlHandler>true</enableHttpUrlHandler>
                        <additionalBuildArgs>--report-unsupported-elements-at-runtime</additionalBuildArgs>
                    </configuration>
                </execution>
            </executions>
        </plugin>
```

**Comment by dufoli** [comment]
thanks to @shumonsharif  test, I close this ticket.

**Comment by chet20r** [comment]
Thanks @dufoli and @shumonsharif . I'll try out the suggested native build approach soon.

**Comment by chet20r** [comment]
Hi @shumonsharif  Just need a little bit of help here. I have updated the POM (in sample-rest project) with the plugin settings you shared above ☝🏽  and when I run `mvn clean package -Pnative -pl sample-rest -am -Dquarkus.native.container-build=true` from the parent project, I am still getting
```
[sample-rest-1.0.0-SNAPSHOT-runner:26]     analysis: 128,565.19 ms,  2.87 GB
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader.java:108)
Call path from entry point to org.apache.cxf.common.spi.ClassGeneratorClassLoader$TypeHelperClassLoader.access$001(ClassGeneratorClassLoader$TypeHelperClassLoader, String, byte[], int, int):
```	
I am not sure what I am doing wrong here?

**Comment by dufoli** [comment]
your error seems not relative to cxf. I have search for 
JNIJavaCallWrappers.jniInvoke_ARRAY on internet because it seems to be a jni problem...

**Comment by shumonsharif** [comment]
Hey @chet20r I can certainly try to help, but given the error is not related to the extension, can you give me access to your repo, and open an issue there with your latest code commits and logs?

**Comment by dufoli** [comment]
maybe I will need to add a profile ...

**Comment by shumonsharif** [comment]
@dufoli We already have a [profile](https://github.com/quarkiverse/quarkus-cxf/blob/master/integration-tests/pom.xml#L107) in our integration-tests, which is probably what @chet20r may have used as a starting point.  

This is what those few lines _should_ look like, in order for folks to use `-Pnative`.  I think we'll need to update our build workflows too, if we touch that.  I can work on that if you'd like, pls feel free to create an issue and assign to me.

```xml
            <id>native</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
```

**Comment by chet20r** [comment]
thanks @shumonsharif & @dufoli. I have given you both access to my repo and have created an issue here. 
https://github.com/chet20r/quarkus-cxf-interceptor-issue/issues/1

I have also attached the logs and the environment details I am running this on.
Thanks for your help!
