### ISSUE TITLE
@WebService Of Implementation Class Ignored

### ISSUE THREAD

**Issue by wh81752** [quarkiverse/quarkus-cxf#140]
I'm trying to change the name of port and service via `@WebService` annotation on service implementation class, like:
```
@WebService(portName = "Foobar")          // annotation appears to be ignored
public class HelloWorldImpl implements HelloWorld { .. }

@WebService(serviceName = "HelloWorld")
public interface HelloWorld { .. }
```

The generated WSDL is expected to be like
```
 <wsdl:service name="HelloWorld">
    <wsdl:port binding="tns:HelloWorldSoapBinding" name="Foobar">
      ..
    </wsdl:port>
  </wsdl:service>
```

but I sticks with port name `HelloWorldPort`.

CXF mandates on https://cxf.apache.org/docs/developing-a-service.html that `@WebService` is to be placed on both, SEI  and  Implemenation class:

> In order to create a service from Java code you are only required to add one annotation to your code. You must add the `@WebService()` annotation on both the SEI and the implementation class

I noticed however that removing `@WebService` from Implemenation class has no impact when developing with current quarkus-cxf.

**Comment by wh81752** [comment]
https://github.com/wh81752/cxfdemo-quarkus/tree/quarkus-cxf-issue-140

A small project supporting my claim. It uses version 0.0.5-SNAPSHOT of quarkus-cxf. Build it as usual with `mvn clean quarkus:dev`, then checkout http://localhost:8080/soap/hw?wsdl for any WSDL changes when playing around with `@WebService`.

**Comment by dufoli** [comment]
this point seems to be related to cxf internaly. I think best is to open a ticket on cxf jira.

**Comment by dufoli** [comment]
Some attribute on annotation are not available on implementor. Check which one is for sei or implementor here https://cxf.apache.org/docs/developing-a-service.html
I do not set any name in my code 
https://github.com/quarkiverse/quarkus-cxf/blob/master/runtime/src/main/java/io/quarkiverse/cxf/transport/CxfHandler.java

**Comment by dufoli** [comment]
Indeed, it was ever analyzed on a previous ticket.
https://github.com/quarkiverse/quarkus-cxf/issues/85#issuecomment-764872425
Ler s close. No solution on extension.
