### ISSUE TITLE
Enhancement: Scanning @WebService

### ISSUE THREAD

**Issue by wh81752** [quarkiverse/quarkus-cxf#141]
The docu of quarkus-cxf mandates to bring a webservice into play by

```
== FruitWebServiceImpl.java ==
@WebService(..)
public class FruitWebServiceImpl implements FruitWebService { ..}

== application.properties ==
quarkus.cxf.endpoint."/fruit".implementor=org.acme.cxf.FruitWebServiceImpl
```

While this works fine, wouldn't it be easier to get going by quarkus-cxf scanning for `@WebService` annotated classes and auto-generate properties, i.e.

```
@WebService()
public class FruitWebServiceImpl implements FruitWebService { ..}    
==>    
quarkus.cfx.endpoint."org.acme.cxf.FruitWebServiceImpl".servicepath=/FruitWebService   ; auto generated
```
The service (sub)path would become `http://localhost:8080/FruitWebService` using the default service name (rendered from SEI's classname by default). Together with `quarkus.cxf.path=/ws` this would end up in `http://localhost:8080/ws/FruitWebService`.

Obviously a conflict arises if a second FruitWebService is implemented, i.e.
```
@WebService()
public class SecondFruitWebServiceImpl implements FruitWebService { ..}    
==>    
quarkus.cfx.endpoint."org.acme.cxf.SecondFruitWebServiceImpl".servicepath=/FruitWebService
```

This could be redeemed by either (a) using a different service name or (b) a different servicepath, i.e.
```
@WebService(serviceName = "AnotherService")               // (a)
public class SecondFruitWebServiceImpl ..

== application.properties ==
quarkus.cfx.endpoint."org.acme.cxf.SecondFruitWebServiceImpl".servicepath=/AnotherService  // (b)
```

Anyway, by scanning annotated services they just "pop-up" auto-magically. Is Quarkus not all about bringing some magic in plain dull boring webservice development?

**Comment by wh81752** [comment]
I noticed that this issue's title is misleading. `@WebServices` are of course detected by annotation scanning. So it is all about get going without further ado in `application.properties `once `quarkus-cfx` extension is present.

**Comment by dufoli** [comment]
hmm so convension over configuration.... good point but it mean that we change completely the config format. And I want to avoid that... but we can provide and mecanisme to generate without config.
idea is to generate /servicename but we need to define what name we select for the url.
serviceName
PortName
from SEI
from implementor
...
we can just use the simple class name of SEI for the moment.

**Comment by dufoli** [comment]
@shumonsharif no the perfect situation but I can not change totally configuration behaviour. 
Anyway, convention over configuration is addressed. So you can have with configuration a server running with default route on servicename. I do not manage collision for the moment... but if we have collision it can be fixed with configuration...

**Comment by shumonsharif** [comment]
I agree @dufoli I think this is good ...

**Comment by dufoli** [comment]
I have maybe a solution. scan the key of map.
if it contain / it mean it is a path , if it contain dot, it is a class. and by default I switch to class if contain no dot or slash.

**Comment by dufoli** [comment]
reopen was done by misstake.
