### ISSUE TITLE
wsdl2java: -p has invalid character when when mapping multiple namespaces to Java packages

### ISSUE THREAD

**Issue by argenstijn** [quarkiverse/quarkus-cxf#1416]
When using 

quarkus.cxf.codegen.wsdl2java.package-names[0]=test\=y
quarkus.cxf.codegen.wsdl2java.package-names[1]=jan\=x

or 
quarkus.cxf.codegen.wsdl2java.package-names=test\=y,jan\=y 

result in one -p parameter with two values separated by comma which is incorrect!. Should result in multiple -p parameter with one value.

**Comment by argenstijn** [comment]
generated-sources\wsdl2java -p ........
-p has invalid character!
Usage : wsdl2java -fe|-frontend <front-end-name> -db|-databinding <data-binding-name> -wv <wsdl-version> -p <[wsdl-namespace =]package-name>* -sn <service-name> -b <binding-file-name>* -reserveClass <class-name>* -catalog <catalog-file-name> -d <output-directory> -compile -classdir <compile-classes-directory> -impl -server -client -clientjar <jar-file-name> -all -autoNameResolution -allowElementReferences|-aer<=true> -defaultValues<=class-name-for-DefaultValueProvider> -ant -nexclude <schema-namespace [= java-package-name]>* -exsh <(true, false)> -noTypes -dns <Default value is true> -dex <(true, false)> -validate<[=all|basic|none]> -keep -wsdlLocation <wsdlLocation> -xjc<xjc-arguments>* -asyncMethods<[=method1,method2,...]>* -bareMethods<[=method1,method2,...]>* -mimeMethods<[=method1,method2,...]>* -noAddressBinding -faultSerialVersionUID <fault-serialVersionUID> -encoding <encoding> -exceptionSuper <exceptionSuper> -seiSuper <seiSuper>* -mark-generated -suppress-generated-date -maxExtensionStackDepth <maxExtensionStackDepth> -h|-?|-help -version|-v -verbose|-V -quiet|-q|-Q -wsdlList <wsdlurl>

**Comment by ppalaga** [comment]
Thanks for the report @argenstijn. It seems to be a bug on our side. A fix would be welcome.

**Comment by ppalaga** [comment]
BTW, you can use [quarkus.cxf.codegen.wsdl2java.additional-params](https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf.html#quarkus-cxf_quarkus-cxf-codegen-wsdl2java-additional-params) as a workaround:

```
quarkus.cxf.codegen.wsdl2java.additional-params = -p,test=y,-p,jan=y
```

**Comment by ppalaga** [comment]
For the record, the error message is 

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.12.1:generate-code-tests (default) on project quarkus-cxf-integration-test-wsdl2java: Quarkus code generation phase has failed: InvocationTargetException: Could not run wsdl2Java -d /home/ppalaga/orgs/cxf/qcxf/integration-tests/wsdl2java/target/generated-test-sources/wsdl2java -p http://www.example.org/add=io.quarkiverse.cxf.wsdl2java.it.add,http://www.example.org/multiply=io.quarkiverse.cxf.wsdl2java.it.multiply /home/ppalaga/orgs/cxf/qcxf/integration-tests/wsdl2java/src/test/resources/wsdl/2ns.wsdl: org.apache.cxf.tools.common.toolspec.parser.BadUsageException: -p has invalid character!
```
