### ISSUE TITLE
Mocking Junit test case for RestClientBuilder

### ISSUE THREAD

**Issue by sreekar12** [quarkiverse/quarkus-cxf#1417]
Can you please help how to mock RestClientBuilder using @QuarkusComponentTest or any other Mocking functions like Mockito or powerMockito

Example : RestClientBuilder.newBuilder().baseUri(URI).build(HandlerService.class);

could you please provide a sample mocking example for above line.

**Comment by ppalaga** [comment]
> Can you please help how to mock RestClientBuilder

If you are trying to use Quarkus CXF for serving REST endpoints or for accessing them using CXF rest client, then the answer is no. Quarkus CXF supports solely those parts of CXF that are related to SOAP WebServices. See also https://docs.quarkiverse.io/quarkus-cxf/dev/index.html#:~:text=While%20Apache%20CXF%20implements%20wide%20range%20of%20standards%20and%20specifications%2C%20Quarkus%20CXF%20is%20currently%20focusing%20only%20on%20supporting%20the%20ones%20related%20to%20Simple%20Object%20Access%20Protocol%20(SOAP)%20and%20Java%20API%20for%20XML%20Web%20Services%20(JAX%2DWS).%20Refer%20to%20Reference%20to%20learn%20which%20parts%20of%20CXF%20are%20supported.

**Comment by ppalaga** [comment]
@sreekar12 please feel free to reopen if your question is related to SOAP.
