### ISSUE TITLE
Replace `quarkus.cxf.logging.enabled` with `quarkus.cxf.logging.enabled-for` in the documentation

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#1424]
We should fix the docs to mention `quarkus.cxf.logging.enabled-for` instead.

**Comment by lasteris** [comment]
@ppalaga Can I also ask you, please, why you removed `quarkus.cxf.logging.enabled` and for what postfix `-for' stands of ?

**Comment by ppalaga** [comment]
> @ppalaga Can I also ask you, please, why you removed `quarkus.cxf.logging.enabled` > and for what postfix `-for' stands of ?

`quarkus.cxf.logging.enabled-for` allows for finer-grained control over for what the logging feature is enabled at the global level: it can namely be enabled for clients, services, both or none. - see also https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf.html#quarkus-cxf_quarkus-cxf-logging-enabled-for
