### ISSUE TITLE
WebServiceContext not injected into a service impl with `@CXFEndpoint("/my-path")`

### ISSUE THREAD

**Issue by Inithron** [quarkiverse/quarkus-cxf#1425]
Used quarkus-cxf version: 3.12.0
After the removal of the `quarkus.cxf.endpoint."/my-path".implementor` from the properties file and the usage of the annotation `@CXFEndpoint("/my-path")` the WebServiceContext was null:
```
    @Resource
    WebServiceContext wsContext;
```
This issue pops up after #1399 was fixed.

**Comment by ppalaga** [comment]
Thanks for the report @Inithron. You caught us naked, as we have zero tests for `@Resource WebServiceContext wsContext`. Let me have a look what can be done.

**Comment by Inithron** [comment]
I'm not sure if it will help but maybe it could be an inspiration for a possible test.
We set in the incoming interceptor a variable which we are using the service implementation.

```
public class IncomingRequestInterceptor extends AbstractPhaseInterceptor<Message> {

    public IncomingRequestInterceptor() {
        super(Phase.RECEIVE);
    }

    @Override
    public void handleMessage(final Message message) {
        message.getExchange().put("myVariable", "myContent");
    }
}
```

```
public class MyService {

    @Resource
    WebServiceContext wsContext;

    private String getMyVariable() {
        return (String) wsContext.getMessageContext().get("myVariable");
    }
}
```

The only open point would be a unit tests.

**Comment by ppalaga** [comment]
Thanks, I'll add it to the tests I am writing right now.
