### ISSUE TITLE
Quarkus 3.12.0 with CXF: java.lang.NullPointerException in CxfDeploymentUtils.findSei(CxfDeploymentUtils.java:60) without 

### ISSUE THREAD

**Issue by gawrilsemke** [quarkiverse/quarkus-cxf#1427]
```
[ERROR]   PackageSequenceGeneratorTest.testGetPackageId » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.cxf.deployment.CxfEndpointImplementationProcessor#collectEndpoints threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.annotation(org.jboss.jandex.DotName)" because "interfaceInfo" is null
	at io.quarkiverse.cxf.deployment.CxfDeploymentUtils.findSei(CxfDeploymentUtils.java:60)
```
	
The solution was to add a parameter 'endpointInterface' by WS Annotation: 
`@WebService(targetNamespace = "http://some", serviceName = "SomeServices", endpointInterface = "SomePortType")
public class SomePortTypeImpl implements SomePortType {...`

is it naccessery? backwards compatibility?

JavaDoc:
String jakarta.jws.WebService.endpointInterface()
The complete name of the service endpoint interface defining the service's abstract Web Service contract.

This annotation allows the developer to separate the interface contract from the implementation. If this annotation is present, the service endpoint interface is used to determine the abstract WSDL contract (portType and bindings). The service endpoint interface MAY include JSR-181 annotations to customize the mapping from Java to WSDL. The service implementation bean MAY implement the service endpoint interface, but is not REQUIRED to do so. If this member-value is not present, the Web Service contract is generated from annotations on the service implementation bean. If a service endpoint interface is required by the target environment, it will be generated into an implementation-defined package with an implementation- defined name

This member-value is not allowed on endpoint interfaces. Default: ""

**Comment by ppalaga** [comment]
Hi @gawrilsemke, thanks for the report!.

We definitely have service implementations with `implements` and without `@WebService(endpointInterface = "...` in our tests that worked both before and after 3.12.0, such as 

https://github.com/quarkiverse/quarkus-cxf/blob/333d4f46f3655e3fa0079f8df6d36c73e695eb99/integration-tests/metrics/src/main/java/io/quarkiverse/cxf/metrics/server/it/HelloServiceImpl.java#L10-L11

Regardless of that, we may have broken something in some corner case recently and I'd be very much interested to see a reproducer for your issue.

**Comment by dstein90** [comment]
Hi @ppalaga 

I traced this issue back. It boils down to having the interfaces pulled from a dependency without a jandex index and the fact the annotation scanning changed with 02f027c

**Comment by ppalaga** [comment]
Nice, thanks for the investigation, @dstein90! So adding jandex to the dependency using the [maven plugin or application.properties](https://stackoverflow.com/a/55513723) is a valid solution?

**Comment by dstein90** [comment]
Indeed generating the index on the dependency solves this issue.

**Comment by ppalaga** [comment]
I made the build fail with an informative exception if some interface cannot be found in Jandex: https://github.com/quarkiverse/quarkus-cxf/pull/1437/files

**Comment by ppalaga** [comment]
I am afraid we cannot restore the pre-3.12.0 behavior. I think throwing an exception that tells the user what to do is the best thing we can do. Or you @dstein90 have a better idea?

**Comment by ppalaga** [comment]
Closing this for now. @dstein90 please feel free to reopen, if you have any suggestion what else we could do.

**Comment by dstein90** [comment]
I think it's fine this way. But good to have the issue with the solution open. Maybe the requirement for the jandex index should be added to the docs.

**Comment by ppalaga** [comment]
Thanks, that's a good idea, @dstein90 . I filed a follow up issue: https://github.com/quarkiverse/quarkus-cxf/issues/1449
