### ISSUE TITLE
Create codestart

### ISSUE THREAD

**Issue by Dufgui** [quarkiverse/quarkus-cxf#150]
See https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/codestarts/README.adoc

**Comment by Dufgui** [comment]
https://github.com/quarkusio/quarkus/pull/15253/files

**Comment by Dufgui** [comment]
I push a codestart in quarkus repo, because i don't know how to do it for quarkiverse

**Comment by shumonsharif** [comment]
Hey @Dufgui - this is a great idea.

One suggestion, I think your PR is currently missing the extension specific application.properties entries.  You can add them as per:  https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/codestarts/README.adoc#applicationproperties

**Comment by Dufgui** [comment]
it's not available for external extension
