### ISSUE TITLE
Per client or service configuration of `sensitive-element-names` and `sensitive-protocol-header-names` not honored

### ISSUE THREAD

**Issue by rudiger3d** [quarkiverse/quarkus-cxf#1533]
This week I discovered that our client specific configuration for `sensitive-element-names` stopped working after upgrading from 2.5.0 to 3.8.2 all the way back in May, i.e. config properties of the form `quarkus.cxf.client."client-name".logging.sensitive-protocol-header-names`

I did some incremental updates and when updating from 2.6.1 to 2.7.0.CR1 the configuration stopped working.

Comparing: https://github.com/quarkiverse/quarkus-cxf/compare/2.6.1...2.7.0.CR1 it seems that the structure of lines 121-122 of the old file was copied in `LoggingFactoryCustomizer.java` lines [78-79](https://github.com/quarkiverse/quarkus-cxf/blob/main/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/logging/LoggingFactoryCustomizer.java#L78-L79) without taking into account any configuration present in the `PerClientOrServiceLoggingConfig`  object and so that only the global config is added to the configured LoggingFeature.

As per client logging configuration is still documented I assume this must be a bug.

**Comment by rudiger3d** [comment]
Substituting the lines 78-79 with the following lines will fix the issue:

```java
        clientOrServiceConfig.sensitiveElementNames()
                .or(() -> global.sensitiveElementNames())
                .ifPresent(feature::addSensitiveElementNames);
        clientOrServiceConfig.sensitiveProtocolHeaderNames()
                .or(() -> global.sensitiveElementNames())
                .ifPresent(feature::addSensitiveElementNames);
```

And (I know this is goldplating 😃) I would suggest a similar approach in the `addList` method:

```java
    private void addList(Optional<List<String>> global, Optional<List<String>> perClientOrService, Consumer<String> consumer) {
        perClientOrService
                .or(() -> global)
                .map(list -> list.stream().collect(Collectors.joining(";")))
                .ifPresent(consumer);
    }
```

**Comment by rudiger3d** [comment]
Looking into this issue has been fun so far. I'll go ahead and create a pull request

**Comment by ppalaga** [comment]
@rudiger3d thanks for the report. I can reproduce and in between I have implemented a test.

**Comment by ppalaga** [comment]
I am releasing 3.8.7 and 3.15.2 right now.

@rudiger3d thanks again for reporting this security relevant issue. If you would like to get acknowledged in the associated CVE, please send me your name to ppalaga @ redhat.com

BTW, this made us aware that we did not have reporting of security issues enabled for this repository, which we have fixed in between: https://github.com/quarkiverse/quarkus-cxf/security/advisories
Please report any potentially security relevant issues there in the future.

**Comment by rudiger3d** [comment]
Thanks for the quick response. I have sent an email (and added my name to my github profile)
