### ISSUE TITLE
Release 0.5 failed to published on maven 

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkus-cxf#154]
Relaunched workfloW is ko because current master has evolve...
We need to rollback or modify again project file to generate publication of 0.5

**Comment by dufoli** [comment]
Switched to branch 'master'
M	integration-tests/src/main/java/io/quarkiverse/it/cxf/GreetingWebServiceImpl.java
Your branch is up to date with 'origin/master'.
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.
Error: Process completed with exit code 1.

**Comment by shumonsharif** [comment]
Hey @dufoli I think the file is getting updated during the maven build.  My guess is that this line here gets removed, and the file then becomes an unstaged change.

https://github.com/quarkiverse/quarkus-cxf/blob/master/integration-tests/src/main/java/io/quarkiverse/it/cxf/GreetingWebServiceImpl.java#L3

We just need to get rid of that import statement, and I think it should work.

**Comment by dufoli** [comment]
yes I arrive to same conclusion... I done some shits to push it but finally push it with the fix. Now have to wait to see if it is released !

**Comment by dufoli** [comment]
done
