### ISSUE TITLE
Unsatisfied dependency for type io.opentelemetry.api.OpenTelemetry and qualifiers [@Default]

### ISSUE THREAD

**Issue by mcanzerini** [quarkiverse/quarkus-cxf#1551]
We distribute an internal framework on top of quarkus and we wanted to know if our framework (tipically some extensions) was still compatible with the current LTS quarkus 3.8
In my test app, I downgraded all quarkus bom to 3.8.6 and I got this error at runtime:

```
ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.opentelemetry.api.OpenTelemetry and qualifiers [@Default]
        - injection target: io.quarkiverse.cxf.opentelemetry.OpenTelemetryCustomizer#openTelemetry
        - declared on CLASS bean [types=[io.quarkiverse.cxf.CxfClientProducer$ClientFactoryCustomizer, io.quarkiverse.cxf.transport.CxfHandler$EndpointFactoryCustomizer, java.lang.Object, io.quarkiverse.cxf.opentelemetry.OpenTelemetryCustomizer], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.opentelemetry.OpenTelemetryCustomizer]
```

I am stuck here without any clue on what can lead to this error.
Anyhelp will be much appreciated, thanks 🙂

**Comment by mcanzerini** [comment]
In my debugging journey, I tried to comment this dependency in my pom.xml : 
```
<dependency>
  <groupId>io.quarkiverse.cxf</groupId>
  <artifactId>quarkus-cxf-integration-tracing-opentelemetry</artifactId>
</dependency>
```

Then my app can build and run as excpected.

I cannot explain this behaviour, can someone help me to understand this and fix the issue?

**Comment by codespearhead** [comment]
When upgrading or downgrading any software, be mind the upgrading guides [1][2].

This change was catalogued here [3]. 

Could you please close this issue [4]?

***
[1] https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/index.html
[2] https://github.com/quarkiverse/quarkus-cxf/tree/main/docs/modules/ROOT/pages/release-notes
[3] https://github.com/quarkiverse/quarkus-cxf/blob/10a319c15cbde7ea95266cb12ea2e4551eda20d7/docs/modules/ROOT/pages/release-notes/3.14.0.adoc?plain=1#L17-L26
[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue
