### ISSUE TITLE
ClassCastException when using Async Client

### ISSUE THREAD

**Issue by dabkhazi** [quarkiverse/quarkus-cxf#1585]
I created a test project to check the functionality of the asynchronous client as described in the HTTP Async Transport section. I created a server and a client for testing. Here is the link to the project on GitHub:
https://github.com/dabkhazi/quarkus-soap-async-test
However, I am unable to use the asynchronous client due to the following error:

java.lang.ClassCastException: class org.apache.cxf.jaxws.JaxwsResponseCallback cannot be cast to class io.netty.util.concurrent.Future
(org.apache.cxf.jaxws.JaxwsResponseCallback and io.netty.util.concurrent.Future are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader)

The test project uses Java 17 and Quarkus 3.15.1. Do you have any ideas on what might be going wrong?

**Comment by ppalaga** [comment]
Thanks for the report and reproducer, @dabkhazi. I guess the import around here should be `java.util.concurrent.Future` rather than `io.netty.util.concurrent.Future` https://github.com/dabkhazi/quarkus-soap-async-test/blob/main/client/src/main/java/io/github/dabkhazi/wscalculator/boundary/CalculatorResource.java#L5

**Comment by dabkhazi** [comment]
@ppalaga Thank you very much, I fixed the Future class and now everything works. But I saw that there was no need to implement asynchronous processing in a special way for the server, because according to the logs it is not called and it can be safely removed from the server implementation. Also frustrating is the fact that the asynchronous call comes from the eventloop thread, and the response returns to the worker thread.

**Comment by ppalaga** [comment]
> Also frustrating is the fact that the asynchronous call comes from the eventloop thread, and the response returns to the worker thread.

Yeah, the execution and result on a worker thread is given by CXF design. The only thing we customize in that area on Quarkus is using a worker thread pool managed by Quarkus.

Actually, the lazy client initialization on first use may block if you set a WSDL URL on the client via `quarkus.cxf.client."client-name".wsdl`. In that case the even loop would be blocked and the best practice is to suspend to a worker thread strainght away, e.g. by annotating the REST endpoint by `@io.smallrye.common.annotation.Blocking`.
