### ISSUE TITLE
Support HTTP redirects with `VertxHttpClientHTTPConduit`

### ISSUE THREAD

**Issue by dcheng1248** [quarkiverse/quarkus-cxf#1609]
When sending SOAP requests with the default VertxHttpClientHTTPConduitFactory I get a HTTP 302 Redirection error.

The request works outside the app and the problem is solved by setting
`quarkus.cxf.http-conduit-factory=URLConnectionHTTPConduitFactory`

Not sure what is causing this error in the new default factory, any advice would be appreciated.

**Comment by ppalaga** [comment]
Do you have any stack trace by any chance? This would be to see where in the flow the exception happens. The main two suspects are accessing the remote service endpoint and accessing the remote WSDL. But could also be something else.
Can you perhaps give more hints, so that we can reproduce the behavior?

**Comment by ppalaga** [comment]
Thanks for the info, @dcheng1248. I really appreciate it as our aim is to make VertxHttpClientHTTPConduitFactory a drop in replacement for URLConnectionHTTPConduitFactory. I'll have a look how redirecting could be enabled for the VertxHttpClientHTTPConduitFactory.

**Comment by ppalaga** [comment]
@dcheng1248 the fix is available in Quarkus Platform 3.17.0. It would be great to hear whether it fulfills all your needs. 
Note that offloading the request data to disk is not implemented yet https://github.com/quarkiverse/quarkus-cxf/issues/1628

**Comment by dcheng1248** [comment]
@ppalaga many thanks for the quick update and notification. I will test it out soon and report back.
