### ISSUE TITLE
Add `quarkus.cxf.client."client-name".max-same-uri` configuration option

### ISSUE THREAD

**Issue by dcheng1248** [quarkiverse/quarkus-cxf#1639]
The default implementation of the HTTP Conduit now uses the VertxHttpClientHTTPConduit, which throws an Redirection Loop error when redirected to the same URL if the http.redirect.max.same.uri.count property is not set. There is no quarkus property corresponding to this property and it needs to be set as a system property when starting the app. 

This is in contrast to the original default (in quarkus 3.15 and before) URLConnectionHTTPConduit where redirection (also to the same URL) are automatically enabled so no properties need to be set. 

Would it be possible to add a quarkus property corresponding to this for easier usage? Thank you!

**Comment by dcheng1248** [comment]
@ppalaga I'm not sure how contribution to quarkus works, but any chance I could perhaps try my hands on this in my free time and submit a PR?

**Comment by ppalaga** [comment]
That would be highly welcome! You may want to have a look at recent commits to see where to add the feature and a test. Let me assign this issue to you.

**Comment by ppalaga** [comment]
We have a basic [Contributor guide](https://docs.quarkiverse.io/quarkus-cxf/dev/contributor-guide/index.html#how-to-build), FWIW.

**Comment by dcheng1248** [comment]
Thank you! I will try my best, but it might take a bit of time to learn the workflow. Please let me know if it becomes an urgent issue and I'm delaying progress!

**Comment by dcheng1248** [comment]
@ppalaga so I've been trying to get my hands on it a little. One problem that I'm running into (unrelated to this issue) is when running mvn verify, the AntoraTest in the doc module hangs. I've poked around a bit but made no progress. I use Podman instead of Docker. Any advice there - am I missing something? Thanks!

**Comment by dcheng1248** [comment]
I'm on apple M1 so that is probably it. I'll try the new version - thanks!

**Comment by ppalaga** [comment]
quarkus-antora is now at 1.0.1, where `quarkus.antora.image` defaults to `docker.io/antora/antora:3.1.10`. So you just need to rebase.

**Comment by dcheng1248** [comment]
@ppalaga dumb question: is there a way to enable cookie session maintenance or is that part of #1616 ? 

I'm testing the new property and trying to get the test service to return a cookie that stores the number of self redirections for counting. The response comes back with the correct set-cookie header, but the cookie does not get added to the new headers because the maintain session flag of the cookies in the conduit is set to false. I've dug around a bit but failed to find a way to enable this. 

I can work around this but the test service won't be as pretty... and I guess cookie session maintenance is also good to know about in general!

**Comment by dcheng1248** [comment]
@ppalaga I created a [PR](https://github.com/dcheng1248/quarkus-cxf/pull/1) towards my own forked main, can you take a look? I tried my best to match the formatting of the code but there may still be things off. For the test service I used the workaround for now. If things look OK later I can create a PR towards the cxf main.

Side note: when I do mvn install -Pnative I get an error:
WsReliableMessagingIT>WsReliableMessagingTest.testTwowayMessageLoss:38 » Runtime Timed out waiting for Installed features: [ in target/ws-rm-server-native.log
However I get this also on the main so I don't think it's my changes. However, I cannot figure out what the problem is - I am admittedly super unfamiliar with the native build as I've never worked with it before.
All tests pass on JVM.

**Comment by ppalaga** [comment]
> I created a [PR](https://github.com/dcheng1248/quarkus-cxf/pull/1)

Thanks a lot! I commented there.

**Comment by dcheng1248** [comment]
@ppalaga thank you! I've got my hands a bit full these few days but will get back onto it once I can. Note: having this quarkus property does not solve my full issue with the server, now it complains that we try to retransmit to a closed connection... 

I will try to go through the URLConnectionHTTPConduit and the VertxHTTPConduit in dev mode to see if I can pinpoint the exact cause for the difference in behaviour. Would you prefer if I find it out and fix that before submitting a PR to main, or is creating this quarkus property anyway helpful?

**Comment by dcheng1248** [comment]
@ppalaga I just wanted to say thank you again for helping me make a tiny contribution! You did most of the work but it's still my first ever OS contribution and it makes me proud. As mentioned in the previous comment, there still seems to be some difference in behaviour (our actual issue on prod is not solved), but I will investigate more and open another issue for this.

**Comment by ppalaga** [comment]
Thank you very much @dcheng1248 for your part! I am happy I could help.
