### ISSUE TITLE
Client using SOAP 1.2 sends no SOAP Action

### ISSUE THREAD

**Issue by CodedNikls** [quarkiverse/quarkus-cxf#1640]
I configured my quarkus cxf client to use SOAP 1.2 via the soap-binding property like this:

`quarkus.cxf.client.myClient.soap-binding=http://www.w3.org/2003/05/soap/bindings/HTTP/`

The client is set up using the @CXFClient annotation and an interface generated from a wsdl file, which has been working so far. 
Before, the messages it sent out used to have a Header "SOAPAction", now they don't. 

Is there a solution to this I am missing or is this a bug?
Thank you in advance!

**Comment by CodedNikls** [comment]
Thank you for the answer @ppalaga! After further investigation, we have discovered that a SOAPAction header is not required in SOAP 1.2 anymore and the soap action has instead been moved to the content-type in format 
"Content-Type: application/soap+xml; charset=utf-8; action="[...]""
So, right now we are stuck on the issue regarding the content-type and will need to investigate the Soap action there as well.

**Comment by ppalaga** [comment]
Thanks for the feedback, @CodedNikls. Let's focus on https://github.com/quarkiverse/quarkus-cxf/issues/1641 then.
