### ISSUE TITLE
Missing vertx dependency in 3.17

### ISSUE THREAD

**Issue by jcjveraa** [quarkiverse/quarkus-cxf#1666]
Hi there,

While debugging https://github.com/quarkiverse/quarkus-cxf/issues/1665, I found that adding `quarkus-vertx` to my 'hardcoded' dependencies caused `quarkus-cxf` 3.17.3 to work rather than throwing the error described in the linked issue. I guess (another sub-dependency of?) `quarkus-vertx` should be a transistive dependency of `quarkus-cxf`?
```xml
	<dependency>
		<groupId>io.quarkus</groupId>
		<artifactId>quarkus-vertx</artifactId>
	</dependency>
````

**Comment by ppalaga** [comment]
Could you please run `mvn dependency:3.8.1:list -Dsort` with and without the `quarkus-vertx` direct dependency and see whether there is some difference?

**Comment by jcjveraa** [comment]
Apologies, I seem to have incorrectly tested against a wrong build of my code. You are correct, so this issue is a non-issue while #1665 continues to be an issue.
