### ISSUE TITLE
Question: Using a Soap Service and Client in the same project

### ISSUE THREAD

**Issue by chet20r** [quarkiverse/quarkus-cxf#167]
I think this is more of a question on the usage than a bug.

I've got a Quarkus project that exposes a ReST endpoint say "/hello". This would then call a SOAP Service and then return the response.

What I need to do is to have a proxy soap service implementation within the quarkus service that proxies the request to the external soap service, fetches the results, modifies the results based on another rest call to another service and returns the response back to the user.

The result I am trying to achieve is something like below

<img width="657" alt="Screen Shot 2021-03-03 at 11 19 40 am" src="https://user-images.githubusercontent.com/7542319/109733052-76d72980-7c12-11eb-87ec-2f658d58e723.png">

The problem I am facing now is that when I inject the soap client in my ReST resource, It is configured to call the soap proxy service implementation which is also in the quarkus project. However, within this soap implementation, I need a client that is configured to connect to an external soap service which is where I have trouble configuring.

I've got something in the repo here but not able to get it work 👉🏽  https://github.com/chet20r/quarkus-cxf-interceptor-issue

Any help is appreciated 🙏🏽

**Comment by shumonsharif** [comment]
Hey @chet20r I couldn't think of a good solution for your needs, I'm not sure how you would inject an instance of a class into itself ... however, did you already consider something like the below?

```java
CalculatorSoap calculatorSoapClient = new Calculator().getCalculatorSoap12();
```

**Comment by chet20r** [comment]
Thanks @shumonsharif . I did think about the solution you have suggested but just wanted to check if there was a better / cleaner approach. With the approach you have suggested, I have to configure the client with the right endpoint, basic auth, timeouts, etc. So if thats the only option, then I'll go with that 👍🏽 Thanks a lot for taking time to answer my query 😄

**Comment by shumonsharif** [comment]
Hey @chet20r it's getting late here. :) so I'm definitely going to give it some thought later and keep you posted if I can think of a good solution ... in the meantime, I did have a question - as I'm not sure I understood the issue to begin with.  It seems you are trying to expose a `proxy-service` endpoint.  

Why not create a `MyCalculatorServiceInterface` and make your `MyCalculatorService` implement that?  That should then allow you to wrap and inject `CalculatorSoap` as needed.  You can also inject `MyCalculatorService` elsewhere if needed.  Let me know if that will address your issue ...

**Comment by chet20r** [comment]
Hi @shumonsharif  Yes, I am trying to expose a SOAP service (proxy-service) that exposes the same WSDL contract as the external service (Calculator Service). The proxy-service then makes a call to the external Calculator service and also makes a ReST call to another service, merges the data and returns the response conforming to the WSDL contract.

And not sure why it did not occur to me 🤦🏽  but your solution to create a separate interface for the proxy-service works for me 👍🏽 . thanks a lot again for your time
