### ISSUE TITLE
Documentation: Creating a SOAP Client

### ISSUE THREAD

**Issue by wh81752** [quarkiverse/quarkus-cxf#177]
The [documentation about create a SOAP proxy](https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/client.html) client needs some improvment (IMHO):

```
quarkus.cxf.endpoint."/fruit".client-endpoint-url=http://localhost:8080/
quarkus.cxf.endpoint."/fruit".service-interface=org.acme.cxf.FruitWebService
```

(A) The example assumes an (external) endpoint published at address http://localhost:8080/fruit featuring SEI org.acme.cxf.FruitWebService. It is not obvious that "/fruit" and the value's property are joined to become the final address.

(B) The _configuration_ of such a client proxy is currently (0.6.0-SNAPSHOT) possible for a truly external service, only for a service _without_ an implementation. Here's an example:

```
@WebService
public GreetingImpl implements GreetingService {}      // Here we have IMPL and SEI
@WebService
public interface FruitWebService {}                                 // SEI only, no IMPL in classpath
```

Given this setup, then
```
@Inject GreetingService greetingClient;                        // This works regardless of any config in application.properties 

@Inject FruitWebService fruitClient;                               // This bean is produced by quarkus-cxf if a configuration 
                                                                                           // like above is present, otherwise not.
```

Viewed from another angle being application.properties:
```
quarkus.cxf.endpoint."/greet".client-endpoint-url=http://localhost:${quarkus.http.port}/
quarkus.cxf.endpoint."/great".service-interface=org.acme.cxf.GreetingService
quarkus.cxf.endpoint."/great".features=org.apache.cxf.feature.LoggingFeature
```

This setup is or appears to be silently ignored.

For reasons of consistency it would be really smooth if there is no difference - configuration of an internal or  external service should follow the same pattern.

**Comment by famod** [comment]
> (A) The example assumes an (external) endpoint published at address http://localhost:8080/fruit featuring SEI org.acme.cxf.FruitWebService. It is not obvious that "/fruit" and the value's property are joined to become the final address.

+💯! This is really confusing currently because it doesn't make sense having to set a relative path for a _client_.
I'd find it way more intuitive to just freely choose some descriptive name instead of a relative path. The value of the property would then be the _full_ URL.

**Comment by wh81752** [comment]
> Btw: What if that external webservice doesn't use a context path at all and is instead reachable directly via http://localhost:8080/? Is the infix then just "/", e.g. quarkus.cxf.endpoint."/".client-endpoint-url=...?

I guess that would be the logical consequence.

In addition: what if there are two services published at "/" or, more generally, published with the same path, i.e.

```
https://allfruits.com/fruits
https://worldfruits.com/fruits 
```

**Comment by dufoli** [comment]
@famod I know . For config, I start with server and hen I work on client, I want to reuse same config to simplify work and I never came back to it. And I was afraid to change format of config later for backward compatibility. Anyway @wh81752 take the point and a big patch will arrive for that.

**Comment by famod** [comment]
@dufoli I get it, start simple and reuse stuff, make it more complicated later. 😁

**Comment by wh81752** [comment]
@dufoli , @famod - I guess we can also close this issue, right?

**Comment by famod** [comment]
I think so, yes. Thanks a lot @wh81752!

**Comment by tbkahuna48** [comment]
easiest way to create a soap client is just treat it as XML over HTTP and simply use resteasy jaxb to marshall the response xml. Easy if you hav a simple request xml body.
However, looking for a templating engine that will make marshaling the request easier when the request body xml is more ocmplicated.

**Comment by shumonsharif** [comment]
Hi @tbkahuna48 The purpose of this extension is to leverage CXF to support the myriad of WS-* specifications and standards.  

Having said that, if the use case is very simple - one can leverage just the [Quarkus REST client](https://quarkus.io/guides/rest-client) to invoke an HTTP SOAP endpoint, without even having a need to marshal the response using RESTEasy JAXB.

> However, looking for a templating engine that will make marshaling the request easier when the request body xml is more complicated.

I'm not sure what you mean by the above?  You can auto-generate your Java model classes from any schema, and then use those for JAXB marshaling.  I don't quite see how a templating engine fits in with JAXB.

**Comment by tbkahuna48** [comment]
Sorry mixed dialog there. The template freemarker - just makes it easy to create the xml content for the  request body without needing a pojo for marshaling. The quarkus jaxb stuff makes it easy to use buildEntity(Some.class) on the returned response to marshal the response content.  However, soap messages , particularly when tags have attributes, so just wishing there was some utility to marshal something that less ugly.
