### ISSUE TITLE
Interface of web service is in other library

### ISSUE THREAD

**Issue by mnouwens** [quarkiverse/quarkus-cxf#179]
We have a seperate project that generated the classes based on the wsdl.

When we include this library and implement it ti fail to load correctly.

Please see attached example:

# code-with-quarkus project

First run mvn clean install in gio-digimelding-service-wsdl

Then You can run the application in dev mode that enables live coding using:
```shell script
./mvn compile quarkus:dev
```

Open http://localhost:8080/cxf/fruit?wsdl to see the wsdl

The stacktrace below has been reversed to show the root cause first. Click Here to see the original stacktrace

java.lang.NullPointerException
at io.quarkiverse.cxf.transport.CxfHandler.process(CxfHandler.java:275)
at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:207)
at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:48)
at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)

The class AnnotatieInterfaceImpl shows the problem. Is the class is implementing default the Interface from the library.

There are also 2 lines that use the inrface when copied into the project itself. Then the wsdl will work as expected.

**Comment by dufoli** [comment]
I think you can use indexDependencyConfig
```
quarkus.index-dependency."dependency-name".group-id=
quarkus.index-dependency."dependency-name".artifact-id=
quarkus.index-dependency."dependency-name".classifier=
```
to add some external dependency to index.

**Comment by dufoli** [comment]
please read https://quarkus.io/guides/cdi-reference for detail about how to add more dependencies to index.

**Comment by shumonsharif** [comment]
Hi @mnouwens Did you resolve your issue?  Let us know if you still have trouble, I'm sure I can find you an example or two that may be helpful ...

**Comment by querdenker2k** [comment]
I had the same problem, but adding the jandex plugin solved it. But within the native image it's the same problem and i don't know how to resolve.

**Comment by chet20r** [comment]
hey @mnouwens  see if this helps. I've setup a sample project which has generated soap artifacts in a separate module that I am using in another quarkus module.

https://github.com/chet20r/quarkus-cxf-interceptor-issue

**Comment by vipseixas** [comment]
@mnouwens I have the wsdl and generated classes in another project and it only worked after I included the jandex-maven-plugin in the pom, like this:

```
<plugin>
  <!-- Ensure that beans defined in this lib will be found by Quarkus CDI -->
  <groupId>org.jboss.jandex</groupId>
  <artifactId>jandex-maven-plugin</artifactId>
  <executions>
    <execution>
      <id>make-index</id>
      <goals>
        <goal>jandex</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

Maybe that's what is missing for you.

**Comment by famod** [comment]
@shumonsharif @dufoli I think this should be closed. The only thing that could be done here IMO is to add some hints to the docs.
