### ISSUE TITLE
Native image generation problem

### ISSUE THREAD

**Issue by aruffie** [quarkiverse/quarkus-cxf#186]
Dear,

I have a native image generation problem, and I don't know where to begin investiguate.
Do you have an idea ?
[quarkus-dalkia-ticket-loader-bug.zip](https://github.com/quarkiverse/quarkus-cxf/files/6242795/quarkus-dalkia-ticket-loader-bug.zip)

I put in attache file my project (just login/password removed for cassandra), the full log trace, and the screen
![quarkus1](https://user-images.githubusercontent.com/80361700/113280627-d34a6900-92e4-11eb-89be-bab5072d31b0.png)
[quarkus-cxf-native-error-generation.txt](https://github.com/quarkiverse/quarkus-cxf/files/6242804/quarkus-cxf-native-error-generation.txt)

Do you know I can fix the problem plz ?
I can help for the resolution, if need

Adrien Ruffié

**Comment by shumonsharif** [comment]
Hi @aruffie you can take a look at the following issue which was resolved, I believe it is the same exception.

https://github.com/quarkiverse/quarkus-cxf/issues/139

**Comment by aruffie** [comment]
Hi @shumonsharif thank for your link, so I used:
/Java/Web-innovation/quarkus/quarkus-dalkia-ticket-loader/ mvn clean package -Pnative -am -Dquarkus.native.container-build=true -Dimage-native.xmx=9g

with the @dufoli  fixe about properties in my pom.xml and removing quarkus plugin like in this ticket :https://github.com/chet20r/quarkus-cxf-interceptor-issue/issues/1

butfor know I got this following exception:
![quarkus1](https://user-images.githubusercontent.com/80361700/113353324-c5750200-933d-11eb-92b0-37b91dec6411.png)
and log file:
[quarkus-log2.txt](https://github.com/quarkiverse/quarkus-cxf/files/6246451/quarkus-log2.txt)

I despair :'( do you have an idea ?

**Comment by shumonsharif** [comment]
Hey @aruffie I believe it's exactly as the error message says - your OperationOrderStatusType class contains a lot of non ASCII characters.  Would suggest you clean it up and convert to ASCII only, it should fix the issue.

**Comment by dufoli** [comment]
Hmm I see CRéé in where we need ASCII. Do you use French word in Wsdl or in method?

**Comment by dufoli** [comment]
Ça you do full text search for créé

**Comment by shumonsharif** [comment]
@dufoli It's not just créé that's a problem, anything starting with `\u` (see image below) will be a problem.  Having said that, I searched your codebase @aruffie and `OperationOrderStatusType` is the only class I see with this issue.

<img width="470" alt="non-ascii" src="https://user-images.githubusercontent.com/13334073/113480567-e125f880-9462-11eb-8b05-bff305db499e.png">

**Comment by aruffie** [comment]
Yes yes sorry for responding late but the week was very overhelming to manage my team and several production problems during working holiday. Thank you both for your help @shumonsharif & @dufoli . CXF doesn't produce any problem now during native image generation or runtime. I just got a Jackson's Serializer missing class I think ... for sending the SOAP message received from CXF to Kafka, but this is another subject 😂 (If you have an idea, I take it :+1:  ) but for now you can close this thicket. Once again thx very much. I think after this previous problem fixing, the overall of this our microservice will work properly, and I can after that, improve the CFX Quarkus' Extension documentation/user's doc/first use case or example, if you are open 😁
![kafka-native-error](https://user-images.githubusercontent.com/80361700/113487987-8967ab80-94bb-11eb-8f84-90c142653f6f.png)

**Comment by aruffie** [comment]
I found the solution for jackson with @RegisterForReflexion ! You can close de ticket :-) tomorrow I begin idea for documentation/tutorial/other think of the return of my first experience in order to help next developers :-)

**Comment by dufoli** [comment]
@aruffie je suis français aussi 😉

**Comment by aruffie** [comment]
> @aruffie je suis français aussi

oui oui j'avais compris 😁 mais c'était pour que les gens qui tombent sur mon ticket et non français puisse avoir un retour. Tu penses que je peux vous aider à faire quoi sur la doc, page wiki, ... ? Si je peux mettre la mains à la pâte  :-)
