### ISSUE TITLE
Not able to get Native working 

### ISSUE THREAD

**Issue by dinosath** [quarkiverse/quarkus-cxf#193]
Hello i tried cxf-extension in JVM mode and everything is ok. When i tried to build Native mode although the build is a success during runtime i get the error

`Provider com.sun.xml.bind.v2.JAXBContextFactory not found`

After that i tried adding the following dependencies in my pom.xml

`                <dependency>
                    <groupId>jakarta.xml.bind</groupId>
                    <artifactId>jakarta.xml.bind-api</artifactId>
                    <version>2.3.2</version>
                </dependency>
                <dependency>
                    <groupId>org.glassfish.jaxb</groupId>
                    <artifactId>jaxb-runtime</artifactId>
                    <version>2.3.2</version>
                </dependency>`

And during the native build it fails with 

`com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput got initialized use --trace-class-initialization=com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput
`

I tried quarkus-cxf 0.5 with both Quarkus 1.11.3.Final , 1.13.0.Final and 1.13.2.Final and in all i get the same errors.
I cannot submit my project because is propretiary and compared to the example project the wsdl in my case is more complex.
Did anyone encountered the same?

**Comment by shumonsharif** [comment]
Hi @dinosath Please have a look at the suggestions at:  https://github.com/quarkiverse/quarkus-cxf/issues/172 - it's the same error, so may possibly be helpful for your situation; let us know if it's still an issue.

**Comment by dufoli** [comment]
The null pointer exception on native must come from same issue than Uber jar. Duplicate file must be merged

**Comment by dufoli** [comment]
About fastinfoset a patch has land on last version.

**Comment by dufoli** [comment]
I have implement the merge of bus-extensions.txt on a #210

**Comment by dufoli** [comment]
Can you retry with last release ? Many things has been fixed (JAXBContextFactory , provider,...)

**Comment by dufoli** [comment]
ok I close this ticket. Many fixes has been done and I think it is now ok. And it is working for others users.

**Comment by dinosath** [comment]
Sorry for not answering. I encountered an issue that relates to an open quarkus bug. I tried stripping some of the code and leaving only cxf to see if everything is ok. I will try with a new project only with cxf-codegen and quarkus-cxf. Thank you for all your help
