### ISSUE TITLE
Using resteasy reactive with this plugin doesn't work

### ISSUE THREAD

**Issue by chet20r** [quarkiverse/quarkus-cxf#197]
When I try to use resteasy reactive module from quarkus along with the quarkus-cxf dependency, the rest endpoints do not work and I get a 404 for the routes.

Here is a sample project to replicate the issue. I have a simple rest endpoint using resteasy reactive and it also includes quarkus-cxf dependency. When I try run `mvn clean compile -pl sample-rest -am quarkus:dev` and try to hit `http://localhost:8080/hello` then I get a 404 not found although the endpoint is defined in the resource

When I remove the quarkus-cxf extension, then I can see the endpoint returns a response.

https://github.com/chet20r/quarkus-cxf-interceptor-issue/tree/main/sample-rest

**Comment by shumonsharif** [comment]
@chet20r Did you already try separating resteasy and CXF paths as per:  https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/tips-and-tricks.html#_rest_and_soap_endpoints

**Comment by chet20r** [comment]
Yes. In my application properties, I've got those properties defined. This is an issue only with resteasy reactive

![Screenshot_20210427-223512_GitHub.jpg](https://user-images.githubusercontent.com/7542319/116242557-5d350700-a7a9-11eb-8c2d-2af820676e80.jpg)

**Comment by famod** [comment]
Mostly by chance, I found a fix for this issue (which also affects my current project): #204 

@chet20r Your sample project now works for me (with `0.7.0-SNAPSHOT` built from #204). Can you please double-check? Thanks!

**Comment by chet20r** [comment]
> Mostly by chance, I found a fix for this issue (which also affects my current project): #204 
> 
> @chet20r Your sample project now works for me (with `0.7.0-SNAPSHOT` built from #204). Can you please double-check? Thanks!

Thank you. I'll test that out soon. On the other hand do you know if the webservice endpoint that   quarkus-cxf exposes is a reactive endpoint? I think it's not and runs on a blocking worker thread. Is my thinking right?

**Comment by famod** [comment]
@chet20r I suppose it isn't reactive, but better ask @dufoli or @shumonsharif.

**Comment by shumonsharif** [comment]
Hey @chet20r Please review the notes at https://github.com/quarkiverse/quarkus-cxf/issues/4. The extension is not reactive - however, everything should already be asynchronous and non-blocking; to implement async CXF calls you just need to include the `cxf-rt-transports-http-hc` dependency.  Feel free to open a new ticket in case of any issues!
