### ISSUE TITLE
Not able to get the add method in Fruit example to work

### ISSUE THREAD

**Issue by PerJV** [quarkiverse/quarkus-cxf#203]
I'm  working on this example :
https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/server.html

When I test the Fruit service (list method) with the  curl command provided in the example it works, but I'm not able to get the add method working

I'm trying with this curl:

```
curl -X POST "http://localhost:8080/cxf/fruit" \
 -H 'Content-Type: text/xml' \
 -H 'SOAPAction:' \
 -d '
 <soapenv:Envelope
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:cxf="http://cxf.acme.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <cxf:add>
	     <Fruit>
            <name>Pineapple</name>
            <description>Tropical fruit</description>
         </Fruit>	  
	  </cxf:add>
   </soapenv:Body>
</soapenv:Envelope>'
```

The request is entering the add method, but the fruit is null.

Repo :  https://github.com/PerJV/fruit-example

**Comment by PerJV** [comment]
I think I have found a solution. It's working after adding WebParam annotation on Fruit param in add method :

`    @WebMethod
    Set<Fruit> add(@WebParam(name = "Fruit") Fruit fruit);`

**Comment by shumonsharif** [comment]
Hi @PerJV In case you are new to SOAP, I would suggest you review some SOAP and Apache CXF tutorials, to better understand how everything works ... it'll certainly help as you try to use the extension.

Having said that, for the example referenced in the docs, you can import the WSDL located at http://localhost:8080/cxf/fruit?wsdl into a tool like SoapUI to auto generate some sample payloads.

You don't need any modifications to the code for the add example to work, you just need to update the payload in your curl command ... the following should work fine.

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cxf="http://cxf.acme.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <cxf:add>
         <arg0>
            <name>PerJV Fruit</name>
            <description>PerJV Fruit Test</description>
         </arg0>
      </cxf:add>
   </soapenv:Body>
</soapenv:Envelope>
```
