### ISSUE TITLE
SOAP 1.2?

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#205]
I stumbled upon this:
https://github.com/quarkiverse/quarkus-cxf/blob/9569c3cc504a2dec9e56ca412cd300ea68334d00/deployment/src/main/java/io/quarkiverse/cxf/deployment/QuarkusCxfProcessor.java#L209-L210

Does that mean that currently only SOAP 1.1 clients are supported?

**Comment by shumonsharif** [comment]
Hi @famod I believe you've stumbled upon a valid issue.  However, I think most SOAP 1.2 endpoints (depending on the frameworks in play) should be backward compatible and support SOAP 1.1 payloads - though as per the spec, the endpoints do have the option to throw a SoapFault if they choose to.  

Bottom line, I believe the client currently only generates SOAP 1.1 payloads ... this will need to be addressed as per the TODO.  Let's wait to hear from @dufoli and get his confirmation.

**Comment by famod** [comment]
Hi @shumonsharif, thanks for your feedback.

> should be backward compatible and support SOAP 1.1 payloads

I fear the service(s) we need to connect to in our current project are 1.2 only.

Anyway, looks like a rather easy fix/enhancement.

**Comment by dufoli** [comment]
pretty easy fix indeed.
Implementor support 1.2 binding.
but not client. That is forgotten missing feature. Anyway pretty easy to fix.
and the big patch pending need to address it too.

**Comment by dufoli** [comment]
can you test it ?
if it is ok for you @famod , I will do a release with : 
- inputStream fix
- drop undertow dependancy
- soap 1.2 client.
it is not that much but it fix important stuff. So I guess we can release before to import the BIG patch with config change.

**Comment by dufoli** [comment]
Hmm thinking to add the same config for server part.

**Comment by famod** [comment]
> if it is ok for you @famod , I will do a release with :
> 
>     * inputStream fix
> 
>     * drop undertow dependancy
> 
>     * soap 1.2 client.
>       it is not that much but it fix important stuff. So I guess we can release before to import the BIG patch with config change.

That would be **excellent**!

> can you test it ?

I'm afraid I'm totally swamped for the rest of teh week, sorry!

**Comment by famod** [comment]
> Hmm thinking to add the same config for server part.

Makes sense if you ask me!

**Comment by dufoli** [comment]
I have update my branch before merge for server too. So no worry about this comment ;-)

**Comment by famod** [comment]
You implement faster than I can comment. 😉

**Comment by wanderingfella** [comment]
I have been banging my head against the wall for the best part of a day now, and I think this is why!
I am using wsdl2java to generate client code, and when calling the service it seems to be forcing to soap 1.1 and the server only seems to support 1.2. The WSDL specifies 1.2, I have tried various things like forcing the generated webservice to be 1.2

Looking through the code today, I noticed the binding config. So I tried this.

quarkus.cxf.client."CLIENT".soapBinding=http://www.w3.org/2003/05/soap/bindings/HTTP/

I am getting this in the logs though..

WARN: Unrecognized configuration key "quarkus.cxf.client."CLIENT".soapBinding" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

This is using quarkus-cxf:0.9.

Is there another version I need to use?

Thanks!

**Comment by famod** [comment]
@wanderingfella have you tried "kebab-case" instead?
```
quarkus.cxf.client."CLIENT".soap-binding=...
```

@dufoli
`soap-binding` is not listed here: https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/properties.html

Also, are users really supposed to set a URL instead of something more descriptive like `SOAP12HTTP_BINDING`?

PS: I must admit that I'm not (yet!) using this feature in my project.

/cc @shumonsharif

**Comment by dufoli** [comment]
TODO document config element

**Comment by wanderingfella** [comment]
Thanks @famod, that worked. Sorry, I was looking at the config in the code and didn't consider.
It hasn't exactly solved my issue though.

To make it work before now, I was pointing CXF at the WSDL, and at runtime it seemed to make it use Soap 1.2. Now I can configure SOAP 1.2, I have taken away the config which pointed at the WSDL.

I was hoping the runtime processing of the WSDL, was making the first call slow. However that hasn't helped.

There seems to be 7 seconds between the log message below, and the call interceptor logging the outgoing message.

{
    "timestamp": "2021-07-30T13:08:53.921Z",
    "sequence": 56,
    "loggerClassName": "org.apache.cxf.common.logging.AbstractDelegatingLogger",
    "loggerName": "org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean",
    "level": "INFO",
    "message": "Creating Service {http://*****}Service from class *.*.*",
    "threadName": "main",
    "threadId": 1,
    "processId": 9
}

I don't think it's a quarkus issue by the way, annoying all the same!
