### ISSUE TITLE
Wrong anonymous ServletInputStream implementation in VertxHttpServletRequest

### ISSUE THREAD

**Issue by vipseixas** [quarkiverse/quarkus-cxf#206]
The problem is at this line:

https://github.com/quarkiverse/quarkus-cxf/blob/9569c3cc504a2dec9e56ca412cd300ea68334d00/runtime/src/main/java/io/quarkiverse/cxf/transport/VertxHttpServletRequest.java#L110

It is an anonymous implementation of ServletInputStream and it implements `InputStream.read()` this way:

```
return new ServletInputStream() {
    @Override
    public int read() throws IOException {
        return (int) request.bytesRead();
    }
    ...
}
```

From InputStream.read() Javadoc: `return the next byte of data, or -1 if the end of the stream is reached.`

But it is returning HttpServerRequest.bytesRead(), which is according to Javadoc: `return the total number of bytes read for the body of the request.`

This is causing problems with MTOM attachment processing (through AttachmentInInterceptor).

**Comment by dufoli** [comment]
hmm, do you plan to provide a patch ? or I need to rethink to it and do it ?

**Comment by vipseixas** [comment]
I would submit a patch but you were faster! 🥇 

Thanks!
