### ISSUE TITLE
Java code formatting for contributors

### ISSUE THREAD

**Issue by shumonsharif** [quarkiverse/quarkus-cxf#207]
We should provide a mechanism to automatically (re)format the code during a Maven build, or verify its formatting, so that the project can converge on a consistent code style regardless of contributor preferences, IDE settings, etc.  

[Google Java Format](https://github.com/google/google-java-format) is an option to consider; it has plugins for major IDEs ([IntelliJ IDEA](https://github.com/google/google-java-format#intellij-android-studio-and-other-jetbrains-ides), [Eclipse](https://github.com/google/google-java-format#eclipse)), it provides integrations with tools such as Maven ([fmt-maven-plugin](https://github.com/coveooss/fmt-maven-plugin)), and provides means to run the formatter as [pre-commit hook](https://github.com/a1exsh/google-java-format-git-pre-commit-hook) or when pushing the code to Github with [this Github action](https://github.com/marketplace/actions/google-java-format).

A potential major issue with introducing automated (re)formatting at this stage, is that the existing codebase will be impacted significantly, and the Git history / blame may become quite meaningless.  I can't think of a good solution to this drawback.

@dufoli and @wh81752 Please feel free to share your thoughts on this, and whether it's something we should even entertain.

**Comment by shumonsharif** [comment]
Dug in some more, appears there's already a code formatter defined in the Quarkiverse parent pom:  https://github.com/quarkiverse/quarkiverse-parent/blob/main/pom.xml#L93

**Comment by wh81752** [comment]
@shumonsharif - I'm using this formatter and I believe that format checking is enabled by default. The problem is, IMHO, that the formatter is too tolerant.

**Comment by shumonsharif** [comment]
Well, as long as it's consistent (regardless of whether it's a maven command line build vs an IntelliJ IDEA reformat), I think we should be ok - are you saying it may not be so?

**Comment by wh81752** [comment]
I'm having really trouble about the overall problem. I guess it is this one:

The maven formatter plugin (fmt-maven-plugin) is already present in the project and charged with formatting rules. The rules however are not sharpend enough. It's easy to introduce non-relevant formatting changes which are happily accepted by the rules. Take this for example:

```
            cxfWebServices.produce(new CxfWebServiceBuildItem(cxfBuildTimeConfig.path, sei, soapBinding, wsNamespace,
                    wsName, wrapperClassNames));

vs

            cxfWebServices.produce(
                    new CxfWebServiceBuildItem(
                            cxfBuildTimeConfig.path,
                            sei,
                            soapBinding,
                            wsNamespace,
                            wsName,
                            wrapperClassNames));
```

Both styles are valid from the current formatter's point of view. However, since this change is purly cosmetical, it is not ok to push this change. 

So what would help me? I guess it would be a tool (yet another one) that tells me - watch out, this is just a cosmetical change. Do you really want to commit?

**Comment by shumonsharif** [comment]
I see what you're saying @wh81752 ... this is also the point I was trying to get across in your [PR](https://github.com/quarkiverse/quarkus-cxf/pull/181#issuecomment-831253719).  So there are two separate things happening, as far as I can tell.

- Code reformatting in the IDE (based on a [predefined configuration and set of rules](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#formatting))
- Maven build verification that code is formatted correctly

For some reason, your IntelliJ IDEA is reformatting the code much more so than it should be ... for example when I reformat in my IntelliJ, this line remains the same, whereas it's getting reformatted for you:

```
cxfWebServices.produce(new CxfWebServiceBuildItem(cxfBuildTimeConfig.path, sei, soapBinding, wsNamespace, wsName, wrapperClassNames));
```

The only reason I can attribute is that you have some custom rules in your IDE.  So please try to configure as per https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#formatting and let us know if you're still seeing the block above getting reformatted.

**Comment by wh81752** [comment]
> The only reason I can attribute is that you have some custom rules in your IDE. So please try to configure as per https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#formatting and let us know if you're still seeing the block above getting reformatted.

I configured again as per https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#formatting. Then:

- If I reformat all *.java files then nothing is changed.
- If I change this line

```cxfWebServices.produce(new CxfWebServiceBuildItem(cxfBuildTimeConfig.path, sei, soapBinding, wsNamespace, wsName, wrapperClassNames));
```

to 

```
  cxfWebServices.produce(
          new CxfWebServiceBuildItem(
                  cxfBuildTimeConfig.path, sei, soapBinding, wsNamespace,
                  wsName, wrapperClassNames, implementor));
```

then it stays at it is.  My expectation is that it my changes are "undone".

**Comment by wh81752** [comment]
Since I'm the only format troublemaker here :-) I guess we can close. Otherwise I propose just to add an extra docu section for contributors.

**Comment by shumonsharif** [comment]
Agreed, closing this issue - I'll make sure to look at adding a note for contributors to the docs!!  Thanks @wh81752 for helping validate the various hypothesis ... :-)
