### ISSUE TITLE
Add timeout properties

### ISSUE THREAD

**Issue by floriansiepe** [quarkiverse/quarkus-cxf#211]
# Feature Request

For each endpoint (in client mode) it should be possible to set some properties on the HTTPClientPolicy such as connection and receive timeouts to make this extension even more useful and customizable.

Please also see:

https://cxf.apache.org/docs/client-http-transport-including-ssl-support.html

**Comment by shumonsharif** [comment]
Hi @floriansiepe I haven't tested any of this, but as a workaround, you may be able to do something like the below.

```java
HTTPConduitConfigurer httpConduitConfigurer = new HTTPConduitConfigurer() {
    public void configure(String name, String address, HTTPConduit c) {
        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
             
        httpClientPolicy.setConnectionTimeout(36000);
        httpClientPolicy.setAllowChunking(false);
        httpClientPolicy.setReceiveTimeout(32000);
              
        c.setClient(httpClientPolicy);
    }
}

final Bus bus = BusFactory.getThreadDefaultBus();
bus.setExtension(httpConduitConfigurer, HTTPConduitConfigurer.class);
```

**Comment by floriansiepe** [comment]
Hi @shumonsharif  thank you very much for the code snippet. This just works fine! 
However using properties instead of code would be great

**Comment by dufoli** [comment]
have you try regular http quarkus config ?

quarkus.http.auth.form.timeout
quarkus.http.idle-timeout
quarkus.http.read-timeout

**Comment by shumonsharif** [comment]
> Hi @shumonsharif thank you very much for the code snippet. This just works fine!
> However using properties instead of code would be great

@floriansiepe @dufoli My suggestion would be to keep this extension focused on the core features provided by CXF.  There are potentially hundreds of CXF configurations we can expose through properties ... the extension will become quite difficult to manage if we try to address all of them.

As per the link @floriansiepe shared, this is an advanced configuration use case for CXF that can easily be handled through code.  While managing SLAs in the SOAP world may be a common enough use case, I'm not sure how much value it adds to be configurable through properties - maybe we can leave the issue open to gauge community interest?

**Comment by dufoli** [comment]
Fair point @shumonsharif. So let's close this issue

**Comment by floriansiepe** [comment]
@shumonsharif I see your point. Certainly, making every possible piece of CXF configurable in the extension is not beneficial for anyone. 

But I think some common properties (I would add timeouts to this set) should be configurable. Maybe this could be aligned to the Quarkus REST Client and its exposed properties. So my suggestion would be to keep this issue open to

- Gauge peoples interest in this
- If there is some to define a set of the common propeties, which should be exposed

@dufoli Unfortunately using the regular Quarkus config does not work for my since a have to deal with multiple clients and different settings for each client.

**Comment by dufoli** [comment]
You can provide a pull request to update doc with it
