### ISSUE TITLE
Published documentation does not match latest release

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#220]
Short story: https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/client.html already mentions `@CXFClient` which is not in 0.7.

Details are here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Cannot.20Import.20.40CXFClient

**Comment by dufoli** [comment]
OK so we need a branch stable which contains only last release or a branch develop and master stick to last release. But current build is based on master so easier to do a stable branch and add push to it on release process then update quarkiverse config file

**Comment by shumonsharif** [comment]
I think we should be able to specify multiple wildcard branches as per:
https://docs.antora.org/antora/2.3/playbook/content-branches/#glob-pattern

The branch names can be listed here, so we'll need to submit a PR:
https://github.com/quarkiverse/quarkiverse-docs/blob/main/antora-playbook.yml

Maybe just create a branch named 'v*' for each of our releases, and Antora should generate docs for each version.

**Comment by famod** [comment]
On Zulip tags were mentioned so maybe you don't even need separate branches? I did not yet have a closer look.

**Comment by shumonsharif** [comment]
@dufoli I just created https://github.com/quarkiverse/quarkus-cxf/tree/v0.7 branch from the 0.7 release commit, so should reflect in the docs once PR above is merged.

**Comment by shumonsharif** [comment]
> On Zulip tags were mentioned so maybe you don't even need separate branches? I did not yet have a closer look.

@famod Tags are also an excellent option; that way we're not maintaining unnecessary branches ... only drawback I see with tags is that you can't update docs for the tag post release - we have some breaking non-backward compatible changes coming up for the next release, so I think a branch may be preferred in this scenario, in case the docs need to be improved.  In any case, @dufoli if you have a preference for tags, we can go that way too, just let me know.

**Comment by dufoli** [comment]
branch is better because we can add backport and backport some docs too.
