### ISSUE TITLE
ASM dependency?

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#224]
(Maybe GH discussions should be enabled for this repo, which is now possible as an opt-in for quarkiverse projects.)

I noticed that this extension brings in `org.ow2.asm:asm:jar:9.1:compile`. But I'd assume that all bytecode magic is done during build time instead of runtime?

**Comment by dufoli** [comment]
yes it is done during build time but build time use cxf generation. Not sure it can be removed. We need to test.

**Comment by dufoli** [comment]
so remove asm make native bug.... We have to investiguate but I guess that It is not doable. Anyway, I cleanup pom at the same moment. So maybe I will merge first the cleanup on dep.

**Comment by shumonsharif** [comment]
@dufoli I did not dig in too deep; but I tried the below on a whim, and native is working fine.

```java
@TargetClass(className = "org.apache.cxf.common.util.ASMHelperImpl")
final class Target_org_apache_cxf_common_util_ASMHelperImpl {

    @Substitute
    private Class<?> getASMClassWriterClass() {
        return null;
    }

}
```

**Comment by dufoli** [comment]
@shumonsharif you can commit to branch. Else I do it.

**Comment by shumonsharif** [comment]
Thanks so much @dufoli I will test a little more thoroughly and commit to the branch.

**Comment by shumonsharif** [comment]
Just to note, the latest commit adds an exclusion for `jaxb-runtime` and removes the explicit dependency on `jboss-jaxb-api_2.3_spec` ... as @famod noted in the PR, both of these are provided by `quarkus-jaxb` for which we already had a dependency.
