### ISSUE TITLE
Can't find annotation CXFClient on any version

### ISSUE THREAD

**Issue by PaKu5** [quarkiverse/quarkus-cxf#225]
Hello, 

I try to use the extension as explained in your documentation.

But I have the problem that I cant find/import the annotation CXFClient on any version...

<dependency>
      <groupId>io.quarkiverse.cxf</groupId>
      <artifactId>quarkus-cxf</artifactId>
      <version>0.6</version>
</dependency>

I also tried version 0.5 and 0.4 but no success...

What am I doing wrong?

**Comment by dufoli** [comment]
on top right corner of doc, you can switch branch
please use https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/0.7/index.html
for 0.7
