### ISSUE TITLE
CXFClient missing?

### ISSUE THREAD

**Issue by lthasle** [quarkiverse/quarkus-cxf#233]
Hi!

I am trying to implement a soap client by using quarkus-cxf.
I have added the below included dependency to my pom.
According to the below examples I shall use a an annotation named:

io.quarkiverse.cxf.annotation.CXFClient

I was expecting that that class would be found in the quarkus-cxf, have I misunderstood something?

https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/client.html

https://github.com/quarkiverse/quarkus-cxf/blob/master/integration-tests/src/test/java/io/quarkiverse/it/cxf/ClientGreetingClientTest.java

``
<dependency>
 <groupId>io.quarkiverse.cxf</groupId>
 <artifactId>quarkus-cxf</artifactId>
 <version>0.7</version> 
</dependency>

**Comment by shumonsharif** [comment]
Hi @lthasle This CXFClient feature is currently in master / development branch and will be in the next release.  

In the meantime, you may take a look at:
https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/0.7/client.html

I'm also including an image below that hopefully others can reference if needed, and I'm going to update the README on how to switch documentation versions in quarkiverse-docs.

![quarkiverse-docs-version](https://user-images.githubusercontent.com/13334073/119669482-19640a80-be06-11eb-8184-9f063166276a.jpg)
