### ISSUE TITLE
Client: Should limit generation to only those portTypes that are actually used

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#252]
We generate classes via `cxf-codegen-plugin` from a WSDL file that contains multiple portTypes.
This yields multiple `@WebService` classes.
So far so common.

We only use one of those service interfaces/portTypes but I can see on the console that this extension generates a  QuarkusJaxWsServiceFactoryBean for _every_ found `@WebService` class.

Since Quarkus is all about build-time optimization and generation is expensive, I think it makes a lot of sense to limit this generation to only those portTypes that are actually in use.

**Comment by famod** [comment]
@dufoli @shumonsharif I would like to take a stab at this before the next release is published.

I would try to find via jandex index all `@CXFClient` injections...something like that. WDYT?

**Comment by dufoli** [comment]
hmm, yes you are right ;-). It is a good optimization.

**Comment by shumonsharif** [comment]
@famod Just wanted to clarify one thing, and hope I'm not over thinking the issue ... you'll somehow need to strip out only the `@WebService` classes that are tied to a `@CXFClient` specific endpoint ... but any server endpoint `@WebService` classes that are co-existing and hosted within the same project should still generate the `QuarkusJaxWsServiceFactoryBean`... is my understanding correct?

**Comment by dufoli** [comment]
yes @shumonsharif 
only produce client needed but all server with route must be generated!

**Comment by dufoli** [comment]
I will wait the pPR before releasing 0.9

**Comment by famod** [comment]
@dufoli Ok, but beware that I will have to refactor `QuarkusCxfProcessor.build(...)` quite a bit.

**Comment by famod** [comment]
Got it working! Need to do some polishing and then I'll create a PR (tomorrow or so).

**Comment by famod** [comment]
I just realized that I should better support `Instance<SEI>` as well, working on it...

**Comment by famod** [comment]
Done: #262
