### ISSUE TITLE
Initialisation of endpoints and operations

### ISSUE THREAD

**Issue by tpodg** [quarkiverse/quarkus-cxf#264]
I am trying to get schema validation working but so far without success. During the process I did some debugging and found out that the extension should hand over the implementation class to the cxf:
**CXFHandler**: factory.setServiceClass(seiClass)).

The cxf documentation is as following: 
Specifies the class implementing the service.
Params:
serviceClass – the service's implementaiton class 

So later cxf is using generated interface twice, even when implementation class is expected. I guess the actual implementor (configured in properties) should be used or am I missing something?
It looks like this is also the reason no annotations from implementor are taken over, because only the generated interface (from wsdl) is always processed.

I've tried a quick modification to test my assumption and it should be correct. 

Change of line 116:
`factory.setServiceClass(seiClass);`
to:
`factory.setServiceClass(instanceService.getClass());`

leads to working schema validation if adding the annotation to the implementor class.

**Comment by dufoli** [comment]
thanks? I will merge the fix ;-)

**Comment by tpodg** [comment]
No problem. If the solution is fine with you and nothing breaks, I guess the whole code block could be replaced:
```
Class<?> seiClass = null;
if (servletInfo.getSei() != null) {
    seiClass = loadClass(servletInfo.getSei());
    factory.setServiceClass(instanceService.getClass());
}
if (seiClass == null) {
    LOGGER.warn("sei not found: " + servletInfo.getSei());
}
```
with
`factory.setServiceClass(instanceService.getClass());`

I did not have a look where / how the sei is set in the first place...
