### ISSUE TITLE
document HTTPConduitConfigurer trick

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkus-cxf#274]
idea is to explain how HTTPConduitConfigurer can help to configure authentication...

example:
```
void onStart(@Observes StartupEvent ev) {
     
     HTTPConduitConfigurer httpConduitConfigurer = new HTTPConduitConfigurer() {
         public void configure(String name, String address, HTTPConduit c) {
             AsyncHTTPConduit conduit = (AsyncHTTPConduit)c;
             DefaultHttpAsyncClient defaultHttpAsyncClient;
             defaultHttpAsyncClient = conduit.getHttpAsyncClient();
             defaultHttpAsyncClient.getCredentialsProvider().setCredentials( AuthScope.ANY,
              new NTCredentials( USER,PWD, "", DOM ) );
             conduit.getClient().setAllowChunking( false );
             conduit.getClient().setAutoRedirect( true );
         }
     };

     final Bus bus = BusFactory.getThreadDefaultBus();
     bus.setExtension(httpConduitConfigurer, HTTPConduitConfigurer.class);
 }
```

**Comment by famod** [comment]
FWIW, if you have clients for multiple backends, you'll likely have to use endpoint specific settings.

E.g. we are using this in our "Connector" classes (that are using the `@CXFClient`s) to configure client cert auth:
```java

    @Inject
    @CXFClient
    SomePortType portType;

    @PostConstruct
    void configurePortType() throws NoSuchAlgorithmException, UnrecoverableKeyException, KeyStoreException {
        final var httpConduit = (HTTPConduit) ClientProxy.getClient(portType).getConduit();
        final var tlsClientParameters = Optional.ofNullable(httpConduit.getTlsClientParameters()).orElseGet(TLSClientParameters::new);
        tlsClientParameters.setCertAlias(config.clientCert().keyAlias());
        tlsClientParameters.setKeyManagers(securityStoreProvider.getKeyManagers(config.clientCert()));
        tlsClientParameters.setTrustManagers(securityStoreProvider.getTrustManagers());
        httpConduit.setTlsClientParameters(tlsClientParameters);
    }
```
Note: `securityStoreProvider` is a custom class providing access to out custom key store and trust store.

IIRC, you can also apply configurers to specific clients, but above solution is good enough for us for now.

**Comment by antonwiens** [comment]
> FWIW, if you have clients for multiple backends, you'll likely have to use endpoint specific settings.
> 
> E.g. we are using this in our "Connector" classes (that are using the `@CXFClient`s) to configure client cert auth:
> 
> ```java
>     @Inject
>     @CXFClient
>     SomePortType portType;
> 
>     @PostConstruct
>     void configurePortType() throws NoSuchAlgorithmException, UnrecoverableKeyException, KeyStoreException {
>         final var httpConduit = (HTTPConduit) ClientProxy.getClient(portType).getConduit();
>         final var tlsClientParameters = Optional.ofNullable(httpConduit.getTlsClientParameters()).orElseGet(TLSClientParameters::new);
>         tlsClientParameters.setCertAlias(config.clientCert().keyAlias());
>         tlsClientParameters.setKeyManagers(securityStoreProvider.getKeyManagers(config.clientCert()));
>         tlsClientParameters.setTrustManagers(securityStoreProvider.getTrustManagers());
>         httpConduit.setTlsClientParameters(tlsClientParameters);
>     }
> ```
> 
> Note: `securityStoreProvider` is a custom class providing access to out custom key store and trust store.
> 
> IIRC, you can also apply configurers to specific clients, but above solution is good enough for us for now.

Thanks @famod for the info. Question regarding that: Is a new client created for each injection? I would like to inject the same client class for different endpoints with different conduit configurations and use them in parallel.

**Comment by famod** [comment]
@antonwiens sorry, your question fell off my radar.

> Is a new client created for each injection?

`@CXFClient` beans are `@Dependent` so each injection point should receive another instance and there fore also another conduit.
You should be able to verify easily by printing `System.identityHashCode(conduit)` (or similar).

**Comment by dufoli** [comment]
@famod not sure if it is good to have new instance or share the same one. Share willy reduce memory. But it may have impact.
