### ISSUE TITLE
Locatable is incompatible with types in state XmlSeeAlso ProxyImpl

### ISSUE THREAD

**Issue by grigoni** [quarkiverse/quarkus-cxf#278]
hello

I'm developing an application that uses quarkus, camel and direct Quarkiverse-CXF calls (MTOM enabled)
macOS BigSur, quarkus 2.1.0-Final / quarkus 2.1.1-Final, GraalVM 21.2.0, quarkiverse cxf 0.9

(openjdk build is working as designed)
when building a native image of a CXF application I get following error:

Error: Field com.sun.xml.bind.v2.model.impl.TypeInfoImpl.upstream has declared type com.sun.xml.bind.v2.model.annotation.Locatable which is incompatible with types in state: 1TypeMObject<[0x00001E4B00001E4C:!S:XmlSeeAlso$$ProxyImpl]>
Detailed message:
com.oracle.svm.core.util.UserError$UserException: Field com.sun.xml.bind.v2.model.impl.TypeInfoImpl.upstream has declared type com.sun.xml.bind.v2.model.annotation.Locatable which is incompatible with types in state: 1TypeMObject<[0x00001E4B00001E4C:!S:XmlSeeAlso$$ProxyImpl]>
Detailed message:
                at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
                at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
230.012,11 ms,  3,75 GB
                at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:764)
                at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
                at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
                at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
                at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
                at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
                at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Field com.sun.xml.bind.v2.model.impl.TypeInfoImpl.upstream has declared type com.sun.xml.bind.v2.model.annotation.Locatable which is incompatible with types in state: 1TypeMObject<[0x00001E4B00001E4C:!S:XmlSeeAlso$$ProxyImpl]>
Detailed message:
                at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
                at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:761)
                ... 6 more

I've tried also the substitution workaround without success: https://github.com/oracle/graal/issues/2720

@TargetClass(className = "com.sun.xml.bind.v2.model.impl.TypeInfoImpl", onlyWith = Target_com_sun_xml_bind_v2_model_impl_TypeInfoImpl.Selector.class)
@Substitute
final class Target_com_sun_xml_bind_v2_model_impl_TypeInfoImpl {        
   
    static final class Selector implements BooleanSupplier {

        @Override
        public boolean getAsBoolean() {
            try {
                Class.forName("com.sun.xml.bind.v2.model.impl.TypeInfoImpl");
                return true;
            } catch (Exception e) {
                return false;
            }
        }
    }
}

did I miss something or is this related to https://github.com/quarkiverse/quarkus-cxf/issues/8 ?

best regards

**Comment by dufoli** [comment]
is it related to native or jvm ?

**Comment by dufoli** [comment]
source of the file : 
https://github.com/javaee/jaxb-v2/blob/master/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/v2/model/impl/TypeInfoImpl.java

the issue here is that unmarshaling the message lead to issue because the class which need to be used to map the xml data do not fit. It is really a core issue. Anyway it seems to be linked to XMLSeeAlso.

To handle marshaling of object with XmlSeeAlso I have added a ReflectiveClassBuildItem on class name value of XMLSeeAlson annotation.
I do not know how XMLSeeAlson internaly is mapped but the code seems to talked about proxy.
So, maybe the solution is just to produce NativeImageProxyDefinitionBuildItem.

I see that in https://github.com/javaee/jaxb-v2/blob/master/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/v2/model/annotation/LocatableAnnotation.java
they use proxy so I think we have a something to handle proxy of locatable...

**Comment by dufoli** [comment]
https://github.com/javaee/jaxb-v2/search?q=newProxyInstance&type=

A search on proxy on jaxb ri to handle on cxf.

**Comment by dufoli** [comment]
hmm jaxb processor already handle the locatable proxy build item for all jaxb annotation:
https://github.com/quarkusio/quarkus/blob/2f33d20cdae18c29f6c1f84f8ba62eaccdf0ad72/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L173

I found some missing proxy, but not sure it is related to our issue : 
com.sun.tools.xjc.generator.annotation.spec.XmlElementRefWriter
com.sun.tools.xjc.generator.annotation.spec.XmlAnyAttributeWriter
com.sun.tools.xjc.generator.annotation.spec.XmlEnumValueWriter
com.sun.tools.xjc.generator.annotation.spec.XmlEnumWriter
com.sun.tools.xjc.generator.annotation.spec.XmlJavaTypeAdapterWriter
com.sun.tools.xjc.generator.annotation.spec.XmlMimeTypeWriter
com.sun.tools.xjc.generator.annotation.spec.XmlRootElementWriter
com.sun.tools.xjc.generator.annotation.spec.XmlSeeAlsoWriter
com.sun.tools.xjc.generator.annotation.spec.XmlTypeWriter
com.sun.tools.xjc.generator.annotation.spec.XmlAccessorTypeWriter
com.sun.tools.xjc.generator.annotation.spec.XmlElementDeclWriter
com.sun.tools.xjc.generator.annotation.spec.XmlRegistryWriter
com.sun.tools.xjc.generator.annotation.spec.XmlSchemaWriter

import com.sun.xml.bind.v2.schemagen.xmlschema.Any;
import com.sun.xml.bind.v2.schemagen.xmlschema.AttrDecls;
import com.sun.xml.bind.v2.schemagen.xmlschema.ComplexExtension;
import com.sun.xml.bind.v2.schemagen.xmlschema.ComplexType;
import com.sun.xml.bind.v2.schemagen.xmlschema.ComplexTypeHost;
import com.sun.xml.bind.v2.schemagen.xmlschema.ExplicitGroup;
import com.sun.xml.bind.v2.schemagen.xmlschema.Import;
import com.sun.xml.bind.v2.schemagen.xmlschema.List;
import com.sun.xml.bind.v2.schemagen.xmlschema.LocalAttribute;
import com.sun.xml.bind.v2.schemagen.xmlschema.LocalElement;
import com.sun.xml.bind.v2.schemagen.xmlschema.Schema;
import com.sun.xml.bind.v2.schemagen.xmlschema.SimpleExtension;
import com.sun.xml.bind.v2.schemagen.xmlschema.SimpleRestrictionModel;
import com.sun.xml.bind.v2.schemagen.xmlschema.SimpleType;
import com.sun.xml.bind.v2.schemagen.xmlschema.SimpleTypeHost;
import com.sun.xml.bind.v2.schemagen.xmlschema.TopLevelAttribute;
import com.sun.xml.bind.v2.schemagen.xmlschema.TopLevelElement;
import com.sun.xml.bind.v2.schemagen.xmlschema.TypeHost;
import com.sun.xml.bind.v2.schemagen.xmlschema.ContentModelContainer;
import com.sun.xml.bind.v2.schemagen.xmlschema.TypeDefParticle;
import com.sun.xml.bind.v2.schemagen.xmlschema.AttributeType;
import com.sun.xml.bind.v2.schemagen.episode.Bindings;

**Comment by dufoli** [comment]
to analyse deeper:
https://github.com/javaee/jaxb-v2/blob/45360860439ab14bccf020036306b69797ee1a9e/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/v2/model/impl/ClassInfoImpl.java

https://github.com/javaee/jaxb-v2/blob/45360860439ab14bccf020036306b69797ee1a9e/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/v2/model/impl/ElementInfoImpl.java

https://github.com/javaee/jaxb-v2/blob/45360860439ab14bccf020036306b69797ee1a9e/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/v2/model/impl/EnumLeafInfoImpl.java

https://github.com/javaee/jaxb-v2/blob/45360860439ab14bccf020036306b69797ee1a9e/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/v2/model/impl/ArrayInfoImpl.java


it is declared class witch extends TypeInfoImpl and there is some reflection in it...

**Comment by dufoli** [comment]
I just discover this PR : https://github.com/oracle/graal/commit/d72e67beff8bb9ebcda8ce5e40b8f552bb7eabf6#diff-5731194b93b5585f9ee61e07a1c72af18fd64a3a47dafcacb0fe155555b287ae
maybe it will fix it.

**Comment by grigoni** [comment]
hello
thanks for investigating

it is happening on linux (ubuntu VM) and macOS Big Sur9

**Comment by grigoni** [comment]
if there is something I can try on my side let me know, I'll be glad to help and make the issue more clear
(I am no expert in GraalVM, still confused... :-) )

**Comment by dufoli** [comment]
OK it come from an exception in https://github.com/javaee/jaxb-v2/blob/45360860439ab14bccf020036306b69797ee1a9e/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/v2/model/annotation/LocatableAnnotation.java

So it is not wrapped.
Few possibilities : 
- wrong classloader
- 
- class not found in class loader.
- annotationType do not return type 
- LocatableAnnotation

**Comment by dufoli** [comment]
Idea to test, substitution to add log in this function...

**Comment by dufoli** [comment]
@grigoni can you test with substitution:
```

@TargetClass(className = "com.sun.xml.bind.v2.model.annotation.LocatableAnnotation")
final class Target_com_sun_xml_bind_v2_model_annotation_LocatableAnnotation implements InvocationHandler, Locatable, Location {

    //@Alias
    //private static Logger LOG = null;

    @Alias
    Target_com_sun_xml_bind_v2_model_annotation_LocatableAnnotation(Annotation core, Locatable upstream) {
    }

    @Substitute()
    public static <A extends Annotation> A create(A annotation, Locatable parentSourcePos) {
        Logger LOG = LogUtils.getL7dLogger(com.sun.xml.bind.v2.model.annotation.LocatableAnnotation.class);
        LOG.info("LocatableAnnotation.create");
        if (annotation == null)
            return null;
        Class<? extends Annotation> type = annotation.annotationType();
        LOG.info("LocatableAnnotation.create type:" + type);
        ClassLoader cl = null;
        Class c = Target_com_sun_xml_bind_v2_model_annotation_LocatableAnnotation.class;
        if (System.getSecurityManager() == null) {
            cl = c.getClassLoader();
        } else {
            cl = (ClassLoader) java.security.AccessController.doPrivileged(
                    new java.security.PrivilegedAction() {
                        public java.lang.Object run() {
                            return c.getClassLoader();
                        }
                    });
        }
        try {
            LOG.info("LocatableAnnotation.create before reflection");
            Class loadableT = Class.forName(type.getName(), false, cl);
            LOG.info("LocatableAnnotation.create after reflection");
            if (loadableT != type) {
                LOG.info("LocatableAnnotation.create failed reflection");
                return annotation; // annotation type not loadable from this class loader
            }

            return (A) Proxy.newProxyInstance(cl,
                    new Class[] { type, Locatable.class },
                    new Target_com_sun_xml_bind_v2_model_annotation_LocatableAnnotation(annotation, parentSourcePos));
        } catch (ClassNotFoundException e) {
            // annotation not loadable
            LOG.info("LocatableAnnotation.create annotation not loadable" + e.toString());
            return annotation;
        } catch (IllegalArgumentException e) {
            // Proxy.newProxyInstance throws this if it cannot resolve this annotation
            // in this classloader
            LOG.info("LocatableAnnotation.create cannot resolve this annotation" + e.toString());
            return annotation;
        }

    }

    @Alias
    private static final Map<Class, Quick> quicks = new HashMap<Class, Quick>();

    @Alias
    public com.sun.jdi.Location location() {
        return null;
    }

    @Alias
    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
        return null;
    }
}
```

**Comment by grigoni** [comment]
thanks a lot, I tried by adding following imports (please check):

import com.oracle.svm.core.annotate.Alias;
import com.oracle.svm.core.annotate.Substitute;
import com.oracle.svm.core.annotate.TargetClass;
import com.sun.xml.bind.v2.model.annotation.Locatable;
import com.sun.xml.bind.v2.model.annotation.Quick;
import com.sun.xml.bind.v2.runtime.Location;
import org.apache.cxf.common.logging.LogUtils;

import java.lang.annotation.Annotation;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

but ice is complaining the class is missing method getUpstream implementation (as per interface import com.sun.xml.bind.v2.model.annotation.Locatable;)

**Comment by grigoni** [comment]
thanks a lot for rechecking, here the result when building:
Error: The value assigned to a static @Alias field is ignored unless @RecomputeFieldValue with kind=FromAlias is used: com.zurich.ch.ecm.soms.cxf.Target_com_sun_xml_bind_v2_model_annotation_LocatableAnnotation.quicks
# Printing build artifacts to: /Users/gianandrea.rigoni/IdeaProjects/Galapagos/SOMS-C18E-quarkus/target/soms-c18e-quarkus-0.2.0-SNAPSHOT-native-image-source-jar/soms-c18e-quarkus-0.2.0-SNAPSHOT-runner.build_artifacts.txt
com.oracle.svm.core.util.UserError$UserException: The value assigned to a static @Alias field is ignored unless @RecomputeFieldValue with kind=FromAlias is used: com.zurich.ch.ecm.soms.cxf.Target_com_sun_xml_bind_v2_model_annotation_LocatableAnnotation.quicks
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:450)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:344)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:310)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:936)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:868)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
Error: Image build request failed with exit status 1

**Comment by grigoni** [comment]
did following changes:
    //removed final
    @Alias
    // added following info when building
    @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.FromAlias)
    private static Map<Class, Quick> quicks = new HashMap<Class, Quick>();

following error on build:

Error: Field com.sun.xml.bind.v2.model.impl.TypeInfoImpl.upstream has declared type com.sun.xml.bind.v2.model.annotation.Locatable which is incompatible with types in state: 1TypeMObject<[0x00001E8000001E81:!S:XmlSeeAlso$$ProxyImpl]>
Detailed message:
com.oracle.svm.core.util.UserError$UserException: Field com.sun.xml.bind.v2.model.impl.TypeInfoImpl.upstream has declared type com.sun.xml.bind.v2.model.annotation.Locatable which is incompatible with types in state: 1TypeMObject<[0x00001E8000001E81:!S:XmlSeeAlso$$ProxyImpl]>
Detailed message:
[soms-c18e-quarkus-0.2.0-SNAPSHOT-runner:11984]      [total]: 265.943,40 ms,  4,29 GB
	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
# Printing build artifacts to: /Users/gianandrea.rigoni/IdeaProjects/Galapagos/SOMS-C18E-quarkus/target/soms-c18e-quarkus-0.2.0-SNAPSHOT-native-image-source-jar/soms-c18e-quarkus-0.2.0-SNAPSHOT-runner.build_artifacts.txt
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:764)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Field com.sun.xml.bind.v2.model.impl.TypeInfoImpl.upstream has declared type com.sun.xml.bind.v2.model.annotation.Locatable which is incompatible with types in state: 1TypeMObject<[0x00001E8000001E81:!S:XmlSeeAlso$$ProxyImpl]>
Detailed message:
	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:761)
	... 6 more
Error: Image build request failed with exit status 1

**Comment by dufoli** [comment]
Hmm quick is not needed. So we can just remove the field. @grigoni

**Comment by grigoni** [comment]
unfortunately this is not changing the result

**Comment by dufoli** [comment]
bad news. Ok so it is coming from build. So I guess I can not log with that.
https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/annotation/AnnotationSubstitutionType.java

is the graalvm class which wrap annotation. The famous $$ProxyImpl come from that. a method getOriginal() get the original annotation. It is maybe a lack of getOriginal() (or AnnotationSubstitutionProcessor.resolve() ) somewhere...
because wrapping type must never been used directly...

Anyway, what I see is that, If I have a test which not worked, I can debug in jvm mode with breakpoint on 
https://github.com/eclipse-ee4j/jaxb-ri/blob/002aa3d6738622110ebcb6e1dc0fb99fe07faafd/jaxb-ri/runtime/impl/src/main/java/org/glassfish/jaxb/runtime/v2/model/impl/ModelBuilder.java#L244
 to check what is type and origine of upstream  parameter

**Comment by grigoni** [comment]
hello, I'm trying to create a reproducible test, until now I only get working stuff and not same error (murphy's law...)

**Comment by dufoli** [comment]
I think you need fruit class ans inherited class banana. Then xmlseealso on parent class to point to child.
Then used it in param or return of method.
Is it the right use case?

**Comment by dufoli** [comment]
can still not reproduce ?
what is your jdk version ?

**Comment by argenstijn** [comment]
Hi,

I can reproduce it again with my simple test project.

quarkus: 2.1.2.Final
linux graalvm: 21.2.0
JDK version : 11

And it works again when i have the following replacement:

@TargetClass(className = "com.sun.xml.bind.v2.model.impl.TypeInfoImpl", onlyWith = Target_com_sun_xml_bind_v2_model_impl_TypeInfoImpl.Selector.class)
@substitute
final class Target_com_sun_xml_bind_v2_model_impl_TypeInfoImpl {

static final class Selector implements BooleanSupplier {

    @Override
    public boolean getAsBoolean() {
        try {
            Class.forName("com.sun.xml.bind.v2.model.impl.TypeInfoImpl");
            return true;
        } catch (Exception e) {
            return false;
        }
    }
}

}

See https://github.com/oracle/graal/issues/2720

**Comment by argenstijn** [comment]
see oracle/graal#2720 for the zip where you can reproduce the error.

**Comment by grigoni** [comment]
I was busy with other projects sorry, I'm still trying the reproducer, unfortunately my efforts didn't produced a breaking build also when I add to new project the original wsdl that I cannot share

**Comment by grigoni** [comment]
> can still not reproduce ? not yet :-(
> what is your jdk version ? graalvm (jdk 11) 21.2.0 on macOS and linux (vm)

**Comment by grigoni** [comment]
this is great news, thanks for finding and solving the issue!

**Comment by dufoli** [comment]
I help to understand issue but fixing was done by graal team ;-) it was too complexe for me.

**Comment by grigoni** [comment]
I'm very happy and looking forward to make our app that uses CXF completely native

**Comment by grigoni** [comment]
native compilation completes when using 21.3.0
thanks a lot!
