### ISSUE TITLE
Managing x-forwarded headers

### ISSUE THREAD

**Issue by demeureg** [quarkiverse/quarkus-cxf#311]
Hello, 

First of all, thanks for your work, this extension is really making the job.

Is there a way to manage x-forwarded-headers? If not, can I have advice implementing this feature? 

CXF servlet manage them using a flag, authorizing application to be deployed behind an API gateway, and looks like Quarkus has already the capability to do this (https://quarkus.io/guides/http-reference#reverse-proxy).

Regards, 

Guillaume Demeure

**Comment by shumonsharif** [comment]
Hi Guillaume, I just wanted to make sure I got your question ... you are looking to be able to turn on [this flag](https://github.com/apache/cxf/blob/cxf-3.4.5/rt/transports/http/src/main/java/org/apache/cxf/transport/servlet/AbstractHTTPServlet.java#L125) or achieve the equivalent in the extension?

The extension currently does not support it, but in case you'd like to take it on, PRs are very welcome.  Advice for now would be to take a look at the `VertxServletConfig` and `CxfHandler` classes.

**Comment by demeureg** [comment]
Hello and thanks for your reply. Yes, I would have the same behaviour with this extension.

Some client require to have the right path to the endpoint. If not, these client cannot reach the service because we cannot define service URL.

When I use the CXF servlet, if headers are present, the service URL is correct (example below):
```
<wsdl:service name="MyServiceEndpointService">
<wsdl:port binding="tns:MyServiceEndpointServiceSoapBinding" name="MyServiceEndpointPort">
<soap:address location="http://api.example.com/prefix/services/service"/>
</wsdl:port>
</wsdl:service>
```

I though it was enough to add these configuration into Quarkus to deal with this issue but it seems that it has no effect on this extension: 
```
quarkus.http.proxy.allow-forwarded=true
quarkus.http.proxy.enable-forwarded-host=true
quarkus.http.proxy.enable-forwarded-prefix=true
quarkus.http.proxy.proxy-address-forwarding=true
```

Regards

**Comment by shumonsharif** [comment]
Hi Guillaume, apologies but I am a little unsure as to the end goal; are you just trying to control the service URL in the WSDL because you are behind a reverse proxy?  That's the impression I'm getting from your example; if that is the case, have you considered using the `published-endpoint-url` property?

```java
quarkus.cxf.endpoint."/fruit".published-endpoint-url=https://something.com:9291/cxf/tootyfruity
```

```xml
<wsdl:service name="FruitWebServiceImplService">
    <wsdl:port binding="tns:FruitWebServiceImplServiceSoapBinding" name="FruitWebServiceImplPort">
        <soap:address location="https://something.com:9291/cxf/tootyfruity"/>
    </wsdl:port>
</wsdl:service>
```

I will take a look at this issue a little deeper later this week!

**Comment by shumonsharif** [comment]
I think I got it working, but need your help testing as I don't have a proper reverse proxy setup.  

Can you check out the [x-forwarded-headers](https://github.com/quarkiverse/quarkus-cxf/tree/x-forwarded-headers) branch and let us know your thoughts?

**Comment by demeureg** [comment]
Hello @shumonsharif,

i will try this today, the implementation sounds great. 

The published endpoint url cannot be used in this use case because we have multiple proxies with differents URLs so WSDL has to be dynamic (for memories, the client cannot modify the service url 😭 ).

Thanks for your time and explanation.

Regards

**Comment by shumonsharif** [comment]
Thanks so much Guillaume, for your help with describing the use case, and the testing support.

We need to add some unit tests and though it's a relatively low impact change, it would be helpful to get a quick code review with @dufoli and/or @famod (giving you both a heads up) before we merge into master.

Guillame, you're most welcome to contribute / submit a PR for unit tests (let me know if so), otherwise I hope to wrap it up this weekend!

**Comment by demeureg** [comment]
Hello,

Sorry the late response, I was working on test coverage this weekend, but i didnt achieve to make it work.

Thanks you for your time on this feature, it will be useful for our usage.

Regards
