### ISSUE TITLE
Invalid URL generated in XML "import" 

### ISSUE THREAD

**Issue by davorl-cedacri** [quarkiverse/quarkus-cxf#323]
Starting from 0.10.0, when publishing a webservice with the _targetNamespace_ attribute of the `@WebService` annotation, XML schema is not embedded within the WSDL but linked via _import_; the problem is that the _import_ statement contains an invalid URL, such as this one:
`<wsdl:import location="http://localhost:8080/soap/test?wsdl?wsdl=TestService.wsdl" namespace="mynamespace"> </wsdl:import>`

Workarounds:
- Don't specify a targetNamespace (but some services may need it);
- Include a pre-generated WSDL (but the WSDL file would need to be manually edited whenever a field is added to the model, for example);
- Specify a _quarkus.cxf.endpoint.key.published-endpoint-url_ property (not optimal because different environments would need different configurations; in most use cases auto-detection of the published URL is desirable).

Example mini-project to reproduce: [cxftest.zip](https://github.com/quarkiverse/quarkus-cxf/files/7642790/cxftest.zip)

**Comment by shumonsharif** [comment]
Hi @davorl-cedacri Thanks for the issue!  I believe the behavior you're seeing is related to:

https://cxf.apache.org/faq.html#FAQ-Thegeneratedwsdl(GETrequestonthe?wsdladdress)doesn'tcontainthemessages,types,portType,etc...WhatdidIdowrong?

Your best option is to set the targetNamespace to the same value in both the service interface **and** service implementation `@WebService` annotations.  I think that's the simplest workaround for you.

However, will keep this open to dig in a little for the invalid URL - that shouldn't be happening either.

**Comment by davorl-cedacri** [comment]
Thank you @shumonsharif!
In my case changing the targetNamespace is not a viable option, as I'm porting an existing application from Thorntail to Quarkus. I'll use the "published-endpoint-url" workaround until a solution to the invalid URL issue is found.

**Comment by shumonsharif** [comment]
Hey @davorl-cedacri I did not follow why porting from Thorntail to Quarkus would matter -- the suggestion was not to change your targetNamespace value; it was to set the same value in BOTH the interface and implementation class ... I believe that should not impact the actual API you are exposing?  Not entirely sure though, will need to dig in further.

**Comment by davorl-cedacri** [comment]
Ooops, I misunderstood that FAQ entry, sorry.
m (_ _) m
Setting both the interface and the implementation to the same targetNamespace works perfectly, thank you!
