### ISSUE TITLE
WSS4J dependencies

### ISSUE THREAD

**Issue by EmreKp** [quarkiverse/quarkus-cxf#340]
Hello,

In order to use `wss4j`, should we have only add a dependency like `cxf-rt-ws-security`? Is there any other way to use it, or is this the easiest way? If this is only way, documentation also should be updated.

Thanks

**Comment by shumonsharif** [comment]
Hi @EmreKp One would only need to add the `cxf-rt-ws-security` dependency for CXF WS-Security support.  The `wss4j` dependencies should get pulled in automatically, given they are [compile time](https://mvnrepository.com/artifact/org.apache.cxf/cxf-rt-ws-security/3.5.0) dependencies.

There are examples of how to leverage the CXF WS-Security framework here:
https://github.com/apache/cxf/tree/3.5.x-fixes/distribution/src/main/release/samples/ws_security

Please feel free to submit a PR with the documentation improvement - spelling out the `cxf-rt-ws-security` dependency may possibly be helpful for others.

**Comment by shumonsharif** [comment]
Something to note is that only the programmatic WSS4JInterceptors are currently supported.  Actions like Timestamp, UsernameToken, Signature, Encryption, etc., can be applied to the interceptors by passing the appropriate configuration properties.

**Comment by EmreKp** [comment]
Thanks for reply, then I will submit PR with updated documentation.
