### ISSUE TITLE
Native build using @RolesAllowed, quarkus-security and quarkus-cxf

### ISSUE THREAD

**Issue by odellamaggiore** [quarkiverse/quarkus-cxf#346]
Given a simple app (built from quarkus-getting started) using : 
- quarkus-cxf
- quarkus-security
- @RolesAllowed annotation on a soap endpoint

Soap Endpoint: 
```
@WebService(endpointInterface = "org.acme.getting.started.GreetingSoap")
@RolesAllowed("SpecialRole")
public class GreetingSoapResource implements GreetingSoap {

    @Override
    public String sayHello(String name) {
        return "Hello " + name;
    }
}
```

Dependencies:
```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-resteasy</artifactId>
</dependency>
<dependency>
  <groupId>io.quarkiverse.cxf</groupId>
  <artifactId>quarkus-cxf</artifactId>
  <version>0.12.0</version>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-security</artifactId>
</dependency>
```

In native mode, the application fails to start : 

```
2022-01-24 10:51:59,123 INFO  [org.apa.cxf.wsd.ser.fac.ReflectionServiceFactoryBean] (main) Creating Service {http://started.getting.acme.org/}GreetingSoapResource_SubclassService from class org.acme.getting.started.GreetingSoap
2022-01-24 10:51:59,129 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NoSuchMethodException: org.acme.getting.started.GreetingSoapResource_Subclass.sayHello(java.lang.String)
        at java.lang.Class.getMethod(DynamicHub.java:1150)
        at org.apache.cxf.jaxws.JAXWSMethodDispatcher.getImplementationMethod(JAXWSMethodDispatcher.java:89)
```
If we remove the @RolesAllowed annotation, or the quarkus-security import, it works fine.
This issue appends only in native mode.

Example project to reproduce : 
[cxf-rolesallowed-issue.zip](https://github.com/quarkiverse/quarkus-cxf/files/7925067/cxf-rolesallowed-issue.zip)

**Comment by shumonsharif** [comment]
Hi @odellamaggiore A couple questions for you.

1. Does **@RolesAllowed** work as it should in JVM mode?  I mean besides just starting up cleanly?  We've had some testing done in the past with https://github.com/quarkiverse/quarkus-cxf/issues/109, so just linking that here for reference.
2. You imported quarkus-security and not an actual security extension, so I'm left wondering if there's any difference in behavior with an actual security extension?  Maybe 'quarkus-elytron-security-properties-file' is a good option to test with?

I don't recall seeing the GreetingSoapResource_**_SubclassService_** suffix in the log statements in the past.  I believe that's where we'd need to start looking at for this issue, as I'm not sure where **_Subclass** in the name is getting introduced.  I'm believe that's likely not happening in this extension or in CXF, but will need to dig in further.

**Comment by odellamaggiore** [comment]
Hi @shumonsharif, thanks for your feedback. Here are my answers:

1. Yes, in JVM mode the @RolesAllowed works fine.

2. You're right. In my real project I use the quarkus-elytron-security extension and it brings quarkus-security as a transitive dependency. But I did the job to isolate each transitive dependency to identify the one which create the issue and it is quarkus-security. So I just included this one in the sample.

**Comment by shumonsharif** [comment]
Hi @odellamaggiore It appears the autogenerated `org.acme.getting.started.GreetingSoapImpl_Subclass` type is getting stripped from the native image.  

It may be a while before I can dedicate some solid blocks of time to investigate (this is not going to be an easy one), but I wanted to share a simple workaround you can try, in case it helps you.

Introduce a `src/main/resources/reflection-config.json` file containing:

```json
[
  {
    "name" : "org.acme.getting.started.GreetingSoapImpl_Subclass",
    "allDeclaredFields":true,
    "queryAllDeclaredMethods":true,
    "queryAllPublicMethods":true
  }
]
```

Then add the following to your native profile in `pom.xml`:

```xml
<quarkus.native.additional-build-args>-H:ReflectionConfigurationFiles=reflection-config.json</quarkus.native.additional-build-args>
```
This will let you execute the native image successfully.

**Comment by shumonsharif** [comment]
I believe this is most likely the the root cause for this issue:  https://github.com/quarkusio/quarkus/issues/7507

**Comment by odellamaggiore** [comment]
@shumonsharif thanks for the fix ! Issue solved for me.
