### ISSUE TITLE
CXF WS-Security native mode support

### ISSUE THREAD

**Issue by wanderingfella** [quarkiverse/quarkus-cxf#354]
Hi,

I am having an issue using ws security in native mode.
I am using 
`'io.quarkiverse.cxf:quarkus-cxf:0.13.0'`
and also added
`'org.apache.cxf:cxf-rt-ws-security:3.4.4'`
I also had to add 
`com.sun.xml.messaging.saaj:saaj-impl:1.5.3`

I think to make it work in JVM mode.

It works fine in JVM mode, but having an issue when running it in native mode.

The top of the stack trace is below

`Caused by: org.apache.cxf.binding.soap.SoapFault: Problem writing SAAJ model to stream: Unable to create message factory for SOAP: Unable to create SAAJ meta-factory: Provider com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl not found\n\tat org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor.handleMessage(SAAJOutInterceptor.java:140)\n\tat org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor.handleMessage(WSS4JOutInterceptor.java:102)\n\tat org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor.handleMessage(WSS4JOutInterceptor.java:58`

I think as it's not picking up META-INF/services inside the saaj impl jar.

Which seems to define com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl as being the factory impl.

In native mode it seems to be looking for com.sun.xml.**internal.**messaging.saaj.soap.SAAJMetaFactoryImpl.

Not really sure how to work around this, it seems like I need to register the saaj impl jar for reflection and the META-INF/service.
I hope that makes sense, any suggestions appreciated.

**Comment by shumonsharif** [comment]
> I am having an issue using ws security in native mode. I am using `'io.quarkiverse.cxf:quarkus-cxf:0.13.0'` and also added `'org.apache.cxf:cxf-rt-ws-security:3.4.4'` I also had to add `com.sun.xml.messaging.saaj:saaj-impl:1.5.3`
> 
> I think to make it work in JVM mode.

Hi @wanderingfella The SAAJ (SOAP with Attachments API for Java) - as the name indicates - is used for attachments and may possibly not be required for WS-Security.  If it is indeed required, then the `cxf-rt-ws-security` dependency I think should pull it in.

> In native mode it seems to be looking for com.sun.xml.**internal.**messaging.saaj.soap.SAAJMetaFactoryImpl.
> 
> Not really sure how to work around this, it seems like I need to register the saaj impl jar for reflection and the META-INF/service. I hope that makes sense, any suggestions appreciated.

My guess is that the issue you are seeing may be due to a dependency conflict.  You are using the wrong version of `cxf-rt-ws-security`.  It should be 3.5.0, so that it matches with the version the quarkus-cxf extension is using.  Are you able to share the output of `mvn dependency:tree -Dverbose` ?

**Comment by wanderingfella** [comment]
Hi @shumonsharif .

Thanks for your suggestions.
I have removed 
`com.sun.xml.messaging.saaj:saaj-impl:1.5.3`
and changed to
`org.apache.cxf:cxf-rt-ws-security:3.5.0`

I now get the error in JVM mode

`org.apache.cxf.binding.soap.SoapFault: Problem writing SAAJ model to stream: Unable to create message factory for SOAP: Unable to create SAAJ meta-factory: Provider com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl not found`

Which curiously is the same error I get in native mode, with 
'com.sun.xml.messaging.saaj:saaj-impl:1.5.3' included.

It definitely seems to me adding that library fixes it in JVM mode, but it probably can't be found in native mode.

I will do some more digging around those dependencies from a wt security perspective, and try to get the gradle depenency tree.

**Comment by wanderingfella** [comment]
[dependencies.txt](https://github.com/quarkiverse/quarkus-cxf/files/7976843/dependencies.txt)
I have attached the gradle dependencies.
I am currently on version 1.13.7.Final of Quarkus. I appreciate that's not the latest, but had trouble trying to upgrade, so I am hoping that's not the issue.

@shumonsharif  thanks again for your time.

**Comment by wanderingfella** [comment]
I can't see where a saaj sun implementation is being brough in my CXF.
When running in JVM mode, without saaj as an added dependency, it seems to be falling over here.

`Caused by: javax.xml.soap.SOAPException: Unable to create message factory for SOAP: Unable to create SAAJ meta-factory: Provider com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl not found
	at javax.xml.soap.MessageFactory.newInstance(MessageFactory.java:90)
	at org.apache.cxf.binding.soap.saaj.SAAJFactoryResolver.createMessageFactory(SAAJFactoryResolver.java:56)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor.getFactory(SAAJOutInterceptor.java:87)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor.handleMessage(SAAJOutInterceptor.java:123)
	... 21 more`

**Comment by shumonsharif** [comment]
Hi @wanderingfella Are you able to provide a reproducer with a minimal set of dependencies?  Or confirm whether the below configuration looks right - I can try to put one together.  

- JDK version 11
- Quarkus 1.13.7.Final
- Quarkus-CXF 0.13.0

However, I will caution that you have a set of of old/new and conflicting dependencies - a much better approach would be to do a clean upgrade - the Quarkus [migration guides](https://github.com/quarkusio/quarkus/wiki/Migration-Guides) may be helpful for you, just wanted to share the link in case you haven't seen those.

**Comment by wanderingfella** [comment]
Hi @shumonsharif  that looks right, I have just upgraded to quarkus 2.0.0, and look to be getting the same issue.
I am also going to try 2.6.3.Final.

It might take me a bit of time to get a reproducer together :(

I am also using this git plugin.

https://github.com/bjornvester/wsdl2java-gradle-plugin

This brings in these dependencies, that might be problematic, but not sure yet.

`jakarta.xml.ws:jakarta.xml.ws-api:2.3.3
jakarta.jws:jakarta.jws-api:1.1.1`

**Comment by shumonsharif** [comment]
Hi @wanderingfella I attempted to put together a simple Gradle based reproducer [ws-security.zip](https://github.com/quarkiverse/quarkus-cxf/files/7990388/ws-security.zip); WS-Security appears to work as expected in native mode. I did need to add the `saaj-impl` dependency as you had suggested.  You'll notice some auto-generated and custom files under `src/main/resources/META-INF/native-image` that should provide what's needed for native mode execution.

You can use the following to test against the native executable. 

```bash
curl -X POST "http://localhost:8080/soap/fruit" \
 -H 'Content-Type: text/xml' \
 -H 'SOAPAction:' \
 -d '
<soapenv:Envelope xmlns:cxf="http://cxf.example.org/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" 
            xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <wsse:UsernameToken>
                <wsse:Username>joe</wsse:Username>
                <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">wss4j</wsse:Password>
            </wsse:UsernameToken>
        </wsse:Security>
   </soapenv:Header>
   <soapenv:Body>
      <cxf:add>
         <arg0>
            <description>Tropical Fruit</description>
            <name>Papaya</name>
         </arg0>
      </cxf:add>
   </soapenv:Body>
</soapenv:Envelope>'
```

Unfortunately as far as the WS-Security dependencies go, the sheer volume of them will make it difficult to integrate native support for, in this extension ... I'm also not convinced this extension would be the right place to provide native support for WS-Security integration, but will give it some further thought.  Let me know if any questions!

**Comment by shumonsharif** [comment]
Hi @wanderingfella Here's an updated [ws-security.zip](https://github.com/quarkiverse/quarkus-cxf/files/8010782/ws-security.zip) Gradle reproducer with reworked and more 'appropriate' dependencies, such as the Jakarta web services implementation.  After sleeping on it for a few days, I think the extension should support WS-Security in native mode, so I'm going to look into getting that integrated.  Hoping you are able to help test once it's available.

**Comment by wanderingfella** [comment]
hi @shumonsharif 
Apologies, I have been away (covid) .
Thanks for looking into this, I will take a look at your suggestions and feedback.

I am also more than happy to test any new integrations.

**Comment by wanderingfella** [comment]
Just thought i would add, I am using an out interceptor (WSS4JOutInterceptor) and using it for a generated client.
I am still working through, adding the things I need from the example provided.

Currently, at runtime, I am getting this issue.
`<html>
<body>


java.util.MissingResourceException: Could not load any resource bundle by com.sun.org.apache.xerces.internal.impl.msg.DOMMessages | java.util.MissingResourceException: Could not load any resource bundle by com.sun.org.apache.xerces.internal.impl.msg.DOMMessages
-- | --



</body>
</html>
`
I am hoping adding the resource-config.json in the example will help that.
It's not something I am too familiar with.

**Comment by wanderingfella** [comment]
Next issue is

javax.xml.ws.WebServiceException: org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl)\n\tat org.apache.cxf.jaxws.JaxWsClientProxy.mapException(JaxWsClientProxy.java:193

Will take a look at the example. I did think jboss commons logging should have taken care of it.

**Comment by shumonsharif** [comment]
Hi @wanderingfella I think you should take a deeper look at your dependencies; unfortunately I'm not familiar enough with Gradle to make suggestions, but I believe you can compare the dependency tree between the working sample I provided and what your project has.  Maybe something like `./gradlew -q dependencies --configuration runtimeClasspath` may help.  That may help at least eliminate any potential classpath related issues.

Assuming the issues you are seeing are all limited to native mode, you can always try to regenerate the GraalVM native image config files.  Use a similar command like below to auto-generate, and please be sure to execute your various use cases while the java process is running, so that all relevant classes and resources are accounted for in the auto-generated config files.  Also, you'll likely need to maintain the `custom/reflect-config.json` file as is.

```zsh
java -agentlib:native-image-agent=experimental-class-loader-support,config-output-dir=./src/main/resources/META-INF/native-image/auto-generated/ -jar build/security-0.1-SNAPSHOT-native-image-source-jar/security-0.1-SNAPSHOT-runner.jar
```

**Comment by shumonsharif** [comment]
> I am using a gradle plugin , and trying to collect the classes etc when running ./gradlew test so that should give adequate coverage. It is however including testing stuff I would prefer it not to.

Indeed, you risk bloating up your native image when using `./gradlew test` for coverage for the tracing agent.  My preference has always been to manually run though the various flows, using tools like SoapUI.

> Can you explain why the custom reflection config needs to be kept as is?

I did not dig in too deep, but for reasons unknown to me, the tracing agent did not pick up any of the things defined in the custom reflection config - I needed to manually add those.

**Comment by wanderingfella** [comment]
Sadly, as it's a soap client I am testing in a AWS Lambda, I don't think I can spin it up locally and run through the scenarios :(

The test approach would have been great, if it wasn't full of lots of bloat. The bloat in this instance does seem to break the native building process.

I feel like I am starting to come to the end of the road on this.

**Comment by shumonsharif** [comment]
> Sadly, as it's a soap client I am testing in a AWS Lambda, I don't think I can spin it up locally and run through the scenarios :(

Have you already considered the below; I think it should address your needs?
https://quarkus.io/guides/amazon-lambda#live-coding-and-unitintegration-testing

"While running in Quarkus Dev Mode, you can feed events to it by doing an HTTP POST to http://localhost:8080/. The mock event server will receive the events and your lambda will be invoked. You can perform live coding on your lambda and changes will automatically be recompiled and available the next invocation you make."

Anyway, happy to make suggestions if you're able to put together a reproducer.  Or you can wait for my changes, though that will likely be several weeks at minimum.

**Comment by shumonsharif** [comment]
Nevermind, it seems there's no easy way to show the actual Java commands getting executed when running dev mode.  I thought that may get printed to the console, in which case you could just plug in the tracing agent.

**Comment by shumonsharif** [comment]
Digging in further, it should indeed be achievable ... here's the maven based solution, though I'm sure something similar can be done in Gradle.
https://stackoverflow.com/questions/64450394/how-to-use-the-graalvm-native-image-agent-with-quarkus

**Comment by wanderingfella** [comment]
I did look at that briefly, but I think it needed docker (I am on virtualised windows  - I think it's a pain to set Docker up).

I have a set of reflection config which builds and runs, but falls over due to reflection issues.

I also have the full set including testing stuff, which I am hoping is complete (too complete!).

Between the two, perhaps I can pull something together. It's just the trial and error time which is my problem.
It's my last evening giving it a try, appreciate the help you have provided.

**Comment by shumonsharif** [comment]
Just for the sake of completeness, and in case others stumble on this issue - docker is only needed for the [SAM CLI](https://quarkus.io/guides/amazon-lambda#testing-with-the-sam-cli), and definitely shouldn't be for Quarkus dev mode.

You sound extremely close to having a working solution - hope it all works out for you!

**Comment by wanderingfella** [comment]
I did try it (very briefly) so it might be an erroneous message.
I did get
`2022-02-08 17:36:48,361 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-2) Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
2022-02-08 17:36:48,361 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-2)     NpipeSocketClientProviderStrategy: failed with exception TimeoutException (org.rnorth.ducttape.TimeoutException: java.util.concurrent.TimeoutException). Root cause TimeoutException (null)
2022-02-08 17:36:48,362 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-2) As no valid configuration was found, execution cannot continue
2022-02-08 17:36:48,366 WARN  [io.qua.dep.IsDockerWorking] (build-2) No docker binary found or general error: java.lang.RuntimeException: Input/Output error while executing command.

`
when running

`./gradlew quarkusDev -Dquarkus.http.port=8081
`
I didn't look into much to be honest though.

**Comment by wanderingfella** [comment]
Just got something working. Hurray!
Thanks so much for your help.

I need to do more testing but the main flow works.

Look forward to the later release and happy to be involved in testing it.

**Comment by shumonsharif** [comment]
@wanderingfella Release 0.14.0 is out, are you able to help us test the WS-Security native mode support, and let us know if we can close this issue?
