### ISSUE TITLE
Dependency Injection in Handler Classes not working

### ISSUE THREAD

**Issue by dave1414** [quarkiverse/quarkus-cxf#376]
I have an issues which feels similar to #52, just in a more specific scenario. I want to add soap handlers to my web service (server side) using the @HandlerChain annotation. The handlers are invoked correctly but Dependency Injection does not work as expected for them. Instead of injected instances I get a No bean found for required type exception for the injected beans. I can circumvent that by adding the @Unremovable annotation to the bean so it can be found. However, injection using the @Inject annotation is not working then either as now I get a NullPointerException. When I inject the bean programmatically using CDI.current().select(BeanName.class).get() the injection works fine.

Example Code:

public class Handler implements SOAPHandler<SOAPMessageContext> {

  // not injecting, getting null
  @Inject
  BeanClass injectionFailing;

  //injecting correctly
  BeanClass injectionWorking = CDI.current().select(BeanClass.class).get();
  
I also noticed that the @Resource annotation is not working either if called from within a handler or from a class programmatically injected into a handler.

If you guys have any hint on whether I might be doing something wrong or whether I might have discovered a bug that would be great :)

**Comment by shumonsharif** [comment]
Thanks for the reproducer.  The `SOAPHandler` classes are currently initialized by CXF, and aren't managed via CDI.  So your best option is to use what you already identified as a solution.

```java
CDI.current().select(BeanName.class).get()
```

While it may be possible to override some of the `@HandlerChain` behavior as part of the extension, I'm not sure the effort will be worth the small benefit gained.  We can leave this issue open if you'd like, to gauge whether others may also be interested in this feature.

As far as the `@Resource` annotation not working for `WebServiceContext` - as far as I understood the [spec](https://docs.oracle.com/javase/7/docs/api/javax/xml/ws/WebServiceContext.html), `WebServiceContext` is really meant to be used in an endpoint implementation class.

> A WebServiceContext makes it possible for a web service endpoint implementation class to access message context and security information relative to a request being served. Typically a WebServiceContext is injected into an endpoint implementation class using the Resource annotation.

**Comment by shumonsharif** [comment]
So I dug in a little more, it should be possible add a property to both server and client configs that will allow you to add your handler classes as a comma separated list of fully qualified class names (this will be instead of using the `@HandlerChain` annotation and an XML config file).  I'll try to have this out in the next release!

**Comment by dave1414** [comment]
replacing the handlers.xml file for a working DI sounds fine. Thanks for your effort and help :) I will keep an eye out for this in the next release :)

**Comment by shumonsharif** [comment]
@dave1414 Relase 0.14.0 is out; are you able to test the JAX-WS Handlers support and keep us posted on whether we can close this issue?
