### ISSUE TITLE
Httpexception filter when call to service fails

### ISSUE THREAD

**Issue by mayankchincholkar** [quarkiverse/quarkus-cxf#385]
Hi

I am trying to implement exception filter where when there is any http exception like 404 or 500 to the service, then that filter captures the exception/fault and transform the exception in a Custom error response class . I tried that with interceptors but somehow struggling.  I found that can be achieved by implementing a FaultListener 
https://cxf.apache.org/javadoc/latest/org/apache/cxf/logging/FaultListener.html
like this 
```
 <cxf:properties>
        <entry key="**org.apache.cxf.logging.FaultListener**">
            <bean id="cxfFaultListener" class="pkg.common.ws.interceptor.CxfFaultListenerImpl" >
                <property name="loggedUser" ref="loggedUser"/>
            </bean> 
        </entry>
    </cxf:properties>
```

Is there a way I can get this injected via annotations in my wsdl client generated via wsdl2java and injected via @CXFClient in my quarkus service?

**Comment by shumonsharif** [comment]
Hi @mayankchincholkar Please feel free to start a [discussion](https://github.com/quarkiverse/quarkus-cxf/discussions)  for any general questions; the issues are really meant for bugs.

Assuming you have a `@Produces` method that returns an instance of your custom `FaultListener` implementation, the example code below should work.

```java
    @Inject
    FaultListener myFaultListener;

    @Inject
    @CXFClient
    MyClient myClient;

    @PostConstruct
    void configureClientFaultListener() {
        Bus bus = ClientProxy.getClient(myClient).getBus();
        bus.setProperty(FaultListener.class.getName(), myFaultListener);
    }
```

**Comment by mayankchincholkar** [comment]
thanks @shumonsharif, you are a saviour. this works absolutely fine. Next time i will raise these sorts of questions on discussion boards. Thanks again
