### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkus-cxf#4]
cxf docs:
http://cxf.apache.org/docs/continuations.html
context: goal is to handle async on client and server side.
1) support of async method and add test for that

http://cxf.apache.org/docs/annotations.html#Annotations-org.apache.cxf.annotations.UseAsyncMethod%28since2.6.0%29
2) see if t possible to handle with uni (async use by quarkus) on the cxf ContinuationProvider

**Comment by ambition-consulting** [comment]
High Throughput with low footprint is one of the main reasons for using Quarkus - without Async support this library is really nice, but not production ready for many I am afraid.

**Comment by dufoli** [comment]
@ambition-consulting so you can work on it and send pull request for it...

**Comment by ambition-consulting** [comment]
Fair enough - will see of I find time.

olivier dufour <notifications@github.com> schrieb am So., 6. Dez. 2020,
09:43:

**Comment by Dufgui** [comment]
Now you are based on vertx is it not already done by vertx ?

**Comment by dufoli** [comment]
We do not support async of cxf but vertex use async. So I think we can close this one

**Comment by ambition-consulting** [comment]
Using Vertx doesn't change that synchronous, blocking operations stay
synchronous and blocking. CXF supports asynch code generation I think. Only
if this leads to effectively calling a non-blocking HTTP service correctly,
then there is not much we need to do.

olivier dufour <notifications@github.com> schrieb am Mo., 22. Feb. 2021,
22:31:

**Comment by dufoli** [comment]
cxf support async operation with Future<?> return and UseAsyncMethod annotation. I think we have to use Uni to fit more with quarkus. I found resteasy uni initial support commit with https://github.com/quarkusio/quarkus/commit/69886c11eee8ef240d298d625810dba7cce2088d 
I think I will have to generate async Futur<?> method of cxf with gizmo witch trigger Uni ( completedFuture and subscribeAsCompletionStage)

**Comment by shumonsharif** [comment]
@dufoli and all, just to make sure I'm reading through all this correctly, I believe the client implementation should hopefully be somewhat trivial, as per:
https://cxf.apache.org/docs/asynchronous-client-http-transport.html
"By default, if the cxf-rt-transports-http-hc module is found on the classpath, CXF will use the HttpAsyncClient based implementation for any Async calls, but will continue to use the HttpURLConnection based transport for synchronous calls."

For the server piece of it, the `@UseAsyncMethod` annotation should really be something that the extension users need to address in their service endpoint implementation classes.  

From our perspective, this issue should mostly be a matter of testing and documentation.  Hope I'm not missing anything major here; and my thoughts are somewhat in line with @Dufgui 's ... what do you guys think?

**Comment by dufoli** [comment]
we use vertx transport so I do not think cxf-rt-transports-http-hc will work....

The thing is that on server side, we can test UseAsyncMethod annotation and Futur<?> return value.
But quarkus used mutiny for async operation, So I am thinking to be able to map Futur<> to mutiny...

**Comment by shumonsharif** [comment]
ok @dufoli I'm not sure I follow you, but I'm sure you've been digging into this much longer than I have, so will accept that that is the best way to proceed!

**Comment by dufoli** [comment]
hmm code to test and add to doc if it worked:
olivier dufour: about point 1 with asynchandler... an idea:
@UseAsyncMethod
public String greetMeSometime(String me) {
return "Hello " + me;
}

public Future<?> greetMeSometimeAsync(final String me,
final AsyncHandler<GreetMeSometimeResponse> asyncHandler) {
return Uni.createFrom().item("world").onItem().transform( name -> {
GreetMeSometimeResponse resp = new GreetMeSometimeResponse();
resp.setResponseType("Hello " + name);
return resp;
}
}).invokeUni( (t, uni) -> {asyncHandler.handleResponse(uni.subscribeAsCompletionStage().toCompletableFuture());});
}

**Comment by shumonsharif** [comment]
Hey @dufoli So I tested the client piece of it ... as I had suspected, adding the `cxf-rt-transports-http-hc` dependency to the classpath is all we need to do for the client to leverage CXF's async (non-blocking) features.   There are no updates required for the extension, it works as is.  I confirmed this by writing a simple interceptor:

```java
import org.apache.cxf.interceptor.Fault;
import org.apache.cxf.message.Exchange;
import org.apache.cxf.message.Message;
import org.apache.cxf.phase.AbstractPhaseInterceptor;
import org.apache.cxf.phase.Phase;
import org.apache.cxf.transport.Conduit;
import org.jboss.logging.Logger;

public class HTTPConduitLoggingInterceptor extends AbstractPhaseInterceptor<Message> {

    private static final Logger logger = Logger.getLogger(HTTPConduitLoggingInterceptor.class);

    public HTTPConduitLoggingInterceptor() {
        super(Phase.PRE_PROTOCOL);
    }

    @Override
    public void handleMessage(Message message) throws Fault {
        Exchange exchange = message.getExchange();
        Conduit conduit = exchange.getConduit(message);
        logger.info("Conduit is of type: " + conduit.getClass().getName());
    }
}
```

WITHOUT `cxf-rt-transports-http-hc` in the classpath, we see the following getting logged:
`2021-02-27 08:40:13,394 INFO  [HTTPConduitLoggingInterceptor] (executor-thread-1) Conduit is of type: org.apache.cxf.transport.http.URLConnectionHTTPConduit`

WITH `cxf-rt-transports-http-hc` in the classpath, we see the following getting logged:
`2021-02-27 08:39:08,076 INFO  [HTTPConduitLoggingInterceptor] (executor-thread-1) Conduit is of type: org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit`

With regard to the code you posted for the server, the `@UseAsyncAnnotation` does not seem to be having any impact, ie. the asynchronous method `greetMeSometimeAsync(final String me, final AsyncHandler asyncHandler)` is not getting invoked at all.  One thing to note though is that the `greetMeSometime(String me)` is already getting invoked in a vertx worker thread, which is good.

**Comment by dufoli** [comment]
OK great. Thanks @shumonsharif

**Comment by dufoli** [comment]
So we can close the issue? @shumonsharif wdyt

**Comment by ambition-consulting** [comment]
Sounds great. :-)

olivier dufour <notifications@github.com> schrieb am So., 28. Feb. 2021,
16:23:

**Comment by piba84-lx** [comment]
> Hey @dufoli So I tested the client piece of it ... as I had suspected, adding the `cxf-rt-transports-http-hc` dependency to the classpath is all we need to do for the client to leverage CXF's async (non-blocking) features. There are no updates required for the extension, it works as is. I confirmed this by writing a simple interceptor:
> 
> ```java
> import org.apache.cxf.interceptor.Fault;
> import org.apache.cxf.message.Exchange;
> import org.apache.cxf.message.Message;
> import org.apache.cxf.phase.AbstractPhaseInterceptor;
> import org.apache.cxf.phase.Phase;
> import org.apache.cxf.transport.Conduit;
> import org.jboss.logging.Logger;
> 
> public class HTTPConduitLoggingInterceptor extends AbstractPhaseInterceptor<Message> {
> 
>     private static final Logger logger = Logger.getLogger(HTTPConduitLoggingInterceptor.class);
> 
>     public HTTPConduitLoggingInterceptor() {
>         super(Phase.PRE_PROTOCOL);
>     }
> 
>     @Override
>     public void handleMessage(Message message) throws Fault {
>         Exchange exchange = message.getExchange();
>         Conduit conduit = exchange.getConduit(message);
>         logger.info("Conduit is of type: " + conduit.getClass().getName());
>     }
> }
> ```
> 
> WITHOUT `cxf-rt-transports-http-hc` in the classpath, we see the following getting logged: `2021-02-27 08:40:13,394 INFO [HTTPConduitLoggingInterceptor] (executor-thread-1) Conduit is of type: org.apache.cxf.transport.http.URLConnectionHTTPConduit`
> 
> WITH `cxf-rt-transports-http-hc` in the classpath, we see the following getting logged: `2021-02-27 08:39:08,076 INFO [HTTPConduitLoggingInterceptor] (executor-thread-1) Conduit is of type: org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit`
> 
> With regard to the code you posted for the server, the `@UseAsyncAnnotation` does not seem to be having any impact, ie. the asynchronous method `greetMeSometimeAsync(final String me, final AsyncHandler asyncHandler)` is not getting invoked at all. One thing to note though is that the `greetMeSometime(String me)` is already getting invoked in a vertx worker thread, which is good.

quick question, would it be ok to wrap into a Uni, do you happen to have an example on how to do it “properly”. My apologies for the silly question, but I’m no expert on reactive and really eager to learn more about it.
Thanks a lot!

**Comment by shumonsharif** [comment]
@piba84-lx I unfortunately do not have an example - and am by no means an expert on reactive either - but I think it should be doable fairly easily.  Can you start a new [discussion](https://github.com/quarkiverse/quarkus-cxf/discussions) for your request?

**Comment by shumonsharif** [comment]
@piba84-lx I've attached some [sample code](https://github.com/quarkiverse/quarkus-cxf/files/8541139/code-with-quarkus.zip) that demonstrates the wrapping of a SOAP client call in a Uni.  The code is fairly simple, but in case you have any questions, please definitely start a discussion as suggested previously.  You can invoke the exposed endpoints to see that the eventloop thread is used with the Uni implementation.

**Comment by piba84-lx** [comment]
@shumonsharif  I can't say thank you enough! I didn't find the time to open a new issue. Thank you so much for this sample, super useful! thank you thank you thank you!!!

**Comment by GustavoGramajo** [comment]
> With regard to the code you posted for the server, the `@UseAsyncAnnotation` does not seem to be having any impact, ie. the asynchronous method `greetMeSometimeAsync(final String me, final AsyncHandler asyncHandler)` is not getting invoked at all. One thing to note though is that the `greetMeSometime(String me)` is already getting invoked in a vertx worker thread, which is good.

So, does this mean that we can't use any async API inside the request handler method? I just tried what you quoted back then, and got the same result. What i need is to send a message over vertx's bus (which has an async API), wait for the result, and then use it to return a response.

Thanks in advance for your time and effort!

**Comment by shumonsharif** [comment]
Hi @GustavoGramajo I believe the `@UseAsyncMethod` should work fine if it's implemented (and invoked) correctly.  What I said did not work for me, was specific to the [example code](https://github.com/quarkiverse/quarkus-cxf/issues/4#issuecomment-786448953) being discussed at that time.

One thing to note is that the asynchronous method in your request handler will only get invoked if your client transport supports asynchronous request processing. Otherwise, only the synchronous method will get invoked.  Please feel free to open a new issue in case it isn't working as expected, so we can dig in further.
