### ISSUE TITLE
ServletController intercepts requests to microprofile metrics endpoint

### ISSUE THREAD

**Issue by user667** [quarkiverse/quarkus-cxf#415]
When using Quarkus CXF to expose endpoints one is unable to also use microprofile metrics (`io.quarkus:quarkus-smallrye-metrics`). Requests are being intercepted by `org.apache.cxf.transport.servlet.ServletController` resulting in:
```
Can't find the request for http://localhost:8080/q/metrics's Observer 
```
I was unable to find any means to configure an exclusion. Is there any other way to get this to work?

I've created a reproducer project: https://github.com/user667/quarkus-cxf

**Comment by shumonsharif** [comment]
Hi @user667 Unless configured explicitly, Quarkus CXF intercepts all traffic to the root context.  You can set the following [property](https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/properties.html#quarkus-cxf_quarkus.cxf.path):

```properties
quarkus.cxf.path=/soap
```

All your Quarkus CXF services will then be exposed at:  http://localhost:8080/soap/

**Comment by user667** [comment]
Thanks @shumonsharif for the hint. I was aware of that settings but was hoping for a bypass as we are migrating existing services from another AS (Thorntail & JBoss CXF) and we cannot simply change the context.

**Comment by shumonsharif** [comment]
Gotcha @user667 ... the additional context for your issue is helpful.  I believe there is likely a way you can handle it, perhaps something like the below may work for you.

```java
package org.acme;

import io.quarkus.arc.Unremovable;
import io.quarkus.vertx.web.RouteFilter;
import io.vertx.ext.web.RoutingContext;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import javax.enterprise.context.ApplicationScoped;
import java.util.List;

@ApplicationScoped
@Unremovable
public class RouteRedirector {

    @ConfigProperty(name = "quarkus.cxf.path")
    String quarkusCXFPath;

    @ConfigProperty(name = "cxf.path.exclusions")
    List<String> pathExclusions;

    @RouteFilter(400)
    void pathBasedRerouter(RoutingContext rc) {
        String uri = rc.request().uri();
        if (uri.contains(quarkusCXFPath) || pathExclusions.stream().anyMatch(path -> uri.contains(path))) {
            rc.next();
        } else {
            rc.reroute(quarkusCXFPath + uri);
        }
    }

}
```

```properties
quarkus.cxf.path=/soap
cxf.path.exclusions[0]=/q/
cxf.path.exclusions[1]=/metrics

quarkus.cxf.endpoint."/helloworld".implementor=org.acme.GreetingService
quarkus.cxf.endpoint."/helloworld".published-endpoint-url=/helloworld
```

The above will redirect all requests, except for the ones in the exclusions list, to the `/soap` context.
