### ISSUE TITLE
How to enforce Client Authentication

### ISSUE THREAD

**Issue by Aviss** [quarkiverse/quarkus-cxf#440]
I'm trying to create a WebService that is only allowed to communicate with TLS/SSL.
I was able to configure the Client by setting the `TLSClientParameters` of the `HTTPConduit` as shown in the [Docs](https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/client.html#code-config). 

However, I'm having trouble finding a way to set the `TLSServerParamters` to enforce Client Authentication as seen [here](https://cxf.apache.org/docs/tls-configuration.html#TLSConfiguration-ServerTLSParameters). 

Quarkus itself offers `quarkus.http.ssl.client-auth=REQUIRED` but that globally blocks all HTTP-Requests. I want to only require Client Authentication for SOAP, ideally on a per-WebService basis.

There seems to be hardly any documentation what features and extensions exist for configuring the Bus programmatically so I'll also gladly take any pointers for that.

**Comment by shumonsharif** [comment]
Hi @Aviss You'll have to depend on what Quarkus offers, as we rely on the HTTP framework it provides.  I would suggest you open a ticket in the Quarkus repo, in case they are able to provide path based instead of global settings for mTLS.

**Comment by shumonsharif** [comment]
Not the optimal solution, but you may possibly have some luck with something similar to the below ...

```java
import io.quarkus.vertx.web.RouteFilter;
import io.vertx.core.http.HttpServerRequest;
import io.vertx.ext.web.RoutingContext;
import org.jboss.logging.Logger;

import javax.net.ssl.SSLPeerUnverifiedException;
import java.security.cert.Certificate;
import java.util.List;

public class ClientCertValidator {

    private static Logger LOGGER = Logger.getLogger(ClientCertValidator.class);

    @RouteFilter(100)
    void myFilter(RoutingContext rc) {
        if (rc.request().path().contains("some-service-path")) {
            LOGGER.info("Intercepting SOAP request ...");
            validateClientCertificate(rc.request());
        }
        rc.next();
    }

    private Certificate validateClientCertificate(HttpServerRequest req) {
        try {
            LOGGER.info("Let's validate the client cert ...");
            List<Certificate> certs = req.connection().peerCertificates();
            // Do required validations
        } catch (SSLPeerUnverifiedException e) {

        }
        throw new RuntimeException("No X.509 client certificate found in request");
    }

}
```

**Comment by Aviss** [comment]
I took a deeper look at the quarkus security configuration and was able to get it working with the following configuration:

```
quarkus.http.ssl.certificate.trust-store-file=store.jks
quarkus.http.ssl.certificate.trust-store-password=secret

quarkus.cxf.path=/webservices

quarkus.http.ssl.client-auth=REQUEST
quarkus.security.jaxrs.default-roles-allowed=**

quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=permit

quarkus.http.auth.permission.webservices.paths=/webservices/*
quarkus.http.auth.permission.webservices.policy=authenticated
```

Thank you for the earlier suggestion, regardless.
