### ISSUE TITLE
Support for Camel "cxf" component

### ISSUE THREAD

**Issue by ammachado** [quarkiverse/quarkus-cxf#446]
quarkus-cxf has support for the [cxf](https://camel.apache.org/components/3.16.x/cxf-component.html) component?

If support is available, can you provide information on how to use it?

**Comment by shumonsharif** [comment]
Hi Adriano, the Camel CXF component you linked is unrelated to Quarkus.  

If you are looking to use Camel Quarkus, [this](https://camel.apache.org/camel-quarkus/next/reference/index.html) is the list of components you should be referencing, and Camel Quarkus currently does not have a CXF extension I'm aware of.

Having said that, you can take a look at the docs [here](https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/camel-integration.html) which provide an example of how to integrate this extension with Camel Quarkus.  Hope this is helpful.

**Comment by ppalaga** [comment]
Since Camel Quarkus 2.12.0 there is a new `camel-quarkus-cxf-soap` extension. It is also available on [code.quarkus.io](https://code.quarkus.io/?e=org.apache.camel.quarkus%3Acamel-quarkus-cxf-soap&extension-search=origin:platform%20cxf)

`camel-quarkus-cxf-soap` leverages Quarkiverse CXF.
