### ISSUE TITLE
Provide a BOM?

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#460]
First off, I haven't checked with others, especially @aloubyansky or @gastaldi, whether this is already solved in some general way for quarkiverse extensions or is being worked at.

In my current project we are using `org.apache.cxf:cxf-rt-transports-http-netty-server` to fire up a CXF test server.
Since `quarkus-cxf` is not depending on that module, we have to define the version for that module on our own **and we need to take care to keep it in sync with the version of cxf that `quarkus-cxf` brings in.**

To avoid that, what about providing a `quarkus-cxf-bom` that imports [`cxf-bom`](https://mvnrepository.com/artifact/org.apache.cxf/cxf-bom/3.5.2)?

**Comment by gastaldi** [comment]
@famod I think that makes sense in your case. It may also evolve to be a platform in the future

**Comment by aloubyansky** [comment]
That's reasonable @famod there is an issue to add support for non-platform extensions with BOMs when generating projects. And we'll need to enhance quarkus:info and quarkus:update to be aware of those too.
So at this point our tooling is behind on this but it is a reasonable idea.

**Comment by famod** [comment]
@shumonsharif I see, quite a mess. It's always "fun" to consume upstream poms (not just BOMs) that haven't been convergence-checked.

Ideally, the cxf guys would need to mediate conflicts for e.g. slf4j (just like Quarkus is doing) via excludes and explicit declarations of transitive dependencies.

Are you actively working on it or shall I have a look?

**Comment by shumonsharif** [comment]
Hey @famod I haven't started taking a look - have been on vacation.  That'd be awesome if you could take this one!

**Comment by famod** [comment]
@shumonsharif Please have a look at #466.

**Comment by shumonsharif** [comment]
@famod Will take a look later today!
