### ISSUE TITLE
Issue with SecureRandom in org.apache.xml.security.stax.ext.XMLSecurityConstants

### ISSUE THREAD

**Issue by javaduke** [quarkiverse/quarkus-cxf#485]
We are facing an issue with the WS-Security, the `nonce` is not added to the request even though we set `addUsernameTokenNonce` to true. Apparently the reason is that there's an exception due to the non-initialized secure random in `org.apache.xml.security.stax.ext.XMLSecurityConstants`. I saw that ws-security module substitutes the XMLSecurityConstants class, but the SecureRandom is still initialized at the build time, which causes the problem. Not sure how to address this.
See the https://github.com/apache/camel-quarkus/issues/3966 , in particular, Peters comment here: https://github.com/apache/camel-quarkus/issues/3966#issuecomment-1209360984
Wondering if anyone can give us a hand with this.

Many thanks!

**Comment by ppalaga** [comment]
This should not be an issue anymore as of Quarkiverse CXF 1.5.0
