### ISSUE TITLE
Introduce test BOM

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#496]
A followup of the discussion in https://github.com/quarkiverse/quarkus-cxf/pull/488#discussion_r947223455

Much like Quarkus has its [quarkus-bom-test](https://github.com/quarkusio/quarkus/blob/main/bom/test/pom.xml) we could also introduce a new module called quarkus-cxf-bom-test to manage dependencies useful for testing of Quarkus CXF applications.

`org.apache.cxf:cxf-rt-transports-http-netty-server` would be a good candidate for adding into a new test BOM.

**Comment by famod** [comment]
To quote myself from the references comment:
> `quarkus-cxf-bom-test` makes sense!
> 
> IMO, the first release that contains this change (this PR) has to ship such a test bom as well, otherwise we'd be back to the pre-BOM state as far as that netty artifact is concerned, making it a bit of a breaking change.
