### ISSUE TITLE
Let org.jasypt.normalization.Normalizer.normalizeToNfc() delegate directly to java.text.Normalizer.normalize()

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#519]
The current substitution looks like this:

```
@TargetClass(className = "org.jasypt.normalization.Normalizer")
final class Target_org_jasypt_normalization_Normalizer {

    @Alias
    static char[] normalizeWithJavaNormalizer(final char[] message) {
        return null;
    }

    @Substitute
    public static char[] normalizeToNfc(final char[] message) {
        return normalizeWithJavaNormalizer(message);
    }

}
```

The problem is that when the result of `normalizeToNfc()` is passed to `String(char value[])` a NPE is thrown because the constructor attempts to read `value.length`.

I wonder which of the following is true:

A. We are sure that `normalizeWithJavaNormalizer()` will never be called. If so, I'd vote for throwing something like `new UnsupportedOperationException("org.jasypt.normalization.Normalizer.normalizeWithJavaNormalizer() is not suported in native mode")`

B. We should fix `normalizeWithJavaNormalizer()` to delegate to java.text.Normalizer.normalize(CharSequence, Form). We can do that without reflection, because we are on Java 11+.

C. We rely on `com.ibm.icu.text.Normalizer` maybe? But we do not see anywhere in our classpath.

**Comment by shumonsharif** [comment]
Hi @ppalaga I believe this is something I had worked on ... `normalizeWithJavaNormalizer` is just an `@Alias` and not an actual `@Substitution` ... unless I misunderstood the Graal docs - it should be fine as it is currently?  Please feel free to correct me here, not a Graal expert by any means!

**Comment by ppalaga** [comment]
Ah, thanks for explaining @shumonsharif ! Now it makes a lot of sense!
