### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#533]
... to follow the practice in Quarkus and other repositories in the Quarkus ecosystem.

Any concerns about that @shumonsharif @famod ?

**Comment by famod** [comment]
+1, it's the way to go these days

**Comment by famod** [comment]
Hi @gastaldi, I suppose other extensions have made that move already?

**Comment by shumonsharif** [comment]
Totally for this, I believe I recall seeing some Quarkiverse level discussion about this in the past as well, and looks like many of the Quarkiverse repos have made the switch already.

**Comment by gastaldi** [comment]
@famod yes, that's the recommended practice 👍🏻

**Comment by shumonsharif** [comment]
> Totally for this, I believe I recall seeing some Quarkiverse level discussion about this in the past as well, and looks like many of the Quarkiverse repos have [made the switch](https://github.com/search?q=org%3Aquarkiverse+master+main&type=commits) already.

This is the discussion I was referring to, https://github.com/quarkusio/quarkus/issues/16601, though it appears it was mainly for Quarkiverse CI related updates.  Digging deeper, only a very small number of the actual repos have made this switch.
