### ISSUE TITLE
Development mode reload is broken for exposed CXF services

### ISSUE THREAD

**Issue by jgrabowski** [quarkiverse/quarkus-cxf#551]
I'm having CXF contract first service on Quarkus. While running in development mode each change generates failure saying:
Soap 1.1 endpoint already registered on address /smsprocessor
It looks like live reload cannot "release" already running webservice before applying changes. After restart it works fine until next code change.

**Comment by shumonsharif** [comment]
This used to work fine before; linking issue below for reference:
https://github.com/quarkiverse/quarkus-cxf/issues/94

**Comment by jgrabowski** [comment]
It was quite different. It wasn't' about unsatisfied dependencied but rather about conflict on context (endpoint already registered). I believe it's happening during Quarkus reload. I've enabled quarkus.live-reload.instrumentation=true and it doesn't crash anymore.

**Comment by baptistejr** [comment]
Hello,
I have the same problem.
I think the problem came with this pr: https://github.com/quarkiverse/quarkus-cxf/pull/480
