### ISSUE TITLE
Test endpoints having no configuration in application.properties

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#552]
Not sure this is supposed to work at all and not sure we already have such test. Anybody knows by any chance?

**Comment by shumonsharif** [comment]
Not sure I followed; are you referring to the integration tests?

**Comment by ppalaga** [comment]
> are you referring to the integration tests?

Not necessarily. Both an integration test or a lightweight deployment test would suffice.
