### ISSUE TITLE
Document X-Forwarded support

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#556]
We support rewriting the location value in WSDL through X-Forwarded headers -  see the [XForwardedHeadersTest](https://github.com/quarkiverse/quarkus-cxf/blob/main/integration-tests/server/src/test/java/io/quarkiverse/cxf/it/server/XForwardedHeadersTest.java)
This feature needs to be documented, including at least the following topics:
* A list of supported X-Forwarded headers and what they do
* A rough overview, how the rewriting is implemented
* The role of `quarkus.http.proxy.enable-forwarded-host`, `quarkus.http.proxy.enable-forwarded-prefix` and             `quarkus.http.proxy.proxy-address-forwarding`configuration properties

~~CXF on WildFly supports some advanced address rewriting for the usage with load balancers or proxies: https://docs.wildfly.org/24/Developer_Guide.html#address-rewrite I wonder whether we need to have something like that?~~

**Comment by shumonsharif** [comment]
Hey @ppalaga The use case of LB and proxy related address rewrites sounds very similar to what we already support via X-Forwarded-Headers.  Were you thinking of any additional functionality beyond what was incorporated with https://github.com/quarkiverse/quarkus-cxf/issues/311?

**Comment by ppalaga** [comment]
Thanks a lot @shumonsharif for explaining! Indeed the X-Forwarded headers support does what I was looking for. I made the test a bit more specific when validating the location value in WSDL and I added a native test class in https://github.com/quarkiverse/quarkus-cxf/pull/558

I do not see the X-Forwarded support being documented anywhere, so I am changing the scope of this issue to documentation.

**Comment by ppalaga** [comment]
@jonsalvas @shumonsharif would you please like to review? https://github.com/quarkiverse/quarkus-cxf/pull/1092/files
