### ISSUE TITLE
How do I prevent CXF from publishing the service (in client-only scenarios)

### ISSUE THREAD

**Issue by javaduke** [quarkiverse/quarkus-cxf#586]
I built a Camel Quarkus application which exposes a REST API and calls the remote SOAP serivce - i.e. it acts as a SOAP client. I noticed, however, that CXF Handler is still trying to create a Web Service Web Service org.apache.camel.component.cxf.jaxws.DefaultPayloadProviderSEI on / and fails. Im wondering if it is possible to disable the service creation completely. What I see in the docs at https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/client.html is:
```
Without any further configuration Quarkus-CXF assumes a service to be published at [http://localhost:8080/{service-path}](http://localhost:8080/%7Bservice-path%7D), where {service-path} is derived from
config property quarkus.cxf.path (if present); and the
SEI’s lowercased class name
```
This is a bit confusing, since my intention is not to publish any service but consume a remote service published elsewhere.

**Comment by ppalaga** [comment]
I wonder what is the difference between the [CXF client integration test](https://github.com/apache/camel-quarkus/tree/main/integration-test-groups/cxf-soap/cxf-soap-client) and your use case? If there is no substantial difference, then does problem you describe occur also in the test?

**Comment by ppalaga** [comment]
As of Camel Quarkus 2.13.1 and Quarkiverse CXF 1.5.7, the client only use cases are better tested and should work as expected. Please feel free to reopen this issue if your scenario still does not work @javaduke
