### ISSUE TITLE
`pom.xml` snippets in docs all use outdated `<version>1.3.0</version>`

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#593]
E.g.:
- https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/config.html
- https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/message-logging.html

Shouldn't this be 1.5.6?

Also, I think it's better to document `quarkus-bom` once and don't use any version after that (on any sub-page).

**Comment by ppalaga** [comment]
Yeah, we should ideally use an AsciiDoc attribute for the latest released version and let maven/CI update it during the release.

**Comment by famod** [comment]
There's already thios property: https://github.com/quarkiverse/quarkus-cxf/blob/main/docs/templates/includes/attributes.adoc#L1 

But I don't know/remember when it's updated.

/cc @shumonsharif

**Comment by ppalaga** [comment]
Indeed, it is not easy. I went through that in Camel Quarkus where it works now. The key parts are these preparationGoals and completionGoals config: https://github.com/apache/camel-quarkus/blob/main/pom.xml#L359-L360 and the commit-release-changes https://github.com/apache/camel-quarkus/blob/main/pom.xml#L1088-L1142

It can be tested locally by passing `-DpushChanges=false -DlocalCheckout=true` to the release mojos.

**Comment by shumonsharif** [comment]
Nice @ppalaga! So this line is where I had attempted to integrate the the `-Ddocs-version-updates' flag for quarkus-cxf:
https://github.com/quarkiverse/quarkus-cxf/blob/main/.github/workflows/release.yml#L53-L57

The next couple lines in the block (which actually commit the updated files) failed when I tried to release - I don't recall the exact error as it's been quite a while, but I think it didn't like the files being updated or committed during the release process.

@famod Actually suggested some great ideas when I tried to implement this, but that's as far as I got!!
