### ISSUE TITLE
Demote `Not registering a Vert.x handler ...` message to DEBUG

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#598]
Just a minor thing, but the following message just adds noise if you're only using clients (like in my case):
```
INFO  [io.qua.cxf.dep.CxfEndpointImplementationProcessor] (build-96) Not registering a Vert.x handler for CXF as no WS endpoints were found at build time and no other extension requested it
```

I'll disable this logger in my project but it might be worth thinking about to demote this message to DEBUG.

**Comment by ppalaga** [comment]
I have added those messages due to https://github.com/apache/camel-quarkus/issues/4192 I thought it would be beneficial for the users to see how their server endpoints are mapped and why the possibly do not see other (like RESTeasy) endpoints to work. 

I think you are right that in case there the Vert.x route is not deployed, it can be just a debug message. So please go ahead and send a PR if you like

**Comment by famod** [comment]
@ppalaga I had a quick look and I'm not entirely sure what "in case the Vert.x route is not deployed" means here.

Do you mean if `cxfRouteRegistrationRequestors` is empty?

**Comment by ppalaga** [comment]
Yes, the vert.x route is deployed only when there are some CXF service endpoints present in the app. That's done in the `true` branch of the conditional

```
        if (!requestors.isEmpty()) {
            final Handler<RoutingContext> handler = recorder.initServer(infos, beanContainer.getValue(),
                    httpConfiguration);
            final String mappingPath = getMappingPath(cxfBuildTimeConfig.path);
            LOGGER.infof("Mapping a Vert.x handler for CXF to %s as requested by %s", mappingPath, requestors);
            routes.produce(RouteBuildItem.builder()
                    .route(mappingPath)
                    .handler(handler)
                    .handlerType(HandlerType.BLOCKING)
                    .build());
        } else {
            LOGGER.info(
                    "Not registering a Vert.x handler for CXF as no WS endpoints were found at build time and no other extension requested it");
        }
```

The `else` branch outputs the message you do not like. I am all for changing `LOGGER.info("Not registering...` to `LOGGER.debug("Not registering...`
