### ISSUE TITLE
Upgrade to Quarkus 3.0/CXF 4.0/Jakarta 10

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#605]
Quarkus migration tips: https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x
Blocked by CXF: https://issues.apache.org/jira/browse/CXF-8371

**Comment by shumonsharif** [comment]
@ppalaga It may be possible to get started with development on this using the [CXF 4.0.0-SNAPSHOT](https://repository.apache.org/content/groups/snapshots/org/apache/cxf/cxf-bom/4.0.0-SNAPSHOT/) releases with the repositories included at the bottom of [this page](https://cxf.apache.org/docs/using-cxf-with-maven.html).

I ran a very crude check - all our `quarkus-cxf` dependencies resolved, and got the same output between the current 3.5.3 and the 4.0.0-SNAPSHOT versions:

```mvn dependency:tree | grep cxf | wc -l```

**Comment by ppalaga** [comment]
Thanks for the tips, @shumonsharif !

I think I'll only have time to work on this after Dec 14th. In case you or anybody else would like to set up a branch/PR it would be welcome.

**Comment by shumonsharif** [comment]
@ppalaga I just pushed https://github.com/quarkiverse/quarkus-cxf/tree/quarkus-3.x

Everything works fine except some of the native test executions.  I suspect the issues are unrelated to the extension; I will dig in as time permits, but feel free to do so as well!

**Comment by shumonsharif** [comment]
Except for the couple native tests relating to MTOM, everything else should be fixed and working now.  For now, I have temporarily disabled `MtomIT` and `MtomAwtIT` unit tests, to see if the build passes.

@ppalaga @famod Please feel free to review as your time permits!

**Comment by shumonsharif** [comment]
Looks like container based native builds are failing.  Without the below, the build on my laptop is passing fine ... will dig in again later!

-Dquarkus.native.container-build=true

**Comment by shumonsharif** [comment]
Issues have been resolved with the native test failures.  There's an issue with running the mtom-awt native test on Mac OS, so it's [conditional on the OS](https://github.com/quarkiverse/quarkus-cxf/compare/quarkus-3.x#diff-707635b0580c7d741a6ec8571ea9882ea2a8de18ec765d8a4fde56c7afcbcaffR9-R13) for now.  Please take a look if you get a chance.

https://github.com/quarkiverse/quarkus-cxf/compare/quarkus-3.x
