### ISSUE TITLE
Ban dependency `org.apache.geronimo.javamail:geronimo-javamail_1.4_mail`

### ISSUE THREAD

**Issue by jamesnetherton** [quarkiverse/quarkus-cxf#622]
@ppalaga Do you think we can ban `org.apache.geronimo.javamail:geronimo-javamail_1.4_mail` and use a jakarta equivalent (E.g `com.sun.mail:jakarta.mail`).?

**Comment by shumonsharif** [comment]
Just a note - this has been addressed in the quarkus-3.x branch (https://github.com/quarkiverse/quarkus-cxf/issues/605).

**Comment by ppalaga** [comment]
> Do you think we can ban org.apache.geronimo.javamail:geronimo-javamail_1.4_mail and use a jakarta equivalent (E.g com.sun.mail:jakarta.mail)?

+1

**Comment by ppalaga** [comment]
#644 bans org.apache.geronimo.javamail:geronimo-javamail_1.4_mail in favor of com.sun.mail:jakarta.mail which is also prefered by Quarkus
