### ISSUE TITLE
CxfHandler.loadClass() should not fail silently

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#625]
It currently just warns. It should throw an exception so that users do not need to struggle with typos in their application.properties

```
    private static Class<?> loadClass(String className) {
        try {
            return Thread.currentThread().getContextClassLoader().loadClass(className);
        } catch (ClassNotFoundException e) {
            // silent fail
        }
        try {
            return Class.forName(className);
        } catch (ClassNotFoundException e) {
            LOGGER.warn("failed to load class " + className);
            return null;
        }
    }
```

**Comment by ppalaga** [comment]
I have hit this again. It needs to fail hardly.

**Comment by shumonsharif** [comment]
I think there's a couple scenarios we need to account for here:
- typo in application.properties
- a missing dependency containing a referenced class, eg. `org.apache.cxf.ext.logging.LoggingFeature`

Not sure on the value of throwing a RuntimeException though; my understanding is that some of these may be loaded lazily and not at application startup.  Perhaps including the stacktrace instead of just a simple warning message would make it more obvious?

**Comment by ppalaga** [comment]
> my understanding is that some of these may be loaded lazily and not at application startup

Could you please explain what you mean with lazy loading? - sounds like dynamic class loading during the application life time; e.g. loading at t1 does not succeed, but succeeds later at t2, because the classpath has changed? Such scenario is not possible on Quarkus and esp. GraalVM. All code has to be known at build time. But maybe you mean something else?

**Comment by shumonsharif** [comment]
Definitely not dynamic class loading - what I was referring to was literally lazy loading as documented here:
https://quarkus.io/guides/cdi-reference#lazy_by_default

The code has changed a lot in recent times, so it may no longer be an issue, but if my memory serves me well, there were some instances under which this happened in earlier versions ...

**Comment by ppalaga** [comment]
Thanks for explaining, @shumonsharif. I am still not sure how the CDI container may affect what we do in `CxfHandler.loadClass()` - that's pure class lookups by class name what we do there. I do not see how the the CDI container could be involved. We do not lookup beans.

**Comment by shumonsharif** [comment]
I was under the impression `CxfHandler.loadClass()` only ever gets called if a CDI bean lookup fails?  

Again, it may no longer be the case, but I thought there were some cases where the CDI bean lookup path would only get triggered after the initial request invocation.  I honestly have not even looked at the code, but I'll try to dig into it later this week and keep you posted if I see this being an issue.
