### ISSUE TITLE
code.quarkus.io should use quarkus-cxf-bom

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#651]
We have a BOM since a couple of releases and code.quarkus.io does not utilize it:

```
...
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkiverse.cxf</groupId>
      <artifactId>quarkus-cxf</artifactId>
      <version>1.6.0</version>
    </dependency>
...
```

Expected is something like

```
...
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.quarkiverse.cxf</groupId>
        <artifactId>quarkus-cxf-bom</artifactId>
        <version>${quarkus.cxf.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkiverse.cxf</groupId>
      <artifactId>quarkus-cxf</artifactId>
    </dependency>
...
```

**Comment by ppalaga** [comment]
Any hint how to address this one @aloubyansky?

**Comment by aloubyansky** [comment]
Unfortunately, it's currently not supported for non-platform extensions.
Not exactly the same but is somewhat similar to https://github.com/quarkusio/quarkus/issues/25937

**Comment by ppalaga** [comment]
This causes real issues, such as https://github.com/quarkiverse/quarkus-cxf/issues/694, to end users. 

@maxandersen what would be the best way forward? Is there no easier option than to go full Platform with CXF? 
Or can perhaps code.quarkus.io to become smarter?

I am not sure I am looking forward for the Platform overhead. Maybe if Platform's CI could amend dependabot PRs with the generated changes so that much less human interaction is required? (I do not see anything like that in Platform workflows).

**Comment by maxandersen** [comment]
@aloubyansky isnt this exactly the same issue as in #25937 ?

With operatorsdk and cxf being in quarkiverse finding way to handle augmenting a single cxf import seems relevant to add. 

What would be the challenges for this?

**Comment by aloubyansky** [comment]
I think the reason I previously described it as not being exactly the same was that https://github.com/quarkusio/quarkus/issues/25937 was formulated as importing a BOM from a codestart (with a ref to a discussion). It'd be a different approach than what is being asked here.
It's a reasonable request and we should look into adding support for it. It will be somewhat different and more challenging from how we handle platform BOMs though.

**Comment by ppalaga** [comment]
For the record: I would not mind going to the Platform with CXF, but as I said, upgrades would have to be much more automated. 
Is there any reason not to have CXF in the Platform?

**Comment by maxandersen** [comment]
Yeah. I would say if cxf becomes supported by camel it would make sense to have the relevant parts in platofrm.

**Comment by ppalaga** [comment]
I created an epic in Quarkus https://github.com/quarkusio/quarkus/issues/31831 asking for CI-driven participant upgrades in the Platform.

**Comment by ppalaga** [comment]
quarkus-cxf is a part of the Platform since Platform version 3.1.0 (IIRC).
