### ISSUE TITLE
Additional quarkus-cxf extensions not present on code.quarkus.io

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#652]
code.quarkus.io currently lists only quarkus-cxf: https://code.quarkus.io/?e=io.quarkiverse.cxf%3Aquarkus-cxf&extension-search=origin:other%20cxf

It should list also 

* `quarkus-cxf-rt-features-logging`
* `quarkus-cxf-rt-features-metrics`
* `quarkus-cxf-rt-transports-http-hc5`
* `quarkus-cxf-rt-ws-rm`
* `quarkus-cxf-rt-ws-security`
* `quarkus-cxf-services-sts`

**Comment by ppalaga** [comment]
Any hint how to address this one @aloubyansky?

**Comment by aloubyansky** [comment]
@gastaldi could you please check whether they are present in the registry?

**Comment by gastaldi** [comment]
Why should `-parent` artifacts be in the registry? 

Also I don't see them in the extension catalog (each extension should have their own YAML)

**Comment by ppalaga** [comment]
> Why should -parent artifacts be in the registry?

Sorry, copy'n'paste error. The description is fixed now.

> Each extension should have their own YAML

IIRC they do have their platform descriptors - e.g. here the logging one: https://github.com/quarkiverse/quarkus-cxf/blob/main/extensions/features-logging/runtime/src/main/resources/META-INF/quarkus-extension.yaml

**Comment by gastaldi** [comment]
@ppalaga sorry, I mean a YAML for each in https://github.com/quarkusio/quarkus-extension-catalog/tree/main/extensions. 

See the micrometer extensions there as an example

**Comment by ppalaga** [comment]
Thanks, let me send a PR to https://github.com/quarkusio/quarkus-extension-catalog/tree/main/extensions

**Comment by ppalaga** [comment]
PR sent https://github.com/quarkusio/quarkus-extension-catalog/pull/41
