### ISSUE TITLE
Need help regarding how to pass backend url to CXF client dynamically(Runtime)

### ISSUE THREAD

**Issue by parulj220** [quarkiverse/quarkus-cxf#666]
Our requirement is to pass backend urls to CXF client at runtime programmatically based on the environment label header from the request. Could you please let us know if there is any way to achieve this?

**Comment by ppalaga** [comment]
Something like this should work:

```
    public static <T> T getClient(String namespace, Class<T> serviceInterface, String endpointUri) {
        try {
            final URL serviceUrl = new URL(endpointUri + "?wsdl");
            final QName qName = new QName(namespace, serviceInterface.getSimpleName());
            final Service service = javax.xml.ws.Service.create(serviceUrl, qName);
            return service.getPort(serviceInterface);
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by ppalaga** [comment]
What do you mean with "update the endpoints for cxf client"? Is it something different than using a different endpoint URL every time? With the above method, you can do exactly that. But maybe you mean something different?

**Comment by shumonsharif** [comment]
Peter's approach is certainly the clean way to do it.  The question is not very clear, but if you're extracting the endpoint per request based on an HTTP header, you may be able to get away with something like this:

```java
    @CXFClient
    CalculatorSoap calculatorSoap;

    @GET
    @Path("/{num1}/{num2}")
    public Integer addNumbers(Integer num1, Integer num2) {

        String dynamicEndpointUrl = // Extract environment label header from the request

        ((BindingProvider)calculatorSoap).getRequestContext()
                      .put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, dynamicEndpointUrl);

        // Do stuff with calculatorSoap client

    }
```

**Comment by ppalaga** [comment]
Please feel free to reopen if you have any more questions
