### ISSUE TITLE
External DTD problem

### ISSUE THREAD

**Issue by asyle83** [quarkiverse/quarkus-cxf#668]
After added in my pom the quarkus-cxf dependency, I receive a Fatal Error when building with quarkus-maven-plugin:
`[Fatal Error] :20:70: External DTD: Failed to read external DTD 'properties.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.`

I tried to set the JVM arg `-Djavax.xml.accessExternalDTD=all` or `-Djavax.xml.accessExternalDTD=http` and `-Djavax.xml.accessExternalSchema=all` but nothing solved the issue.

I'm using quarkus-cxf version 1.7.2 and quarkus platform version 2.15.0.Final.

I noticed that the 'properties.dtd' is the one referenced in the wsdl.plugin.xml file inside cxf-rt-bindings-soap-3.5.5 jar (https://github.com/apache/cxf/blob/main/rt/bindings/soap/src/main/resources/META-INF/wsdl.plugin.xml)

and I also receive a warning after the fatal error:
`[WARNING] [io.quarkiverse.cxf.deployment.QuarkusCxfProcessor] can not merge wsdl.plugin.xml`

I'm building an uber-jar (don't know if it is relevant)

How can I solve the issue?
Thanks

**Comment by shumonsharif** [comment]
Hi @asyle83 The reason non of the JVM args work is because we currently explicitly disable external DTD processing in the [code](https://github.com/quarkiverse/quarkus-cxf/blob/main/extensions/core/deployment/src/main/java/io/quarkiverse/cxf/deployment/QuarkusCxfProcessor.java#L214).  

The referenced PR should address this issue.

**Comment by asyle83** [comment]
@shumonsharif  thanks! Witch platform version will contains this fix? Or how can I take it? Thanks

**Comment by shumonsharif** [comment]
@ppalaga and @famod handle the releases these days, so perhaps they can help you with your question.

**Comment by famod** [comment]
Having this in 1.7.3 would be logical (for me). Right now we are having some [release/build issues](https://github.com/quarkiverse/quarkus-cxf/pull/664) and Peter seems to enjoy some time off screen.

**Comment by asyle83** [comment]
Ok @famod, I'll wait for next release... Hope you'll solve build issues soon :)

**Comment by asyle83** [comment]
@famod any news about the release? :)

**Comment by famod** [comment]
@asyle83 we are having some issues with the test setup (follow #669 if you are interested in details). Sorry for the delay.

**Comment by famod** [comment]
@asyle83 1.7.3 is now available and should fix this problem.

**Comment by asyle83** [comment]
Thanks it worked ;)
