### ISSUE TITLE
Compile errors with cxf-codegen-plugin 4.0.0  (Jakarta EE support)

### ISSUE THREAD

**Issue by tibersept** [quarkiverse/quarkus-cxf#673]
Since upgrading to version 4.0.0 of `cxf-codegen-plugin` (Jakarta EE, see closed Jira issue [https://issues.apache.org/jira/browse/CXF-8371](https://issues.apache.org/jira/browse/CXF-8371)) the generated SOAP classes do not compile and the plugin has no obvious switch to revert back to the JEE namespace:

```
package jakarta.xml.bind.annotation does not exist
package jakarta.jws does not exist
package jakarta.xml.ws does not exist
...
```

Quarkus 2.X has no support for Jakarta EE. Is there a general strategy/roadmap/workaround here?

**Comment by shumonsharif** [comment]
There is a quarkus-3.x branch you can take a look at for how I worked around this issue, more specifically:
https://github.com/quarkiverse/quarkus-cxf/blob/quarkus-3.x/integration-tests/client/pom.xml#L61-L114

I have to ask though, why are you using version 4.0.0 of the plugin?

**Comment by tibersept** [comment]
Thanks for the quick response. It was a proposed automated Dependabot upgrade, which we'll reject. I wanted to be sure that I am not ignoring any obvious undocumented flag to switch back to JEE. So version 4.0.0 is for Quarkus 3.X, that's completely fine.
