### ISSUE TITLE
Annotation based retries with CXF client

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#713]
@cescoffier could you please sketch your vission?

**Comment by cescoffier** [comment]
The idea would be to reuse the pattern we use for REST clients where we have a Java interface with methods mapping to operations. The advantage of that approach is the combination with fault tolerance annotation (and, to some extent, implementing an ambassador pattern). 

For example:

```java
@RegisterWebServiceClient(...)
public class interface MyWSClient {

    @Operation(...)
    @Retry(3)
    @Timeout(2000)
    String myOperation(String arg1, arg2);
}
```

Under the hood, the main difference with what we have right now is that the framework managed the objects providing the interface mentioned above. It is exposed as a CDI bean, and such can be wrapped, intercepted, decorated... I think this is the essence of that feature: make WS client CDI beans that the user can decorate and so on.

**Comment by ppalaga** [comment]
I have found `@org.eclipse.microprofile.faulttolerance.Retry` and `@org.eclipse.microprofile.faulttolerance.Timeout` but what is `@Operation` supposed to be doing?

**Comment by cescoffier** [comment]
@operation was just an idea to map a method to a soap operation. It does not exist yet (and maybe it will never exist?

**Comment by ppalaga** [comment]
There is WS-ReliableMessaging spec for this kind of use cases. We now finally have a proper test coverage and user-friendly configuration - see https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf-rt-ws-rm.html

Thus I am closing this issue as not planned for now.
