### ISSUE TITLE
Connection pooling in quarkiverse

### ISSUE THREAD

**Issue by doppiak80** [quarkiverse/quarkus-cxf#718]
It is possible to configure connection pooling (min/max pool size)?

**Comment by ppalaga** [comment]
How would you do this with plain CXF?

**Comment by ppalaga** [comment]
Anybody knows how to do this with plain CXF?

**Comment by shumonsharif** [comment]
I'm assuming this is relating to CXF clients, and I don't believe this is achievable with plain CXF, I would suggest the issue is closed.
