### ISSUE TITLE
Add migration guide to 2.0.0

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#811]
Possible topics:

* Quarkus 3.0.0 migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0
* Javax -> Jakarta migration - we should check how well [Quarkus migration](https://quarkus.io/blog/quarkus-3-0-0-cr1-released/#upgrading) works for us and eventually submit improvements
* Changed default value of `quarkus.cxf.path` from `/` to `/services` - see https://github.com/quarkiverse/quarkus-cxf/issues/795 for motivation

**Comment by codespearhead** [comment]
Should this issue be closed now that [1] has been merged?

***

[1] https://github.com/quarkiverse/quarkus-cxf/pull/817

**Comment by ppalaga** [comment]
Thanks for the heads up, indeed this issue is rather out of date.
