### ISSUE TITLE
Migrate to the new Dev UI

### ISSUE THREAD

**Issue by phillip-kruger** [quarkiverse/quarkus-cxf#814]
see https://github.com/quarkusio/quarkus/issues/31315

**Comment by ppalaga** [comment]
Any deadlines?

**Comment by phillip-kruger** [comment]
No deadlines yet. asap ?

**Comment by ppalaga** [comment]
Is it fine, to keep the old Dev UI, while we are on Quarkus 3.0.0.Final?

**Comment by phillip-kruger** [comment]
Yes sure

**Comment by phillip-kruger** [comment]
@ppalaga is this something you can look at ? We are starting to plan the removal of the old Dev UI.

**Comment by famod** [comment]
quarkus-cxf breaks with Quarkus 3.4.0.CR1: https://github.com/quarkusio/quarkus/pull/35426#issuecomment-1710183985
That change will be rolled back for 3.4.0 final, but for 3.5.0 at the latest quarkus-cxf needs to move.

**Comment by phillip-kruger** [comment]
I did the rollback here: https://github.com/quarkusio/quarkus/pull/35808

I also started the work to migrate this (CXF) Dev UI to the new Dev UI. Expect a PR soon.
