### ISSUE TITLE
How to provide multiple endpoint URLs for the CXF clustering feature (failover, loadbalancing) 

### ISSUE THREAD

**Issue by sburkard** [quarkiverse/quarkus-cxf#834]
Is there any documentation or an example how to use and configure the **CXF clustering feature** with Quarkus CXF? 

I tried adding the feature via property (and the CXF dependency `cxf-rt-features-clustering` because there seems to be no quarkified extension).

In properties: 
```
quarkus.cxf.client."MyService".features=org.apache.cxf.ext.logging.LoggingFeature,org.apache.cxf.clustering.FailoverFeature
```

When I intentionally configure an invalid endpoint, I see in the logs the failed request and then the FailoverTargetSelector jumping in and try to use the default SequentialStrategy. 
BUT: how can I configure a list of possible service endpoints?

I use the endpoint property `quarkus.cxf.client."MyService".client-endpoint-url`, but this takes a string, not a List of strings. I nevertheless tried a comma-separated list, but this is interpreted as a single endpoint string.

**Comment by shumonsharif** [comment]
I don't believe multiple endpoints are currently supported with `client-endpoint-url`.

As a workaround, you can try setting programmatically using the approach below.

```java
import io.quarkus.arc.Unremovable;
import org.apache.cxf.clustering.FailoverFeature;
import org.apache.cxf.clustering.SequentialStrategy;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;
import java.util.Arrays;

public class FailoverFeatureProducer {

    @Produces
    @ApplicationScoped
    @Unremovable
    FailoverFeature failoverFeature() {
        SequentialStrategy sequentialStrategy = new SequentialStrategy();
        sequentialStrategy.setAlternateAddresses(
                Arrays.asList(
                        "http://www.bad-host-2.com/calculator.asmx",
                        "http://www.dneonline.com/calculator.asmx"));

        FailoverFeature failoverFeature = new FailoverFeature();
        failoverFeature.setStrategy(sequentialStrategy);
        return failoverFeature;
    }

}
```

**Comment by sburkard** [comment]
Works great, thanks.
