### ISSUE TITLE
How to configure multiple WS clients with CXF failover feature

### ISSUE THREAD

**Issue by sburkard** [quarkiverse/quarkus-cxf#842]
The code suggested in #834 works great to add a failover configuration to a single WS client created through properties. 
However, when I have **multiple different WS clients**, each one has its own endpoint-URL and alternative URLs. 

What would be the best way to configure this in quarkus-cxf until #836 is available? 

- When I create multiple `FailoverFeature` configurations as the one suggested in Issue #834, how can I connect each of them with the corresponding WS client created through "standard" application properties? Can I get the CXF clients from the Bean registry in the Producer class so that I can add the `FailoverFeature`?

- Or do I need to **build the WS clients entirely from code** and drop the client properties? If yes, is there an example for this? I found the `CxfClientProducer` that produces clients based on the collected `CXFClientInfo` instances

Thanks

**Comment by shumonsharif** [comment]
Hi @sburkard You should be able to use `@Named` feature configurations.

https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/reference/extensions/quarkus-cxf-rt-features-logging.html#extensions-quarkus-cxf-rt-features-logging-usage-multiple-custom-loggingfeature-s

**Comment by shumonsharif** [comment]
You may have some luck with the approach below until the referenced issues are resolved.

```java
package org.acme;

import io.quarkus.runtime.Startup;
import org.apache.cxf.clustering.FailoverFeature;
import org.apache.cxf.clustering.SequentialStrategy;

import javax.enterprise.context.ApplicationScoped;
import java.util.Arrays;

@ApplicationScoped
@Startup
public class FailoverFeature1 extends FailoverFeature {

    public FailoverFeature1() {
        SequentialStrategy sequentialStrategy = new SequentialStrategy();
        sequentialStrategy.setAlternateAddresses(
                Arrays.asList(
                        "http://www.dneonline.com/calculator.asmx"));
        super.setStrategy(sequentialStrategy);
    }
    
}
```

Create as many variations of the above as you need for each of your strategies, then reference them in your `application.properties` as per usual:

```properties
quarkus.cxf.client."calculator-soap".features=org.acme.FailoverFeature1
```

The [Quarkus CDI](https://quarkus.io/guides/cdi-reference) reference may be a helpful guide for you.

**Comment by sburkard** [comment]
Excellent, works perfect. Thanks a lot for your help and looking forward for #836

By the way: the referencing of a named bean with `#` in properties is kind of "hidden" on the mentioned page about the LoggingFeature. If this is a general Quarkus feature (as in Spring), this might be OK because it is common sense and not specific to quarkus-cxf, otherwise it should be moved to its own page. I never looked at the LoggingFeature page since I had no problem with that feature.

Regards
