### ISSUE TITLE
Generating the model classes from WSDL does not work

### ISSUE THREAD

**Issue by nevenr** [quarkiverse/quarkus-cxf#843]
Reproducer
1.  Ensure JDK 17 on working station
2.  Create project stub on https://code.quarkus.io
  2.1.  Choose quarkus version 2.16
  2.2. Include Quarkus CXF [quarkus-cxf] extension (version 1.7.3 will be set)
  2.3. Download and extract project stub
3.  Follow instruction on https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/user-guide/first-soap-client.html
  3.1. Place WSDL (e.g. CalculatorService.wsdl) src/main/resources/wsdl/CalculatorService.wsdl
  3.2. To app config file (src/main/resources/application.properties) add
         quarkus.cxf.codegen.wsdl2java.includes=wsdl/*.wsdl
4.  Build app
         mvnw clean package
5.  Check target/generated-sources for generated sources, it will be empty.

In maven log there is no visible issue / error report. It is just reported that " quarkus-maven-plugin:2.16.6.Final:generate-code" was invoked but no model classes are generated.

**Comment by nevenr** [comment]
[build-output.zip](https://github.com/quarkiverse/quarkus-cxf/files/11310560/build-output.zip)

**Comment by ppalaga** [comment]
Thanks for the perfect report, @nevenr!

Sorry to disappoint you, but the wsdl2java feature works only in quarkus-cxf 2.0.1 (on quarkus 3.0.0)
I have also backported it to quarkus-cxf 1.5.13 (quarkus 2.13).

> 2.2. Include Quarkus CXF [quarkus-cxf] extension (version 1.7.3 will be set)

Please make sure you use [quarkus-cxf-bom](https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/user-guide/create-project.html#dependency-management)

**Comment by ppalaga** [comment]
Feel free to reopen if it does not work on some of the supported versions
