### ISSUE TITLE
autoNameResoltion because naming conflict when generating from wsdl

### ISSUE THREAD

**Issue by TomBrz** [quarkiverse/quarkus-cxf#861]
When generating classes using apache cxf from a wsdl file, i manage to generate the classes without a problem, but when I use quarkus-cxf i have the following problem:
`Parameter: header already exists for method ping but of type be.belgium.fsb.v1_00.SyncHeader instead of be.belgium.fsb.v1_00.SyncResponseHeader. Use a JAXWS/JAXB binding customization to rename the parameter.`

I think it's because  apache cxf allows for the setting : `<autoNameResolution>true</autoNameResolution>` in pom.xml In order to prevent problems with naming conflicts.

Is there a way to do this in quarkus and solve the issue? Or is there another way to solve the issue?

**Comment by TomBrz** [comment]
the following works:
quarkus.cxf.codegen.wsdl2java.additional-params=-autoNameResolution

**Comment by ppalaga** [comment]
> quarkus.cxf.codegen.wsdl2java.additional-params=-autoNameResolution

was exactly, I was going to suggest :)
