### ISSUE TITLE
Make the beans of types referable in application.properties unremovable so that users do not need to bother with @Unremovable

### ISSUE THREAD

**Issue by mederel** [quarkiverse/quarkus-cxf#943]
Hi,

I think the contract for interceptor definition might not be working in all cases. The contract seems to be (from the documentation):

> Both feature and interceptor classes will be attempted to be loaded via CDI first, and if no CDI beans are available, then the constructor with no parameters will be invoked to instantiate each class. 

For which my understanding is, if I have an interceptor with CDI annotations like:

```java
@ApplicationScoped
public class MyBeanInterceptor extends AbstractSoapInterceptor {
  private final MyBean myBean;
  @Inject
  public MyBeanInterceptor(MyBean myBean) {
    super(Phase.PRE_LOGICAL);
    this.myBean = myBean;
  }
}
```

and then its definition as an out interceptor for a client proxy:

```properties
quarkus.cxf.client.calculator.out-interceptors=org.acme.MyBeanInterceptor
```

I would expect the CXF extension to find the defined CDI bean, and use its instance as the interceptor instance in the chain.

Sadly what happens is the following:

```
2023-07-24 13:23:06,407 WARN  [io.qua.arc.impl] (executor-thread-1) 
================================================================================
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build

Stack frame: io.quarkiverse.cxf.CXFRuntimeUtils.getInstance(CXFRuntimeUtils.java:29)
Required type: class org.acme.MyBeanInterceptor
Required qualifiers: []
Removed beans:
	- CLASS bean  [types=[interface org.apache.cxf.binding.soap.interceptor.SoapInterceptor, class org.apache.cxf.binding.soap.interceptor.AbstractSoapInterceptor, null<org.apache.cxf.binding.soap.SoapMessage>, class org.acme.MyBeanInterceptor], qualifiers=null]
Solutions:
	- Application developers can eliminate false positives via the @Unremovable annotation
	- Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
	- See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
	- Enable the DEBUG log level to see the full stack trace
================================================================================

2023-07-24 13:23:06,411 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /soap/shoot/MULTIPLY/15/41 failed, error id: 6b9bd649-747c-4fd2-9676-ff6476f64925-1: java.lang.RuntimeException: Could not instantiate org.acme.MyBeanInterceptor using the default constructor. Make sure that the constructor exists and that the class is static in case it is an inner class.
	at io.quarkiverse.cxf.CXFRuntimeUtils.getInstance(CXFRuntimeUtils.java:36)
	at io.quarkiverse.cxf.CxfClientProducer.addToCols(CxfClientProducer.java:144)
	at io.quarkiverse.cxf.CxfClientProducer.addToCols(CxfClientProducer.java:139)
	at io.quarkiverse.cxf.CxfClientProducer.produceCxfClient(CxfClientProducer.java:118)
	at io.quarkiverse.cxf.CxfClientProducer.loadCxfClient(CxfClientProducer.java:52)
	at com.example.CalculatorCxfClientProducer.createService(Unknown Source)
	at com.example.CalculatorCxfClientProducer_ProducerMethod_createService_8aaff4e79ae1527f1837a7602f86730ec543ebb0_Bean.doCreate(Unknown Source)
	at com.example.CalculatorCxfClientProducer_ProducerMethod_createService_8aaff4e79ae1527f1837a7602f86730ec543ebb0_Bean.create(Unknown Source)
	at com.example.CalculatorCxfClientProducer_ProducerMethod_createService_8aaff4e79ae1527f1837a7602f86730ec543ebb0_Bean.get(Unknown Source)
	at com.example.CalculatorCxfClientProducer_ProducerMethod_createService_8aaff4e79ae1527f1837a7602f86730ec543ebb0_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:48)
	at org.acme.GreetingResource_Bean.doCreate(Unknown Source)
	at org.acme.GreetingResource_Bean.create(Unknown Source)
	at org.acme.GreetingResource_Bean.create(Unknown Source)
[...]
Caused by: java.lang.NoSuchMethodException: org.acme.MyBeanInterceptor.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at io.quarkiverse.cxf.CXFRuntimeUtils.getInstance(CXFRuntimeUtils.java:34)
	... 33 more
```

It can be easily reproduced with the following reproducer:

[reproducer-cxf-interceptors-with-cdi.zip](https://github.com/quarkiverse/quarkus-cxf/files/12145253/reproducer-cxf-interceptors-with-cdi.zip)

Workaround used for now is to not use CDI annotations on the interceptor class, and resolve the MyBean dependency with:

```java
CDI.current().select(MyBean.class).get();
```

**Comment by shumonsharif** [comment]
Hi @mederel I don't believe your interceptor is implemented correctly.  Perhaps try something like the below?

```java
@ApplicationScoped
@Unremovable
public class MyBeanInterceptor extends AbstractSoapInterceptor {

  @Inject
  private MyBean myBean;

  public MyBeanInterceptor() {
    super(Phase.PRE_LOGICAL);
  }

  @Override
  public void handleMessage(SoapMessage soapMessage) throws Fault {
    System.out.println(myBean.getBlabla());
  }
}
```

Let us know if any questions, and you can review the CDI docs at:
https://quarkus.io/guides/cdi-reference#simplified-constructor-injection

**Comment by ppalaga** [comment]
Sorry for the inconvenience, @mederel! Indeed, this is a common consequence of Quarkus trying to reduce the code of the app as much as possible. If it sees that a bean is not injected anywhere, then it removes it from the app. Adding `@io.quarkus.arc.Unremovable` to the bean class should indeed workaround it.

When thinking of it more, from the app dev perspective, the bean is not unused: it is referenced in application.properties. I think we could add some code that makes beans mentioned in interceptors & Co unremovable automatically.

**Comment by mederel** [comment]
> Sorry for the inconvenience, @mederel! Indeed, this is a common consequence of Quarkus trying to reduce the code of the app as much as possible. If it sees that a bean is not injected anywhere, then it removes it from the app. Adding `@io.quarkus.arc.Unremovable` to the bean class should indeed workaround it.
> 
> When thinking of it more, from the app dev perspective, the bean is not unused: it is referenced in application.properties. I think we could add some code that makes beans mentioned in interceptors & Co unremovable automatically.

My concern is not really about the Unremovable but more about the constructor argument injection that does not work. It can be seen as a good practice to inject things through a constructor so that when writing the tests for instance it is pretty clear what are the required objects.

**Comment by mederel** [comment]
> 



> > more about the constructor argument injection that does not work.
> 
> The constructor injection per se works as shown in https://github.com/quarkiverse/quarkus-cxf/pull/955/files#diff-4b657946ab53218d41e9dabc24d7865c257c333030b811f5e800dad4a084bba3R61-R71 but it is a bit limited: you cannot have the fields final because Quarkus CDI container needs a non-private no-arg constructor. (It can auto-generate it in some situations, but not in the linked test, perhaps because it is an inner class.) Anyway, the limitation is given by Arc and you may try your luck submitting the issue in [Quarkus issue tracker](https://github.com/quarkusio/quarkus/issues).

Indeed I finally understood that is linked to the final addBefore addAfter methods in AbstractPhaseInterceptor that make any subclass "non proxyable". In the end one good in between solution might be:

```java
@ApplicationScoped
@Unremovable
public class MyBeanInterceptor extends AbstractSoapInterceptor {
  private final MyBean myBean;

  private MyBeanInterceptor() {
    this(null);
  }

  @Inject
  public MyBeanInterceptor(MyBean myBean) {
    super(Phase.PRE_LOGICAL);
    this.myBean = myBean;
  }

  @Override
  public void handleMessage(SoapMessage soapMessage) throws Fault {
    System.out.println(myBean.getBlabla());
  }
}
```

It seems to work with the private non args constructor...

Anyway thanks for renaming the issue, and the contribution.

**Comment by ppalaga** [comment]
What a trick! I thought a private non-arg constructor would not work.
