### ISSUE TITLE
Support generating objects from XSD files

### ISSUE THREAD

**Issue by rokkolesa** [quarkiverse/quarkus-cxf#951]
It would be very useful if the plugin would support generating objects from XSD files (it currently only supports creating objects from WSDL).

You could leverage the `xjc` tool which the project already uses for `wsdl2java` generation.
It would also be useful to support `xjb` files as well to customize the object generation, or just in general to support additional params.

Right now, we have to use e.g. `org.codehaus.mojo:jaxb2-maven-plugin` to achieve this with the `xjc` goal.

**Comment by ppalaga** [comment]
I'd be all for this. But this being a pure JAXB use case I guess Quarkus JAXB extension is a better place for it. Would you mind [submitting a new Quarkus feature request?](https://github.com/quarkusio/quarkus/issues/new?assignees=&labels=kind%2Fenhancement&projects=&template=feature_request.yml)

**Comment by rokkolesa** [comment]
Of course! A new issue is created in the main quarkus repo.
I guess this issue can be closed now.
