### ISSUE TITLE
Support & test the case when a remote WSDL URL requires basic authentication

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#969]
Followup of https://github.com/quarkiverse/quarkus-cxf/issues/919

**Comment by ppalaga** [comment]
Note to myself: To make this testable, we need to enable this line and switch `secureWSDLAccess` to  `true` https://github.com/l2x6/calculator-ws/commit/ceffb9886d1b9c216745a531403f17fc70375be1#diff-8cf8e44f6846df6c175feb48f29e740f9d002ba4eccb552e0236f461bf970f14R31 Instead of making this configurable via container property, it would perhaps be better to add a new service, so that the test does not need to start the container twice.

**Comment by dufoli** [comment]
I found this commit on cfx : https://github.com/apache/cxf/commit/8ebe5261f0dcb792de4acb4057b611dd446b4bd4
but it was removed with : https://github.com/apache/cxf/commit/f25e730dd9000f2119ee972295cc7adaf6fdbb07
and here is the ticket about analysys : https://issues.apache.org/jira/browse/CXF-5922

**Comment by dufoli** [comment]
my bad. I read too fast...
I have dig in cxf jira and found few other ticket indeed. 
https://issues.apache.org/jira/browse/CXF-1480
https://issues.apache.org/jira/browse/CXF-3421
anyway, it seems to be fixed...since a long time.... so it is only related to quarkus cxf then...
