### ISSUE TITLE
Would it be too difficult to resove test dependencies with Universe BOM only?

### ISSUE THREAD

**Issue by x80486** [quarkiverse/quarkus-cxf#972]
I usually have to declare `implementation(enforcedPlatform("io.quarkus:quarkus-universe-bom:X.Y.Z.Final"))` only in `Gradle` in order to resolve all `Quarkus` dependencies pinned/released with the `Quarkus` version in question.

This still works file with `io.quarkiverse.cxf:quarkus-cxf`, but somehow `Gradle` is unable to resolve `io.quarkiverse.cxf:quarkus-cxf-test-util`.

I guess it's because it might not be included? Or is this more complex?

> I noticed there is a `io.quarkiverse.cxf:quarkus-cxf-bom` and `io.quarkiverse.cxf:quarkus-cxf-bom-test`, but it would be great, if possible, to use only the `quarkus-universe-bom`, so all dependencies are aligned with the release in question.

**Comment by ppalaga** [comment]
I feel your pain @x80486, but I'd prefer keeping the entries now present in `quarkus-cxf-bom-test` out of `quarkus-cxf-bom`. The level of care and various kinds of guarantees (backwards compatibility, CVE fixing) is a bit different for the two. While `quarkus-cxf-bom` is supposed to offer stable production ready software, `quarkus-cxf-bom-test` is more like our internal utilities that we can break whenever we want. Does that make sense?

**Comment by x80486** [comment]
Totally! I usually treat test dependencies as the rest, but I understand. I just thought initially that it may have been delayed in the process of making/polishing the extension.

Not a big deal. Thanks for the explanation! :bow:
