### ISSUE TITLE
[CXF 4.0.3] OpenTelemetry Tracing Feature

### ISSUE THREAD

**Issue by AndreasPetersen** [quarkiverse/quarkus-cxf#985]
We have the [Metrics Feature](https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf-rt-features-metrics.html) which adds Micrometer metrics.

Is there a OpenTelemetry Tracing Feature that adds tracing to Apache CXF SOAP clients?

**Comment by shumonsharif** [comment]
OpenTelemetry should be available in CXF 4.0.3 [1], which hasn't been released yet.

There's some documentation about the OpenTelemetry integration [2], which should help once it's available.

[1] https://issues.apache.org/jira/browse/CXF-8457
[2] https://cwiki.apache.org/confluence/display/CXF20DOC/Using+OpenTelemetry#UsingOpenTelemetry-DistributedTracingwithOpenTelemetryandJAX-WSsupport

**Comment by ppalaga** [comment]
Quarkus CXF main branch is now on CXF 4.0.3. Would anybody like to give a try?
