### ISSUE TITLE
Allow configuration of proxy authentication via application.properties

### ISSUE THREAD

**Issue by shumonsharif** [quarkiverse/quarkus-cxf#988]
As requested by @ppalaga in https://github.com/quarkiverse/quarkus-cxf/pull/986#issuecomment-1699341406.

We can make the [proxy authentication](https://cxf.apache.org/docs/client-http-transport-including-ssl-support.html#ClientHTTPTransport(includingSSLsupport)-ProxyAuthentication) properties configurable via `application.properties`.  I haven't thought through this - but wondering if we can also optionally allow setting a system property for HTTPS endpoints, see https://github.com/quarkiverse/quarkus-cxf/discussions/941.

> This works over HTTPS and HTTPS, but note for the latter it is necessary to set the following system property (see [here](https://www.oracle.com/technetwork/java/javase/8u111-relnotes-3124969.html) for more information "Disable Basic authentication for HTTPS tunneling"):

> `-Djdk.http.auth.tunneling.disabledSchemes=`

**Comment by ppalaga** [comment]
> wondering if we can also optionally allow setting a system property for HTTPS endpoints

You mean we should have a new client property that would trigger setting `jdk.http.auth.tunneling.disabledSchemes=""` ?

Or you perhaps mean that we should fully autodetect when `jdk.http.auth.tunneling.disabledSchemes=""` should be set?

**Comment by shumonsharif** [comment]
I was thinking the first option, so that it's in control for the user - given it's a system property that would apply to the JVM, I'm not sure if full auto detect can have unintended consequences - for example if there are both https and http endpoints?
