### ISSUE TITLE
HTTP/2 - Quarkus doesn't resend POST when server does not allow HTTP/2 (downgrade protocol)

### ISSUE THREAD

**Issue by brunomaso1** [quarkiverse/quarkus-cxf#989]
**Problem:**
_When using Quarkus to consume a SOAP service in witch the server doesn't support HTTP/2, Quarkus doesn't send the POST again with the protocol HTTP 1.1._

**Description:**
There are some scenarios where Quarkus needs to consume a SOAP service in witch the server doesn't support HTTP/2. The Apache Client uses HTTP/2 for POSTs, but some servers doesn't support this protocol yet. 

The comunication it's via HTTP (so it uses H2 protocol), but the server doesn't accept the HTTP/2 protocol via HTTP.
For this cases, the server is returning 403 - Forbidden, but Quarkus doesn't send the post again with the protocol HTTP 1.1 (downgrade).

Here is a screenshot of WireShark logs for a POST:
![imagen](https://github.com/quarkiverse/quarkus-cxf/assets/10601517/766ac689-fd8b-40fa-8a16-f5cde3f09fef)

And here is a screenshot for a GET:
![imagen](https://github.com/quarkiverse/quarkus-cxf/assets/10601517/39d61892-aff1-4d7d-b7ae-618e9f020900)

In the case of the GET it works fine (the client makes 3 requests). 
The first request is the same as the POST (`Connection: Upgrade, HTTP2-Settings`), but then it makes two more with the protocol HTTP 1.1

**Technologies:**

- Java 17
- SAP NetWeaver 7.5
- Quarkus platform version 3.1.1.Final

**Console error:**
```
Caused by: org.apache.cxf.transport.http.HTTPException: HTTP response '403: (POST http://productionserver/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_I4D_FI_100&receiverParty=&receiverService=&interface=SI_SAP_MaestroProveedores_sync_out&interfaceNamespace=http://imm.gub.uy/SAP/MaestroProveedores) 403' when communicating with http://productionserver/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_I4D_FI_100&receiverParty=&receiverService=&interface=SI_SAP_MaestroProveedores_sync_out&interfaceNamespace=http://imm.gub.uy/SAP/MaestroProveedores

        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1653)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1660)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1602)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1396)
        at org.apache.cxf.ext.logging.LoggingOutputStream.postClose(LoggingOutputStream.java:53)
        at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:228)
        at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
        at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:696)
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:528)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:439)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:354)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:312)
        at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
        at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:140)
        ... 39 more
```

Keep me posted if you need more information.

**Comment by brunomaso1** [comment]
Hi @shumonsharif , thanks for your time.

I will try the async way and post here the results (first I have to learn more about this subject).
By the way, when you said:

> I believe a downgrade from HTTP/2 to HTTP can only occur with an HTTP/2 compatible client

Did you mean that I was not using HTTP/2 compatible client? Maybe you meant to say "I'm not hitting a HTTP/2 compatible server". I thought Apache CXF was using a HTTP/2 client to consume the service, because it's the client who send the header `Connection: Upgrade, HTTP2-Settings`.
Maybe I didn't understand well, but the client is Apache-CXF 4.0.1.

Also, I just got the error abolve, no more information, so I had to use WireShark to get the real problem.

> Also, is your the endpoint you're hitting using HTTP or HTTPS?
It's over HTTP, and the server doesn't work with HTTP/2 over HTTP, only over HTTPS (here a [note ](https://userapps.support.sap.com/sap/support/knowledge/en/3280423) of the problem).

Thanks! I will post the async code when I get it working.

NB: I just notice that you need a SAP account to access the note, I copied the important part here:

> Symptom
> 
> When accessing a custom URL provided by a reverse proxy to the backend system, a "403 Access Denied" error is thrown at the browser.
> 
> Upon checking a dev_icm trace file (at least level 2) from the affected backend instance, there is an entry like below
> 
> [Thr 140425534674688] *** ERROR => forbidden protocol upgrade to h2c {00231e05} [http_plg.c 6627]
> [Thr 140425534674688]              role: Server, protocol: HTTP, local: <backend instance IP>:<backend instance port>, peer: <reverse proxy IP>:<reverse proxy port>
> [Thr 140425534674688] *** ERROR => HttpPlugInHandleNetData: HttpParseRequestHeader failed (rc=701) [http_plg.c   2513]
> Environment
> 
> ABAP Platform all versions
> 
> SAP NetWeaver 7.4 or higher
> 
> SAP Kernel 749 or higher
> Cause
> 
> The proxy is sending the Upgrade header field with the "h2c" token for new connections to the SAP system. This is a mechanism where the HTTP client tries to upgrade the HTTP connection to HTTP/2.
> 
> However, the SAP system supports the use of HTTP/2 only over HTTPS, and not over HTTP. Therefore, the error "forbidden protocol upgrade to h2c".
> Resolution
> 
> Disable the upgrade of HTTP connections to HTTP/2 feature on the reverse proxy.

**Comment by shumonsharif** [comment]
> Did you mean that I was not using HTTP/2 compatible client? Maybe you meant to say "I'm not hitting a HTTP/2 compatible server". I thought Apache CXF was using a HTTP/2 client to consume the service, because it's the client who send the header `Connection: Upgrade, HTTP2-Settings`. Maybe I didn't understand well, but the client is Apache-CXF 4.0.1.

Whoops, I meant to say "HTTP/2 compatible client **_and server_**".  I believe they would *both* need to be HTTP/2 compatible for the downgrade to work, but I'm no expert on this topic.  @ppalaga Do you happen to know?

> Also, is your the endpoint you're hitting using HTTP or HTTPS?
>> It's over HTTP, and the server doesn't work with HTTP/2 over HTTP, only over HTTPS 

Thanks for the additional context, and please keep us posted on the results of trying the async client.

**Comment by ppalaga** [comment]
Thanks for the detailed report, @brunomaso1! I also think the downgrade with the default HTTP client should work out of the box. However, the current behavior is coming either from CXF or even from `java.net.http.HttpClient`. Would you mind filing a an issue in [CXF](https://issues.apache.org/jira/browse/CXF)? I do not think we can fix the root cause here. 

As for possible workarounds, except for `quarkus-cxf-rt-transports-http-hc5`, you can also try one of the following:

A. Force HTTP version 1.1 on the default HTTP client. With the upcoming Quarkus CXF release 2.3.1 and 2.2.3, this will be a matter of adding `quarkus.cxf.client.myClient.version = 1.1` to `application.properties`. With 2.3.0 and 2.2.2, you can achieve it by something like the following:

```
@ApplicationScoped
public class Init {
void onStart(@Observes StartupEvent ev) {

     HTTPConduitConfigurer httpConduitConfigurer = new HTTPConduitConfigurer() {
         public void configure(String name, String address, HTTPConduit c) {
             c.getClient().setVersion("1.1");
         }
     };

     final Bus bus = BusFactory.getThreadDefaultBus();
     bus.setExtension(httpConduitConfigurer, HTTPConduitConfigurer.class);
}
}
```

B. Switch to the good old `java.net.HttpURLConnection`. This will also be easier with  Quarkus CXF releases 2.3.1 and 2.2.3 where it will be possible to add `quarkus.cxf.client.myClient.http-conduit-factory = URLConnectionHTTPConduitFactory` to `application.properties`. For 2.3.0 and 2.2.2, you can try

```
@ApplicationScoped
public class Init {
void onStart(@Observes StartupEvent ev) {

     final Bus bus = BusFactory.getThreadDefaultBus();
     bus.setExtension(new URLConnectionHTTPConduitFactory(), HTTPConduitFactory.class);

}
public static class URLConnectionHTTPConduitFactory implements HTTPConduitFactory {
    @Override
    public HTTPConduit createConduit(HTTPTransportFactory f, Bus bus, EndpointInfo endpointInfo, EndpointReferenceType target)
            throws IOException {
        return new URLConnectionHTTPConduit(bus, endpointInfo, target);
    }
}
}
```

**Comment by brunomaso1** [comment]
Thanks @ppalaga and @shumonsharif for your responses.

I tested two solutions:

1. The async way (`quarkus-cxf-rt-transports-http-hc5`):
After changing the code to make it async and executing the request, we can see that the request is sent via HTTP 1.1:
![imagen](https://github.com/quarkiverse/quarkus-cxf/assets/10601517/70a00bbf-42a0-4974-bf5b-70ab0caab39d)

 2. Changing the client HTTP version:
![imagen](https://github.com/quarkiverse/quarkus-cxf/assets/10601517/e38bfe50-b16e-4ffe-b7ec-9ad0f292f81f)

So both ways worked, as it seems that they are using other client or other configuration under the hood.

I will fill an issue in CXF jira (I'm waiting for the new user request witch I didn't have).
Feel free to answer this [StackOverflow ](https://stackoverflow.com/questions/76731416/quarkus-apache-cxf-httpexception-http-response-403-when-comunicating-w) question related with the problem.

Thanks again.

**Comment by ppalaga** [comment]
Thanks for the feedback @brunomaso1! 

Please create the issue in CXF and paste the link here. I'd keep this issue open till it is resolved in CXF.

**Comment by brunomaso1** [comment]
Hi,

Here is the issue in CXF Jira: [CXF-8923](https://issues.apache.org/jira/browse/CXF-8923)

Thanks.

**Comment by brunomaso1** [comment]
Hi,

As commented on the CXF Jira (link above), this is not a bug from CXF, but the server (the server has to ignore the Upgrade header and continue processing the request (without http/2); in this case the server send a 403, witch is wrong).

Thanks for your time.

**Comment by spoileduwp45** [comment]
@shumonsharif https://stackdev.space/questions/the-camel-cxf-proxy-is-having-issues-communicating-with-the-http-endpoint
